### ISSUE TITLE
pathOrLazy

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1084]
**Is your feature request related to a problem? Please describe.**

Sometimes creating a default value for [pathOr](https://ramdajs.com/docs/#pathOr) is not cheap.

```js
const key = pathOr(new Date().getTime() + Math.random(), ['options', 'key'], notification);
```
**Describe the solution you'd like**

Whould be nice to have `pathOrLazy` that accepts a function instead of value as the first argument.

```js
const key = pathOrLazy(() => new Date().getTime() + Math.random(), ['options', 'key'], notification);
```
This way computing a default value only happens when we really need it.

**Additional context**
[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `pathOrLazy` function.

**Comment by willcaul** [comment]
Could I take this one?

**Comment by char0n** [comment]
@willcaul sure, go ahead
