### ISSUE TITLE
concatAll, concatAllRight

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#109]
Abstraction for following functionality + right variant.

```javascript
const a = [1];
const b = [2];
const c = [3];

const result = [...a, ...b, ...c];
```
Something like this could work. We can get Identity value by calling R.empty on String or Array types (Monoid)
```javascript
const concatAll = R.converge(R.reduce(R.concat), [R.empty]);
const concatAllRight = R.converge(R.reduce(R.flip(R.concat)), [R.empty]);
```

- [x] concatAll (one test needs this a fix)
- [ ] concatAllRight

**Comment by char0n** [comment]
Seems like `R.concat` already supports Semigroups. Justs create PR for ramda docs to include info about Semigroup support. We can then go forward implementing concatAll and concatAllRight.

**Comment by Undistraction** [comment]
@char0n What is this implementation doing that a simple version of `concatAll` isn't?

Simple version:
```
const a = [1,2,3];
const b = [4,5,6];
const c = [7,8,9];

const concatAll = reduce(concat, []);

concatAll([a, b, c]) // [1, 2, 3, 4, 5, 6, 7, 8, 9]
```
[REPL](http://ramdajs.com/repl/#?const%20a%20%3D%20%5B1%2C%202%2C%203%5D%3B%0Aconst%20b%20%3D%20%5B4%2C%205%2C%206%5D%3B%0Aconst%20c%20%3D%20%5B7%2C%208%2C%209%5D%3B%0A%0Aconst%20concatAll%20%3D%20reduce%28concat%2C%20%5B%5D%29%3B%0A%0AconcatAll%28%5Ba%2C%20b%2C%20c%5D%29%20%2F%2F%20%5B1%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%2C%209%5D)

**Comment by char0n** [comment]
@Undistraction it handles semigroups (or at least it should)

```js
RA.concatAll(RA.Identity.of(1), RA.Identity.of(1)); // -> Identity(2)
```

**Comment by GingerPlusPlus** [comment]
What should we return for `concatAll([])`? `[]`? `undefined`? A null monad?

**Comment by GingerPlusPlus** [comment]
Or maybe we should leave it explicit.

```js
const concatAll = R.reduce(R.concat)
// Usage:
concatAll([], [[1, 2], [3, 4], [5, 6]])
concatAll('', ['asdf', 'ghjk'])
```

**Comment by GingerPlusPlus** [comment]
Also, in cases in which we output a string, we should dispatch to `R.join('')`

**Comment by char0n** [comment]
Yes this needs some additional brainstorming indeed. IMHO the identity value should be implicit to hide the complexity. We should infer the identity value type from the first item in the input array using `R.empty`.

Regarding the case when passed empty array. IMHO when concatenating nothing, we should return nothing, in this case `null` because in javascript nothing is it's representation.

> Also, in cases in which we output a string, we should dispatch to R.join('')

We don't need to do that, `R.concat` is doing that for us under the hood.

```js
concatAll([]); // => null
concatAll(['a', 'b']); // => 'ab'
concatAll([[1], [2]]); // => [1, 2]
concatAll([RA.identity.of(1), RA.Identity.of(2)]); // => RA.identity(3)

**Comment by GingerPlusPlus** [comment]
I think I'd opt for a little simplest approach possible, even if it doesn't cover all the cases:

```js
const concatAll = array => array.reduce(R.concat)
```

Note that this uses native `Array.prototype.reduce`'s unary version (without the initiall acc, it throws for empty arrays iirc, can't check, on phone), which is not a part of fantasyland compatible foldable.

Also, I'd put @see R.unnest and R.join.

**Comment by GingerPlusPlus** [comment]
Even better idea:

```js
const nullSemigroup = Object.freeze({ concat: R.identity })

const concatAll = R.reduce(R.concat, nullSemigroup)
```

`concatAll([])` returns `nullSemigroup`

**Comment by char0n** [comment]
I like your first idea with array reduction without initialValue. I have modified the signature to handle possible errors and returns null if there is nothing to concat, which is IMHO better then returning obscure `nullSemigroup` which is hard to detect by predicates.
```js
const concatAll = R.ifElse(
  RA.isNonEmptyArray,
  R.invoker(1, 'reduce')(R.concat),
  RA.stubNull,
);

**Comment by GingerPlusPlus** [comment]
`nullSemigroup` could be written in such a way, that it could emulate empty-anything, it wouldn't need to be detected.

Like, it could inherit from an `Array`, and be frozen to always have length 0, and override `concat` to always return the argument... and I think it'd already be pretty good. Even `R.chain` would treat it as an empty array, and thus, kind of monad, I just checked.

At that point, it could be named `Nothing`, or something, it'd be more than `nullSemigroup`.

Returning `null` has that issue that if it's unexpected, it'd blow the program away, with no trace where it came from... It'd need to be very clearly documented.

Also, my 2nd approach has that advantage that it makes no assumptions. Pass it any fantasyland compatible `Foldable` containing `T extends Semigroup`, and it'll do the right thing.

The solution with `reduce` without `initialValue` and returning `null` in case of empty array makes an assumption that you pass an array, or something else that
1. passes `Array.isArray`, 
2. has notion of emptiness,
3. has `reduce` working without `initialValue`.

**Comment by char0n** [comment]
> Returning null has that issue that if it's unexpected, it'd blow the program away, with no trace where it came from... It'd need to be very clearly documented.

Of couse it would be clearly and explicitly documented. 

The  problem that I have with returning monad is that this will be the first function that directly exposes monadic type even for cases when monadic type is not passed via arguments. This IMHO creates a big precedent for RA api. R is using monads heavily under the hoods, but they don't leak outside. Need more opinions on this. 

@Undistraction, @guillaumearm, @rockymadden, @BjornMelgaard opinions ?

**Comment by Undistraction** [comment]
Don't leak the monad. It would be inconsistent.

**Comment by GingerPlusPlus** [comment]
I missed the fact that you can easily get rid of `null`: `R.defaultTo(defaultValue)`.

But you can also easily get rid of `nullSemigroup`: `R.concat(R.__, defaultValue)`.

> Don't leak the monad.

It doesn't have to be a monad.
We could make it only a semigroup to keep things simple, and encourage to get rid of it with the method above.

And, if you really, really want to return `null` in that case, `nullSemigroup` is still useful, it allows to define `concatAll` on every foldable:

```js
const concatAll = R.pipe(
    R.reduce(R.concat, nullSemigroup),
    R.where(R.equals(nullSemigroup), RA.stubNull))
```

**Comment by char0n** [comment]
@GingerPlusPlus feer free to use any monad under the hood as long as it doesn't leak out. And pls use fantasy-land naming for semigroup defined here: https://github.com/char0n/ramda-adjunct/blob/master/src/fantasy-land/mapping.js

**Comment by GingerPlusPlus** [comment]
Also, I don't think we need `concatAllRight`. `concatAll` has that nice property, that it keeps order (`concatAll([[1], [2], [3]]) //=> [1, 2, 3]`), `concatAllRight` is weird, and, if needed, can be trivially added as `R.pipe(R.reverse, RA.concatAll)`.

**Comment by GingerPlusPlus** [comment]
My TypeScript braindump, I'm a TypeScript noob, please advise me on how to type it correctly:

```ts
interface Foldable<T> {
    reduce<Acc>(fn: (acc: Acc, val: T) => Acc, initAcc: Acc): Acc;
}

interface Semigroup<T> {
    concat(other: Semigroup<T>): Semigroup<T>;
}

export interface Static {
    concatAll<T, S extends Semigroup<T>>(foldable: Foldable<S>): S | null;
}
```

Or would this be better?

```ts
interface Semigroup {
    concat(other: Semigroup): Semigroup;
}

export interface Static {
    concatAll<S extends Semigroup(foldable: Foldable<S>): S | null;
}
```

Or

```ts
interface Semigroup<T> {
    concat(other: Semigroup<U>): Semigroup<T | U>;
}
```

I have no idea how to express that `concat` requires argument to be the same semigroup.

Also, is TypeScript smart enough to figure that `Array` is `Semigroup` and `Foldable`, and `string` is `Semigroup`?

If not, how do I express it?

Maybe I should just create special cases for `F = Array<String>` and `F = Array<Array<T>>`?

**Comment by char0n** [comment]
I wouldn't worry about `concatRightAll` for now. Let's implement it if there is more user request and usecases for it.

Regarding the Typescript signatures, the only competent person here about it @BjornMelgaard, maybe he can help. Meanwhile you can research ramda typings here https://github.com/types/npm-ramda

**Comment by GingerPlusPlus** [comment]
I got it :) jsDoc left and I'm ready to PR.

**Comment by GingerPlusPlus** [comment]
I can't use `"fantasy-land/concat"`, it apparently breaks `R.concat`: https://circleci.com/gh/char0n/ramda-adjunct/3631?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by GingerPlusPlus** [comment]
Why reopen, @char0n?

**Comment by char0n** [comment]
concatAllRight is still under consideration. Just waiting for usecases. Also I need to look at this commented tests.

**Comment by char0n** [comment]
Closing this in favor of #408 and #409 (applied divide and conquer mechanism ;)
