### ISSUE TITLE
isPositiveZero

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1108]
Object.is can be used to provide the check under hood. In JavaScript zero can be positive or negative:
```js
+0
-0
0 // this is implicitly positive zero
```

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `isPositiveZero` function.

**Comment by js636f** [comment]
Hello, @char0n! Can I work on this feature?

**Comment by char0n** [comment]
Hello @js636f. You've been assigned. Good luck!

**Comment by sravan7** [comment]
@char0n  Dont Know how to write this like a module that was done in this repo. Help me 

`const isPositveZero = (zero)=>(1/zero>=0)?true:false`

Above solution works.

**Comment by char0n** [comment]
@sravan7 the example [pull request](https://github.com/char0n/ramda-adjunct/pull/1067) is linked in description of this issue. For more examples see other merged PRs. Regarding your implementation - it's not correct - `isPositiveZero(1)` whould return 1. You have to use [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) to check for it.

**Comment by js636f** [comment]
@char0n, as far as I understand the PR should look like this:

1. New file src/isPositiveZero.js
2. Changes in src/index.js
3. New file test/isPositiveZero.js
4. Changes in types/index.d.ts
5. New file  types/test/isPositiveZero.ts 

Am I right about the PR structure?

I think the main file should look like this:
```
/**
 * Checks if input value is a positive zero.
 * other stuff (I will have some questions about this section later).
 
 */
 
const isPositiveZero = value => Object.is(value,0);

export default isPositiveZero;
```
Is it OK?

**Comment by char0n** [comment]
Structure is about right. The main file is also about right, but there are two problems.

1.) Function must be curried

```js
const isPositiveZero = curry1(value => Object.is(value,0));

2.) Object.is must be polyfiled if not present (IE)

Polyfils are maintained here: https://github.com/char0n/ramda-adjunct/tree/master/src/internal/polyfills

How to write a polyfill can be found here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#polyfill

Here is another example of PR that needed a polyfill: https://github.com/char0n/ramda-adjunct/pull/1080

**Comment by js636f** [comment]
OK, thank you very much! I'm keep working.

**Comment by js636f** [comment]
@char0n, I think the core code should look like this:

Polyfill file: src/internal/polyfills/Object.is.js

```
//source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#polyfill
//docs https://www.ecma-international.org/ecma-262/6.0/#sec-samevalue
const polyfill = function(x, y) {
    // SameValue algorithm
    if (x === y) { // Steps 1-5, 7-10
      // Steps 6.b-6.e: +0 != -0
      return x !== 0 || 1 / x === 1 / y;
    } else {
      // Step 6.a: NaN == NaN
      return x !== x && y !== y;
    }
  };

const objectIsPolyfill = Object.is ? Object.is : polyfill;

export default objectIsPolyfill;
```

Feature file: src/isPositiveZero.js

```
import curry1 from 'ramda/src/internal/_curry1';
import objectIsPolyfill from './internal/polyfills/Object.is'

/**
 * Checks if input value is a positive zero.
 * other stuff 
 
 */
 
const isPositiveZero = curry1(value => objectIsPolyfill(value, 0));

export default isPositiveZero;
```
Is it OK?

**Comment by char0n** [comment]
@js636f it would be best if you would issue a PR we will collaborate there. Code review comments allow me to address individual code lines on your code then. So pls issue a PR and we'll discuss it there.

Regarding the polyfill, it's not possible to include comments like this. These comments assume that we copied the code from the MDN. This is something we cannot do, the code there is licensed and we cannot incorporate it into our codebase just like that. So pls remove the comments and I will assume that you wrote that code yourself.
```
//source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#polyfill
//docs https://www.ecma-international.org/ecma-262/6.0/#sec-samevalue
```

**Comment by js636f** [comment]
@char0n, OK, thank you. I'll issue an PR.

**Comment by char0n** [comment]
@js636f important update. This [PR](https://github.com/char0n/ramda-adjunct/pull/1109) had uncovered that `R.identical` object is using `Object.is` under the hood. So no need for polyfill. Pls use the mention PR as a template for your work.

**Comment by js636f** [comment]
@char0n, OK

**Comment by js636f** [comment]
@char0n, I made the [PR](https://github.com/char0n/ramda-adjunct/pull/1111)

**Comment by char0n** [comment]
Closed by https://github.com/char0n/ramda-adjunct/pull/1111
