### ISSUE TITLE
How to use same variable of Ramda with Ramda Adjunct

### ISSUE THREAD

**Issue by microcipcip** [char0n/ramda-adjunct#111]
Is it technically possible to use the same variable of Ramda with this library? I basically want to avoid to use different API for this addon...maybe with `Object.assign`?
What I mean is:
```
let _ = require('ramda)
let RA = require('ramda-adjunct')
Object.assign(_, RA)

console.log(_.isBoolean(true)) // true
```

BTW, great library! I was almost switching to lodash/fp before finding this!

**Comment by char0n** [comment]
Hi @microcipcip,

Yes, basically if you want to use it like that, you do exactly that. Al-tho I would not recommend it. Both R and RA have different documentations, and using RA like that will make it unclear where the function comes from. 

```javascript
Object.assign(R, RA);
```
Anyway looking at this, I can understand why one would like to use it like this. I suggest we standardize it somehow. I propose this:

CommonJS
```javascript
const R = require('ramda');
const RA = require('ramda-adjunct');

RA.adjunct(R);
```
ES6
```javascript
import R from 'ramda';
import RA from 'ramda-adjunct';

RA.adjunct(R);
```
This is done once in you application bootstrap file. I wouldn't do it implicitly, but rather have standardized API for it. `RA.adjunct` will mutate it's only parameter and assigns it's default export to this param. What to you say ?


> BTW, great library! I was almost switching to lodash/fp before finding this!

Thanks. That was the point. To have a library that acts as and adjunct to Ramda. I am glad you're finding it useful.

**Comment by microcipcip** [comment]
> This is done once in you application bootstrap file. I wouldn't do it implicitly, but rather have standardized API for it. RA.adjunct will mutate it's only parameter and assigns it's default export to this param. What to you say ?

That is exactly what I thought, so, if this will allow me to use the same variable I use for Ramda, that would be great :)

**Comment by char0n** [comment]
Ok this issue has been categorized as feature. RA.adjunct will be created to encapsulate the logic.

Meantime use `Object.assign(R, RA)` as a workaround.

**Comment by char0n** [comment]
@BjornMelgaard, @Undistraction would like your opinion on this one. Thanks

**Comment by BjornMelgaard** [comment]
@microcipcip using `Object.assign(R, RA)` you are depriving yourself from tree-shaking.

babel-plugin-lodash wouldn't work too
```js
    ["lodash", {
      "id": ["ramda", "ramda-adjunct"]
    }],
```

**Comment by char0n** [comment]
@BjornMelgaard this is a non issue in node env. The important question is: do we want to introduce `RA.adjunct(R)` which will promote something like that ?

I'm not even sure if commonjs or ES6 module cache will allow us to do that, so that it works all the time.

**Comment by BjornMelgaard** [comment]
@char0n I don't like pollutions of global variables

**Comment by microcipcip** [comment]
@BjornMelgaard Indeed I use Ramda mainly in node so yes, it's a non issue for me too, but thanks for letting me know about this problem.

**Comment by Undistraction** [comment]
Personally I don't much like the idea. It's rather non-obvious for someone coming to the code fresh and pretty surprising generally. However might be worth looking at how [fs-extra](https://github.com/jprichardson/node-fs-extra) does it - they effectively proxy all methods from `fs` so you can just do `import fs from 'fs-extra';` and access both original and augmented functions from the same place. At least that way it's obvious what is happening in every file and there is a single import and object.

**Comment by char0n** [comment]
@Undistraction the same principle that is already described here, except that it is reversed (https://github.com/jprichardson/node-fs-extra/blob/master/lib/index.js).

**Comment by Undistraction** [comment]
I'm going to close this as I don't think we have any intention of doing what @microcipcip proposed. Feel free to reopen if its worth discussing more.

**Comment by char0n** [comment]
Agree, this is not something we want to do anymore. @microcipcip sorry.

**Comment by microcipcip** [comment]
Np, my initial solution works well for me ;)
