### ISSUE TITLE
isSet

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1110]
**Is your feature request related to a problem? Please describe.**

Predicate for determining if a provided value is an instance of a Set.

**Describe the solution you'd like**

```js
RA.isSet(new Set([1, 2])); //=> true
RA.isSet([1, 2]); //=> false
```

**Additional context**
[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `isSet` function. Issue original conceived in https://github.com/char0n/ramda-adjunct/issues/66

**Comment by realSaddy** [comment]
Could I handle this one?
