### ISSUE TITLE
isMap

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1113]
**Is your feature request related to a problem? Please describe.**

Predicate for determining if a provided value is an instance of a Map.

**Describe the solution you'd like**

```js
RA.isMap(new Map()); //=> true
RA.isMap({ a: 1 }); //=> false
```

**Additional context**
[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `isMap` function. Issue original conceived in https://github.com/char0n/ramda-adjunct/issues/66

**Comment by realSaddy** [comment]
Could I handle this?

**Comment by char0n** [comment]
@realSaddy sure. Assigned to you

**Comment by realSaddy** [comment]
Would you also like isNotMap or isNotSet?

**Comment by char0n** [comment]
@realSaddy I can create issues for them, but not sure if they would be any value. Let's the those issues for vote and we'll find out if there are real world usecases for them.

**Comment by char0n** [comment]
isNotSet: https://github.com/char0n/ramda-adjunct/issues/1123
isNotMap: https://github.com/char0n/ramda-adjunct/issues/1122

I've put them for voting to see a real value in them. Let's see.
