### ISSUE TITLE
zipObjWith

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1129]
**Is your feature request related to a problem? Please describe.**

Same as https://ramdajs.com/docs/#zipObj but accepts a binary function as the first argument. This binary function returns an object which gets merged into final resulting object.

**Describe the solution you'd like**

```js
RA.zipObjWith((value, key) => [key, `${key}${value + 1}`]), ['a', 'b', 'c'], [1, 2, 3]); // => {a: 'a2', b: 'b3', c: 'c4'}
```

**Describe alternatives you've considered**

```js
RA.zipObjWith((value, key) => ({[key]: value}), ['a', 'b', 'c'], [1, 2, 3]); // => {'a': 1, 'b': 2, 'c': 3}
RA.zipObjWith((value, key) => `key${value + 1}`, ['a', 'b', 'c'], [1, 2, 3]); // => {'a': a2, 'b': b3, 'c': c4}
```

Before we go for implementation we have to decide which implementation makes more sense and have higher value.

**Comment by thomasmichaelwallace** [comment]
Coming from #801 I think either the first option makes sense:

```RA.zipObjWith((value, key) => ({[key]: value}), ['a', 'b', 'c'], [1, 2, 3]); // => {'a': 1, 'b': 2, 'c': 3}```

Or, to match the proposed `unzipObjWith`:

```Ra.zipObjWith((value, key) => [key, `key${value + 1}`]), ['a', 'b', 'c'], [1, 2, 3]); // => {'a': a2, 'b': b3, 'c': c4}```

n.b. I agree that the alternative implementation where you only return the value is not as good as when you return the key/value pair because it takes away the ability for the user to transform the keys, which is something I think users will want to do.

**Comment by char0n** [comment]
I like the proposal of returning the tuple from the transformer binary function instead of the object. The new proposed behavior can be:
```js
RA.zipObjWith((value, key) => [key, `${key}${value + 1}`]), ['a', 'b', 'c'], [1, 2, 3]); // => {a: 'a2', b: 'b3', c: 'c4'}

@thomasmichaelwallace do we agree ?

**Comment by thomasmichaelwallace** [comment]
Sounds good to me; I can get this done.

I am going to wait until the review on #1130 is complete. This is because I this will have a similar implementation to `unzipObjWith`, and I do not want to make the same mistakes twice! :)
