### ISSUE TITLE
trimCharsStart

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1135]
**Is your feature request related to a problem? Please describe.**
Removes leading specified characters from string.

**Describe the solution you'd like**

```js
RA.trimCharsStart('_-', '-_-abc-_-'); //=> 'abc-_-'
```

**Additional context**

Function should be curried. Related to [trimStart/trimEnd issue](https://github.com/char0n/ramda-adjunct/issues/808).

**Comment by cos1715** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart

**Comment by M-ZubairAhmed** [comment]
@char0n can i take this

**Comment by M-ZubairAhmed** [comment]
@char0n i need help with this one, i am not able to understand how this function should work, in your example you have written that `_-` should replace the string, why it shouldnt output `-abc-_-`

**Comment by char0n** [comment]
Take a look at [lodash.trimStart](https://lodash.com/docs/4.17.15#trimStart). We need exactly the same behavior. In our case the first argument are the characters in form of string that are replacing the characters at the beginning of a value. So our arguments are 
```js
trimCharsStart(chars, value)
```

Now how should it work ? We decompose the `value` into list of characters called `valueCharList` with the following construct `valueCharList = [...value]`. We then iterate this list of characters and checking if the current character is contained within `chars` string. If yes, then we [shift](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift) the `valueCharList`. We repeat iteration until there is match in `chars`. If there is not match we return `valueCharList.join('')`. And that should be the algorithm.

**Comment by M-ZubairAhmed** [comment]
sorry dropping this one, If anyone would like to take this on, feel free

**Comment by char0n** [comment]
No worries.

**Comment by kitasuna** [comment]
@char0n Hi! Mind if I open a PR for this one?

**Comment by char0n** [comment]
@kitasuna go ahead!
