### ISSUE TITLE
trimCharsEnd

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1136]
**Is your feature request related to a problem? Please describe.**
Removes trailing specified characters from string.

**Describe the solution you'd like**

```js
RA.trimCharsEnd('_-', '-_-abc-_-'); //=> '-_-abc'
```

**Additional context**

Function should be curried. Related to [trimStart/trimEnd issue](https://github.com/char0n/ramda-adjunct/issues/808).

**Comment by cos1715** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd

**Comment by dshubhadeep** [comment]
@char0n Could you explain how the trimming is working ?

Shouldn't the output for the above example be `-_-abc-` ?

What would be the output for the following case ? 
```js
RA.trimCharsEnd('_-', '-_-abc-_-^')
```

**Comment by char0n** [comment]
@dshubhadeep the function works exactly the same as [lodash.trimEnd](https://lodash.com/docs/4.17.15#trimEnd). Checkout that function and try to play with it to fully understand it's behavior.

**Comment by kitasuna** [comment]
@char0n Mind if I grab this one too?

**Comment by char0n** [comment]
@kitasuna go ahead. YOu can grab any feature you want labeled by `feature` and `help wanted`
