### ISSUE TITLE
Unable to resolve module://ramda/src/internal/_curry1.js

### ISSUE THREAD

**Issue by wolverineks** [char0n/ramda-adjunct#1140]
**Describe the bug**
I'm trying to use RA.renameKeys on an [expo snack](https://snack.expo.io/@wolverineks/scan-drivers-license)
But importing anything from RA into the file throws this error

`Unable to resolve module://ramda/src/internal/_curry1.js`

importing and using Ramda alone works fine
everything works in a standalone react-native app
so, looks like it might be more of a expo snack issue, but I thought i'd start here first

```js
// package.json
{
  ...
  "ramda": "0.26.1",
  "ramda-adjunct": "2.21.0",
  ...
}
```

**To Reproduce**
1. new expo project
2. import anything from RA

**Expected behavior**
runs

**Comment by char0n** [comment]
@wolverineks this is (as you correctly assumed) problem specific to the expo snack. expo snack is not able to resolve directories inside the ramda package that ramda-adjunct is using. As part of our CI, we run tests of RA agains multiple versions of R in node (multiple versions) and browser (multiple platforms). 

'ramda/src/' contains perfectly valid commonjs code which should be importable directly or indirectly. I'd contact the expo snack developers and let them know about the issue.

Meantime would you be able to use our standalone bundle ? https://www.jsdelivr.com/package/npm/ramda-adjunct?path=dist. RA.web.standalone.min.js contains prebundled ramda + ramda-adjunct in one file.
