### ISSUE TITLE
Assimilate Cottin/ramda-extras

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#115]
https://github.com/Cottin/ramda-extras

**Comment by Undistraction** [comment]
@charOn Anything actionable here or shall we close?

**Comment by char0n** [comment]
I think assimilation may be to big task but we should still review the lib and see if some concepts are suited for RA.

**Comment by char0n** [comment]
We'll not be assimilating this library. Maybe in future will be worth looking again.
