### ISSUE TITLE
New collaborator - @js636f

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1197]
@js636f  I've added you as a collaborator to this repository. Feel free to add yourself into package https://github.com/char0n/ramda-adjunct/blob/0dba9905a3fe15bafc7702a188723de5b8f2e406/package.json#L36 via new PR.

**Comment by js636f** [comment]
@char0n, Thank you! [Done](https://github.com/char0n/ramda-adjunct/pull/1198).

**Comment by char0n** [comment]
@js636f pls also have a look at following documents:
https://github.com/char0n/ramda-adjunct/blob/master/CODE_OF_CONDUCT.md
https://github.com/char0n/ramda-adjunct/blob/master/GOVERNANCE.md
https://github.com/char0n/ramda-adjunct/blob/master/CONTRIBUTING.md

**Comment by js636f** [comment]
@char0n, OK. And I'm waiting for a new task you told me about.

**Comment by char0n** [comment]
@js636f it's issue https://github.com/char0n/ramda-adjunct/issues/624. I did mention you there 6 days ago. Sorry for my lack of response last days, having some health issues lately that I'm working on.

**Comment by js636f** [comment]
@char0n, I'm sorry, I think I missed than mention. I wish you good health. That issue is interesting for me, so I'm starting working on it.

**Comment by char0n** [comment]
cool glad to hear that. The last function that I rectified was  https://github.com/char0n/ramda-adjunct/blob/master/test/isNotNilOrEmpty.js. Next one is https://github.com/char0n/ramda-adjunct/blob/master/test/isNotNull.js and others that follow alphabetically. Thank you for handling this. You be test master after you're finished here ;]

**Comment by js636f** [comment]
Thank you for the additional info. I hope we'll rectify them all :-)

**Comment by js636f** [comment]
@char0n, I made Batch 0 [PR](https://github.com/char0n/ramda-adjunct/pull/1201), for #624, I'll use "ref" in the commit message to link RP's to that issue.
