### ISSUE TITLE
renameKeyWith

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1228]
**Is your feature request related to a problem? Please describe.**

Renames single key of an object.

**Describe the solution you'd like**
```js
const obj = {A: 1};
RA.renameKeyWith(R.concat('a'), 'A', obj); //=> {aA: 1}
```

**Describe alternatives you've considered**

--

**Additional context**

This function should be implemented as specialization of [R.renameKeysWith](https://char0n.github.io/ramda-adjunct/2.23.0/RA.html#.renameKeysWith). 

Related to https://github.com/char0n/ramda-adjunct/issues/1227

- [ ] implement the function
- [ ] add ref to ramda cookbook

**Comment by dbartholomae** [comment]
Happy to take this next week! I could also take a couple, but don't want to take away the opportunity for others to get to know the repo. What's your thought on this?

**Comment by char0n** [comment]
Cool, I've assigned you to this issue. 

> don't want to take away the opportunity for others to get to know the repo. What's your thought on this?

I'd advise to keep the buffer of issues you're implementing to 2 in PR status.I'll try to provide code review and merge as soon as possible.

**Comment by dbartholomae** [comment]
Sounds good! I will be working on the issue in a Twitch live stream on Thursday from 10am CEST onwards, so I assume that the first PR should be ready around 11am CEST (assuming I don't run into trouble with the setup).

**Comment by char0n** [comment]
@dbartholomae, feel free to provide a Twitch live stream link here also. I could promote it a little bit ;]

**Comment by dbartholomae** [comment]
Sure, thanks, it's https://twitch.tv/the_startup_cto

**Comment by char0n** [comment]
@dbartholomae before I close this issue, do you have a recording of you creating the function? thanks

**Comment by dbartholomae** [comment]
> @dbartholomae before I close this issue, do you have a recording of you creating the function? thanks

No, I don't save these sessions for later.
