### ISSUE TITLE
thenCatchP

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1233]
**Is your feature request related to a problem? Please describe.**

Extension for currently available [thenP](https://char0n.github.io/ramda-adjunct/2.23.0/thenP.js.html#line3) function.

**Describe the solution you'd like**
```js
const thenCatchP = R.invoker(2, 'then');
const resolvedPromise = Promise.resolve(3);
const rejectedPromise = Promise.reject(4);

thenCatchP(console.log, console.error, resolvedPromise); //=> outputs 3
thenCatchP(console.log, console.error, rejectedPromise); //=> outputs 4
```

**Describe alternatives you've considered**
[thenP](https://char0n.github.io/ramda-adjunct/2.23.0/thenP.js.html#line3)

**Additional context**
[Promise.prototype.then](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)

**Comment by rjhilgefort** [comment]
Took a shot at this in https://github.com/char0n/ramda-adjunct/pull/1322!
