### ISSUE TITLE
fnull

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1235]
**Is your feature request related to a problem? Please describe.**
fnull is in a function that takes a function as an argument and a number of additional arguments, and returns a function that just calls the original function given. The magic of fnull is that if any of the arguments to the function that it returns are null or undefined, then the original “default” argument is used instead.

**Describe the solution you'd like**
```js
const multiply = (a, b) => a * b;
const safeMultiply = fnull(multiply, [1, 1]);

safeMultiply(2, null); //=> 2
```

**Describe alternatives you've considered**

https://www.linkedin.com/pulse/function-currying-default-params-javascript-vladim%C3%ADr-gorej/

**Additional context**

**Comment by sidag95** [comment]
Can I take a pass at the above?

**Comment by char0n** [comment]
@sidag95 sure you can. Let me know if you have any questions.

**Comment by sidag95** [comment]
Thanks @char0n will ask if and when I have any questions
