### ISSUE TITLE
isIndexed

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1236]
**Is your feature request related to a problem? Please describe.**

To determine if something is an indexed data type. We can start assuming that value is indexed if it's either **String** or **Array** type.

**Describe the solution you'd like**

```js
isIndexed([1]); //=> true
isIndexed('test'); //=> true
```

**Describe alternatives you've considered**
-- 

**Additional context**

Originally conceived in https://github.com/char0n/ramda-adjunct/issues/66

**Comment by damiangreen** [comment]
I'm having a crack at this one

**Comment by char0n** [comment]
Go ahead and good luck!
