### ISSUE TITLE
skipTake

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1237]
**Is your feature request related to a problem? Please describe.**

When given a number n and an array, returns an array containing every nth element

`R.addIndex(R.takeWhile)` with specialized predicate can be used to implement this function.

**Describe the solution you'd like**

```js
skipTake(2, [1,2,3,4]);
//=> [1, 3]

skipTake(3, _.range(20));
//=> [0, 3, 6, 9, 12, 15, 18]
```

**Describe alternatives you've considered**

I've considered [R.takeWhile](https://ramdajs.com/docs/#takeWhile), but doesn't exactly do what we want without specialized composition.

**Additional context**

**Comment by damiangreen** [comment]
I've got a working implementation of this. I can create a PR once I've created tests
