### ISSUE TITLE
invokeArgs

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1239]
**Is your feature request related to a problem? Please describe.**

Invokes the method at path of object with given arguments. Very important requirement for this function is that if method doesn't exists the function returns undefined. This makes this function always safe.

**Describe the solution you'd like**

```js
invokeArgs(['path', 'to', 'method'], [arg1, arg2], object); //=> result of calling object.path.to.method(arg1, arg2)
```

**Describe alternatives you've considered**
--

**Additional context**

[lodash](https://github.com/lodash/lodash/wiki/FP-Guide) already have this method.

**Comment by js636f** [comment]
@char0n, may I work on this?

**Comment by char0n** [comment]
@js636f go ahead. Remember that this function must be `safe`. `Safe` in a sense that when the method on the object path doesn't exists or the symbol at path is not a function the function must return `undefined`. It must never throw Error.

**Comment by js636f** [comment]
OK, thanks! I'll keep this in mind.
