### ISSUE TITLE
sortByProp

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1241]
**Is your feature request related to a problem? Please describe.**

Sorts the list according to the supplied prop

**Describe the solution you'd like**

```js
const sortByFirstItem = R.sortByProp(0);
const pairs = [[-1, 1], [-2, 2], [-3, 3]];
sortByFirstItem(pairs); //=> [[-3, 3], [-2, 2], [-1, 1]]

const sortByName = R.sortByProp('name');
const alice = {
  name: 'ALICE',
  age: 101
};
const bob = {
  name: 'Bob',
  age: -10
};
const clara = {
  name: 'clara',
  age: 314.159
};
const people = [clara, bob, alice];
sortByName(people); //=> [alice, bob, clara]
```

**Describe alternatives you've considered**

---

**Additional context**

Original issue: https://github.com/char0n/ramda-adjunct/issues/945
Blocked by #1240. This function should be implemented as a specialization of [sortByPath](#1240)

**Comment by nolleto** [comment]
Can I get this issue?

**Comment by char0n** [comment]
@nolleto sure, but in order to implement `sortByProp` you have to first implement #1240. So if you want to start somewhere, #1240 is a way to go.

**Comment by tauantcamargo** [comment]
@char0n i don't know if nolleto is working on that.. if no .. assign it to me pls

**Comment by char0n** [comment]
@tauantcamargo I guess he's not. Feel free to issue a PR.

**Comment by nolleto** [comment]
After a loooooong time, I finally created the PR. 

Fun fact: I created the branch and did all changes after merged `sortByPath` PR, but I forgot to create the actual PR 🤦‍♂️
