### ISSUE TITLE
isBigInt

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1253]
**Is your feature request related to a problem? Please describe.**

Predicate for determining if a value is a big int.

**Describe the solution you'd like**
```js
isBigInt(10n); //=> true
isBigInt(10); //=> false
```

**Describe alternatives you've considered**

--

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by danieldeer** [comment]
Hi there, I'm going to work on it
