### ISSUE TITLE
compact

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#127]
https://lodash.com/docs/4.17.4#compact

**Comment by char0n** [comment]
First we would need the [isTruthy](https://github.com/char0n/ramda-adjunct/issues/66) predicate and then
```javascript
const compact = R.filter(RA.isTruhty);
```

**Comment by Undistraction** [comment]
Looks like this is doable now we have `isTruthy` and `isFalsy` …

**Comment by char0n** [comment]
Yep exactly

**Comment by guillaumearm** [comment]
I talk about this in #38.
anyway, I prefer the implementation with R.reject. it's more semantically related to a compacting xD
