### ISSUE TITLE
Code triage badge

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#129]
[![Code Triagers Badge](https://www.codetriage.com/char0n/ramda-adjunct/badges/users.svg)](https://www.codetriage.com/char0n/ramda-adjunct)

**Comment by guillaumearm** [comment]
I have subscribed, and code helpers is still 1, should we wait or what ?

**Comment by char0n** [comment]
It’s 2 already :)

**Comment by Undistraction** [comment]
Closed with #db2a26
