### ISSUE TITLE
the type of `list` is not `readonly` for `mapIndexed`

### ISSUE THREAD

**Issue by damiangreen** [char0n/ramda-adjunct#1330]
the type of the input argument `list` is not `readonly`  for the `mapIndexed` function

This is the type definition of `mapIndexed`
   `mapIndexed<T, U>(iterator: (elem: T, key: number, list: T[]) => U): (list: T[]) => U[];`

To tell the compiler its immutable we're forced to coerce;
`   mapIndexed(renderItem)(renderItems as T[])`

**Expected behavior**
If list is not mutated I expect the type to be
   `mapIndexed<T, U>(iterator: (elem: T, key: number, list: readonly T[]) => U): (list: T[]) => U[];`

For comparison the signature of `map` which the function follows does have readonly:

` map<T, U>(fn: (x: T) => U, list: ReadonlyArray<T>): U[];`

**Comment by char0n** [comment]
@damiangreen thank you!

Would you mind issuing a PR for that? And maybe also provide [typings test](https://github.com/char0n/ramda-adjunct/tree/master/types/test) to verify correct behavior?
