### ISSUE TITLE
filterIndexed

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1346]
**Is your feature request related to a problem? Please describe.**

[R.filter](https://ramdajs.com/docs/#filter) doesn't expose index to the predicate function. Let's create a function that does and call it `filterIndexed`.

**Describe the solution you'd like**
```js
filterIndexed((v, idx) => idx === 0, [1, 2, 3); // => [1]
```
Possible implementation
```js
const filterIndexed = R.addIndex(R.filter);
```
**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by willblake01** [comment]
@char0n Hi, I'd like to try this one please!

**Comment by char0n** [comment]
Go ahead

**Comment by char0n** [comment]
Issue available to pick up again by anybody interested.

**Comment by jprask** [comment]
@char0n Hey, might I try this one?

**Comment by char0n** [comment]
@jprask sure, go ahead!

**Comment by devadeka** [comment]
Hey, could I have a go at this for hacktoberfest? if it is ok to have multiple people attempt the same issue.
Ta

**Comment by char0n** [comment]
@devadeka unfortunately it's reserved for @jprask. 

Just to be sure @jprask still interested in this issue ?

**Comment by jprask** [comment]
@char0n Yeah, my apologies on the delay here, ended up busy with some parallel stuff. Starting it now.
