### ISSUE TITLE
flattenDepth

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1364]
**Is your feature request related to a problem? Please describe.**
`flattenDepth` function contains reference to internal ramda function called `_makeFlat` which further makes reference to `_isArrayLike`. We have `_isArrayLike` function implemented in ramda-adjunct, so we only need to reimplement `makeFlat` into our codebase. Be aware that function just cannot be copied due to licensing reasons, it really needs to be understood and reimplemented. 

**Describe the solution you'd like**
See text above..

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by char0n** [comment]
@willblake01 this is possible candidate for you.

**Comment by willblake01** [comment]
@char0n This one would be a good challenge. I'm looking over it but I don't see isArrayList. Just want to confirm, did you mean isArrayLike?

**Comment by char0n** [comment]
@willblake01 sorry, is was `isArrayLike`. I've corrected the issue description.
