### ISSUE TITLE
Change all Object types to object in index.d.ts

### ISSUE THREAD

**Issue by BjornMelgaard** [char0n/ramda-adjunct#137]
because `type Object only allow you to assign any value to them` ([from](https://www.typescriptlang.org/docs/handbook/basic-types.html))

https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type#object-vs-object-vs

**Comment by char0n** [comment]
Seems like we have more problems like that in the typings. Sometimes the types are capitalized, sometimes not.

`Number` vs `number`
`String` vs `string`

**Comment by BjornMelgaard** [comment]
It better to change them all to primitives

**Comment by BjornMelgaard** [comment]
I'll do this after mergePaths

**Comment by char0n** [comment]
Nice job. We'll go for the release this evening.
