### ISSUE TITLE
Debounce / Throttle

### ISSUE THREAD

**Issue by damiangreen** [char0n/ramda-adjunct#1392]
**Is your feature request related to a problem? Please describe.**
See https://github.com/ramda/ramda/issues/1041

**Describe the solution you'd like**
An implementation of `debounce` so we don't need to use `lodash`

**Describe alternatives you've considered**
`lodash`

**Comment by char0n** [comment]
I tend to share the same opinion as expressed by many people in the [issue](https://github.com/ramda/ramda/issues/1041) you mentioned. R and RA are side-effect free libraries. Debounce adn Trottle are by definition not side-effect free functions and are not referential transparent. 

R and RA are designed as libraries for data transformations. I don't think these functions belong to those libraries. People can easily install Debounce by `npm i debounce` which is battle tested implementation. 

What is your opinion on this? Do you have some arguments for incorporating those functions into RA, except the argument against using lodash?

**Comment by damiangreen** [comment]
I was aiming to eliminate lodash entirely from our codebase, and there are only a handleful of functions we turn to turn to lodash for. The other functions we use in lodash are string handling ones, which I have just discovered today https://ramda-extension.firebaseapp.com/docs/ has. 

Personally I'd rather import one package and lose strict purity than require multiple. But I guess there are arguments to be had both ways.

**Comment by char0n** [comment]
I understand the argument. I have the same goal. Having a standard library for almost everything. But still installing `npm i debounce` pose no problem. No need to install big lodash. 

Regarding `ramda-extension` be very carefull when using this library. We have an initial research about string manipulation functions - https://github.com/char0n/ramda-adjunct/issues/391. Precursor for this is to implement `deburr` function which is very complex to do. `ramda-extension` doesn't care about proper `deburr` algorithm so you may be surprised by the result that `toKebabCase` will give you.

> Personally I'd rather import one package and lose strict purity than require multiple. But I guess there are arguments to be had both ways.

Understand, but then the spirit of the library will dissolve and it will just become a set of unrelated functions that do stuff.

**Comment by char0n** [comment]
Closing this issue, there's been no followup discission.
