### ISSUE TITLE
[Regression] Changes to isIterable breaks type safety

### ISSUE THREAD

**Issue by kawazoe** [char0n/ramda-adjunct#1412]
**Describe the bug**
[This change](https://github.com/char0n/ramda-adjunct/commit/e7b35e58ba597ef2ff98fa022fadd467b2c5ab09#diff-88bec6beae84369c0376b56b3bb88fe1L52) causes compilation errors

**To Reproduce**
```
export function foo<T>(value: T | Iterable<T>): T {
  if (isIterable(value)) {
    return value[Symbol.iterator]().next()?.value;
  }

  return value;
}
```

**Expected behavior**
Should compile.

**Actual behavior**
Fails to compile since isIterable is not a type guard function. Replacing `Iterable<T>` with `T[]` and `isIterable(value)` with `isArray(value)` would make this sample compile, though would defeat the purpose of using `isIterable`.

**Comment by char0n** [comment]
I can return the typing to original form. At this point I don't remember why I made the change. Possibly it was due to some linting issue that `dstlint` was reporting and maybe Typescript version support.

**Comment by char0n** [comment]
If you'll provide a PR and all the tests will pass, I'll accept the PR.
