### ISSUE TITLE
mergeProps & mergePaths

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#142]
Optimize composition. Both functions can be composed in more functional and point-free manner

```javascript
const mergeProps = curry((ps, obj) => mergeAll(props(ps, obj)));
```
becomes
```javascript
const mergeProps = curryN(2, pipe(props, mergeAll));
```

Note: @BjornMelgaard

**Comment by BjornMelgaard** [comment]
ok, noted, will make later

**Comment by char0n** [comment]
Closed by https://github.com/char0n/ramda-adjunct/pull/143
