### ISSUE TITLE
incorrect ponyfill for replaceAll()

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [char0n/ramda-adjunct#1573]
Hi! I was experimenting with `replaceAll()` from ramda adjunct version `2.27.0` and found the internal ponyfill has some inconsistencies with the native browser version.

Here is the code I tried in both browser and runkit:

```javascript
// browser version:
'foo.bar'.replaceAll('.', '$$$$$') // prints 'foo$$$bar' in Chrome 85, Windows 7

// runkit version:
RA.replaceAll('.', '$$$$$', 'foo.bar') // prints 'foo$$$$$bar'
```

( runkit code can be seen here: https://runkit.com/embed/xb4qhttrwooh )

It turns out, that the new implementation of `String.prototype.replace()` has a few special character patterns, that are handled differently as one would expect -- for example `$$` is turned into `$` -- and `String.prototype.replaceAll()` inherits this behavior.

https://tc39.es/ecma262/#table-replacement-text-symbol-substitutions

Please update https://github.com/char0n/ramda-adjunct/blob/master/src/internal/ponyfills/String.replaceAll.js to include these special patterns, or have a standalone implementation of replaceAll without using `String.prototype.replaceAll()`, even if it's accessible.

Thanks in advance!

**Comment by js636f** [comment]
Hi! 

Thank you for the detailed issue description. 

I'm working on it.

**Comment by char0n** [comment]
Hi Guys, 

I'm inclined to use `R.replace` as base for implementation for `replaceAll` ponyfill. The logic for special cases is complicated and it just seems unnecessary to re-implement it. 

I'm suggesting following algorithm:

```js
var find = 'abc';
var replace = 'a';
var re = new RegExp(RA.isRegExp(find) ? find : RA.escapeRegExp(find) , 'g');

R.replace(re, replace, 'abc.abc.abc');
```

If the search pattern is string we escape it and create a global regex pattern from it. If it's already regex we just convert it to global regex.

@js636f what do say ? With this solution we avoid complexities of implementing the logic.

**Comment by js636f** [comment]
@char0n this sounds reasonable, I think we should go this way

**Comment by char0n** [comment]
Fix is on master.

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!
