### ISSUE TITLE
Broken link in documentation for lensTraverse

### ISSUE THREAD

**Issue by terrenmoe** [char0n/ramda-adjunct#1592]
https://github.com/char0n/ramda-adjunct/blob/5284707c350c41b90227d39968612d1d54a006e4/src/lensTraverse.js#L11
The sequence link should be https://ramdajs.com/docs/#sequence

**Comment by char0n** [comment]
@terrenmoe thanks for reporting this!

**Comment by DanielAguirre** [comment]
Hi @char0n, I would like to help with this if is til available

**Comment by char0n** [comment]
Sure, go ahead!
