### ISSUE TITLE
RA.Identity monad not showing in docs

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1614]
**Describe the bug**

RA.Identity monad is not showing in our documentation

![image](https://user-images.githubusercontent.com/193286/94905262-e0ed7600-049c-11eb-939b-cc2793b83aa5.png)

**To Reproduce**
1. Go to https://char0n.github.io/ramda-adjunct/2.28.0/
2. See there is not R.Identity

**Expected behavior**
RA.Identity should show in documentation. For example version this version of documentation (2.10.0) is still showing it: https://char0n.github.io/ramda-adjunct/2.10.0/

![image](https://user-images.githubusercontent.com/193286/94905387-12fed800-049d-11eb-964c-804fa49c2297.png)

**Additional context**
We use [jsdoc](https://www.npmjs.com/package/jsdoc). We've updated jsdoc to v3.6.6 and maybe that is part of the problem. Needs to be investigated further.

**Comment by tsgoswami** [comment]
Hii, I would like to give a try and work on this issue.

**Comment by wanjuntham** [comment]
May I try this?

**Comment by char0n** [comment]
@wanjuntham sure, go ahead!
