### ISSUE TITLE
spread

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#166]
Ramda cookbook reference: https://github.com/ramda/ramda/wiki/Cookbook#spread

**Comment by char0n** [comment]
@BjornMelgaard final addition to our merging algorithms. Are you interested ? 

PS: I am currently working on isomorphic lenses [here](https://github.com/char0n/ramda-adjunct/pull/165). Will appreciate code review after it's fully implemented.

**Comment by BjornMelgaard** [comment]
@char0n yeah, would like to help, I'll make it in 7 days

**Comment by BjornMelgaard** [comment]
@char0n so...what about change spread to flattenProp and flattenPath?? (lol)

example

```
const flattenProp = R.converge(R.merge, [R.dissoc, R.propOr({})]);
// usage:
// flattenProp("b", { a: 1, b: { c: 3, d: 4 } }); // -> { a: 1, c: 3, d: 4 }


const flattenPath = ...
// usage:
// flattenPath(["b1", "b2"] { a: 1, b1: { b2: { c: 3, d: 4 } } }); // -> { a: 1, c: 3, d: 4 }
```

**Comment by char0n** [comment]
@BjornMelgaard will think about it. Will have to research is `flatten` is a proper name of the mechanism and `spread` is only an implementation detail or vice versa.

**Comment by BjornMelgaard** [comment]
@char0n https://github.com/acdlite/recompose/blob/master/docs/API.md#flattenprop

so flatten from recompose is not the same of spread here: flatten leaves original object, while spread - not
I would say that recompose behavior is more useful

**Comment by char0n** [comment]
As I understand it, we have two distinctive behaviors. `spreadPath` and `flattenPath` (`spreadProp` and `flattenProp` can be derived later from `*Path` functions). They both do different things which seems equivalently practical. 

When we have both (and already having the set you implemented earlies), I guest we can completely minic ES6 spread operator in functional way.

**Comment by BjornMelgaard** [comment]
then.... I'll made `spreadPath` and `flattenPath` (and others) on weekends, awesome

**Comment by char0n** [comment]
Pls send 2 independent PR when doing this.

**Comment by BjornMelgaard** [comment]
noted

**Comment by char0n** [comment]
Task for me: reflect the tests from `spreadProp` into `spreadPath`

**Comment by char0n** [comment]
I was thinking we can now compose `spreadProp` and `spreadPath` directly from `flattenProp` and `flattenPath` ? What do you think ?

**Comment by char0n** [comment]
I'll do the rest of the work here

- [ ] document on ramda cookbook
- [ ] use `flatten*` as a base for composition of `spread*` functions

**Comment by BjornMelgaard** [comment]
this wouldn't work
```ts
const spreadPath = curry((path, obj) => {
  const merged = flattenPath(path, obj);
  const without = dissocPath(path, merged);
  return without;
});
```

sorry, have to go to work)

**Comment by char0n** [comment]
@BjornMelgaard yeah it will not work. Concepts are different even though they seem similar.

**Comment by BjornMelgaard** [comment]
@char0n why bother then?

**Comment by char0n** [comment]
@BjornMelgaard I won't. I'll just document spread* utils on ramda cookbook and close this issue.

**Comment by char0n** [comment]
`spreadPath` & `spreadProp` documented on [ramda cookbook](https://github.com/ramda/ramda/wiki/Cookbook#spreadpath). `flattenPath` & `flattenProp` to be done.

**Comment by char0n** [comment]
flattenPath & flattenProp also documented on cookbook.
