### ISSUE TITLE
Alternation (OR-combinator)

### ISSUE THREAD

**Issue by rockymadden** [char0n/ramda-adjunct#172]
> The alt combinator allows you to perform simple conditional logic when providing default behavior in response to a function call. This combinator takes two functions and returns the result of the first one if the value is defined (not false, null, or undefined); otherwise, it returns the result of the second function.

```javascript
const alt = R.curry((func1, func2, val) => func1(val) || func2(val));
```

From page 113 of [Functional Programming in JavaScript](https://www.goodreads.com/book/show/27876180-functional-programming-in-javascript)

**Comment by char0n** [comment]
`alt` combinator is already implemented in ramda as [either](http://ramdajs.com/docs/#either). In ramda we have `or` util. If you [lift](https://www.linkedin.com/pulse/lifting-functions-monadic-context-javascript-vladim%C3%ADr-gorej) it into monadic context you will get `alt` combinator, in ramda's case `either`.

```javascript
const either = lift(or);
```

**Comment by char0n** [comment]
What we can do in the future is to implement `dispatch` combinator that acts like extension to the alt combinator. It goes forward execting functions until first returns truthy value. But that is part of #66

**Comment by char0n** [comment]
@rockymadden can you close this. Do `R.either` satisfies your needs ?

**Comment by rockymadden** [comment]
Yep, thanks for the analysis.
