### ISSUE TITLE
Sequencing combinator (not S-combinator)

### ISSUE THREAD

**Issue by rockymadden** [char0n/ramda-adjunct#173]
> The seq combinator is used to loop over a sequence of functions. It takes two or more functions as parameters and returns a new function, which runs all of them in sequence against the same value. This is the implementation:

```javascript
const seq = function(/*funcs*/) {
    const funcs = Array.prototype.slice.call(arguments);
    return function (val) {
       funcs.forEach(function (fn) {
          fn(val);
       });
    };
};
```

> With it, you can perform a sequence of related, yet independent, operations. For instance, after finding the student object, you can use seq to both render it on the HTML page and log it to the console. All functions will run in that order against the same student object:

```javascript
const showStudent = R.compose(
  seq(
    append('#student-info'),
    consoleLog),
  csv,
  findStudent));
```

> The seq combinator doesn’t return a value; it just performs a set of actions one after the other. If you want to inject it into the middle of a composition, you can use R.tap to bridge the function with the rest.

From page 114 of [Functional Programming in JavaScript](https://www.goodreads.com/book/show/27876180-functional-programming-in-javascript)

**Comment by char0n** [comment]
Ramda gives us limited S-combinator via [ap](http://ramdajs.com/docs/#ap). Do you really think that S-combinator is practical to have in the library ? I can achieve the same effect using `tap`.

```javascript
const showStudent = R.compose(
  tap(append('#student-info')),
  tap(consoleLog),
  csv,
  findStudent));
```

But I guess the selling point for it is its declarativness. It logically groups related operation into one sequence. You know what ? Let's go for it, just for having a reference implementation of S-combinator as a part of ramda-adjunct. But pls don't use Luis Atencio's implementation. Use utils that are already part of ramda or ramda-adjunct to compose the s-combinator.

**Comment by rockymadden** [comment]
Yep, it's a complete convenience because, as you stated, it is possible to accomplish already.

**Comment by char0n** [comment]
@rockymadden wanna go for this one in v2.1.0 release ? ;]

**Comment by rockymadden** [comment]
I've been on back-to-back on call rotations and then slammed. I am interested in implementing this and other combinators for sure. I think the author is wrong, this is not the S-combinator as it is defined in combinatory logic. Sanctuary [used to have it](https://github.com/sanctuary-js/sanctuary/tree/v0.11.1#s--a-b-c---a-b---a---c). I need to dig in more why it was removed (renamed?). The S-combinator being something along the lines of:
```javascript
R.converge(f, [g, R.identity])
```

**Comment by char0n** [comment]
More info here: https://gist.github.com/buzzdecafe/6261503

**Comment by rockymadden** [comment]
His opinion is there for sure 😆. I think you could argue the same for many functions that refine behavior of more generic functions. I at least use the S combinator semi-regularly, I only didn't realize I was using it until a while back. Why is it named that? Because in combinatory logic it is called that. The name _is_ weird, but you could also say the same of fantasy land laws and other things are weird. Not super approachable, I get. I like how the `I` combinator is approachably called `identity` in Ramda, so I appreciate there is another path.

**Comment by char0n** [comment]
Ok as far as I understand, Luis Atencios explanation is incorrect ? It seems like that this is the case. S-combinator works a bit different than Luis implemented it. Or in different words: he implements only subset of what S-combinator should be ? Anyway I would like to invite Luis to participate in this debate so that we get it right.

**Comment by rockymadden** [comment]
Yep, `ap` is the S-combinator I am speaking of and got renamed to in Sanctuary to `ap` as well (https://github.com/sanctuary-js/sanctuary/commit/7e54645715afa40380fc6a52aa1c5a81cf7f6ac2).

**Comment by rockymadden** [comment]
I think I found it. It is not the S-combinator as is stated in the heading in the book (which matches the title of this issue). It is the sequencing combinator! http://www.cs.rpi.edu/academics/courses/spring11/proglang/handouts/lambda-calculus-chapter.pdf#10 look for section 2.7.

**Comment by rockymadden** [comment]
A primitive implementation being:
```javascript
const seq = curry((x, y, a) => useWith(always(undefined), [x, y])(a, a));
```

**Comment by rockymadden** [comment]
A primitive implementation being: 
```javascript
const seq = curry((x, y) => converge(always(undefined), [x, y]));
```

**Comment by char0n** [comment]
Ok nice research. So there are two combinators, S-combinator and Sequencing combinator. I see them as two completely different things. Let's implement the sequencing combinator here and heal with the rest in #250
