### ISSUE TITLE
clamp

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#1732]
**Is your feature request related to a problem? Please describe.**

Clamps number within the inclusive lower and upper bounds.

**Describe the solution you'd like**

```js
RA.clamp(-5, 5, -10); //=> -5
```

**Additional context**
https://lodash.com/docs/4.17.15#clamp

**Comment by PrathameshAshra** [comment]
First Timer here, trying to do this, please help me where stuck

**Comment by char0n** [comment]
@PrathameshAshra, PR of this should come containing 5 files. Here is [PR](https://github.com/char0n/ramda-adjunct/pull/1067/files) that you can use as model template to build your own PR for clamp function.

**Comment by PrathameshAshra** [comment]
Thanks for the reply, i would do this and keep you in loop.

**Comment by char0n** [comment]
Already part of ramda: https://ramdajs.com/docs/#clamp
