### ISSUE TITLE
pickAllIndexes

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#189]
Just like `pickindexes` but will not omit non existing indexes.

**Comment by GingerPlusPlus** [comment]
http://ramdajs.com/docs/#props does exactly this.

**Comment by char0n** [comment]
Cool, then we add documentation to `pickIndexes` that `R.props` is doing `pickAllIndexes` and that's done.

**Comment by char0n** [comment]
FYI we also have [RA.paths](https://char0n.github.io/ramda-adjunct/2.5.0/RA.html#.paths)
