### ISSUE TITLE
Contributor 

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#205]
@BjornMelgaard I would like to thank you  for all work you did so far. You helped a lot pushing the ramda-adjunct forward. I think you can be even greater value to this project by becoming an official contributor. Would you like to become a contributor ?

What it changes:
You will have access to the master directly but I'd prefer if we discuss thinks first in issues and the code was produced in PR. I will also try to produce my commits more as a PR and I'll expect you to be reviewing them. As popularity of this lib steadily grows it's better to be team of two, rather than team of one ;]

What do you think ?

**Comment by BjornMelgaard** [comment]
@char0n Thanks for proposal, I'm accepting it, would like to help in spare time :smiley:

**Comment by char0n** [comment]
Done welcome to the ramda-adjunct team. Still small, but let's hope it will grow ;]

**Comment by BjornMelgaard** [comment]
Accepted :raised_hands:
