### ISSUE TITLE
isError

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#206]
**Is your feature request related to a problem? Please describe.**

Should detect JavaScript errors.

**Describe the solution you'd like**

```js
const isError = R.pipe(R.type, R.identical("Error"));

isError(new Error()); //=> true
```

**Describe alternatives you've considered**

--

**Additional context**
We need to test on all [major error classes](https://airbrake.io/blog/nodejs-error-handling/nodejs-error-class-hierarchy)

**Comment by GingerPlusPlus** [comment]
`R.is(Error)`.

What are "error-like" objects?

**Comment by char0n** [comment]
Error like object is an object that conforms to the following: 

```js
(typeof errorLike.message == 'string' && typeof errorLike.name == 'string' && !isPlainObject(errorLike));
```

It's been decided [here](https://github.com/char0n/ramda-adjunct/pull/346) that we're not going to deal with the `another realm` problem and we're going to conform to `R` on this and use `R.is` to check for type for various types.
