### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by sacrosanctic** [char0n/ramda-adjunct#2079]
**Describe the bug**
There is a typo for isNotNilOrEmpty

**To Reproduce**
https://char0n.github.io/ramda-adjunct/2.35.0/RA.html#.isNilOrEmpty
https://char0n.github.io/ramda-adjunct/2.35.0/RA.html#.isNotNilOrEmpty

**Expected behavior**
isNotNilOrEmpty should say return false

**Screenshots**
![image](https://user-images.githubusercontent.com/2974920/140258938-8153b8ee-59b9-4209-84a2-6b293c8536e1.png)
![image](https://user-images.githubusercontent.com/2974920/140259081-68d3891b-d304-4598-aa27-a1f3ce9dd38c.png)

**Comment by char0n** [comment]
@sacrosanctic thanks for catching this, would you fancy opening a fixing PR?

**Comment by sacrosanctic** [comment]
i dont know how

**Comment by char0n** [comment]
@sacrosanctic no worries. Fixed in https://github.com/char0n/ramda-adjunct/commit/04ef06ec9cf9e69f980d558ea30455f881369bca. And thanks again!
