### ISSUE TITLE
Code coverage should exclude tests

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#215]
codecov.io

**Comment by char0n** [comment]
@BjornMelgaard I've created milestone [v2.1.0](https://github.com/char0n/ramda-adjunct/milestone/4). Would you be able to implement `stub*` utils ? I'll deal with the infra and #35.

**Comment by BjornMelgaard** [comment]
@char0n yes, I'll do this on weekends

**Comment by char0n** [comment]
test dir still present

**Comment by char0n** [comment]
Resolved by e72aa56

**Comment by char0n** [comment]
@BjornMelgaard everything ready for v2.1.0. Milestone is completed. You wanna add something or can I go for a release today/yesterday ?

**Comment by BjornMelgaard** [comment]
@char0n can release, please)
