### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zhulduz** [char0n/ramda-adjunct#2154]
**Describe the bug**
Hi guys, after updating ramda to 0.28.0,  get next error `Cannot read property 'length' of undefined`.
Use ramda-adjunct 2.35.0

***Error log*
```
at flip (*/node_modules/ramda/src/flip.js:33:20)
at f1 (*/node_modules/ramda/src/internal/_curry1.js:19:17)
at Object.<anonymous> (*/node_modules/ramda-adjunct/lib/contained.js:33:33)
```

**Comment by zhulduz** [comment]
maybe we should wait https://github.com/char0n/ramda-adjunct/issues/2152?

**Comment by char0n** [comment]
@zhulduz I'll try to add support for latest ramda releases during last few days.

**Comment by char0n** [comment]
Fixed in https://github.com/char0n/ramda-adjunct/releases/tag/v3.0.0
