### ISSUE TITLE
defaultWhen

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#216]
```javascript
// defaultToBy :: (a -> Boolean) -> b -> a -> a | b
const defaultToBy = curry((predicate, defaultVal, val) => (predicate(val) ? val : defaultVal));
```

**Comment by char0n** [comment]
@rockymadden, @BjornMelgaard what do you think about the name of this util ? Isn't it too much confusing ?

**Comment by BjornMelgaard** [comment]
defaultBy seems better

**Comment by char0n** [comment]
there is also possibility for `defaultWhen` or `defaultToWhen`. We need to choose the best one from them.

 - defaultToBy
 - defaultBy
 - defaultWhen
 - defaultToWhen

**Comment by BjornMelgaard** [comment]
defaultWhen

**Comment by char0n** [comment]
Yeah that is my preferred also.

**Comment by char0n** [comment]
@BjornMelgaard v2.1.0 just released.

**Comment by BjornMelgaard** [comment]
@char0n awesome
