### ISSUE TITLE
Cannot re-export all of ramda-adjunct in TypeScript

### ISSUE THREAD

**Issue by novascreen** [char0n/ramda-adjunct#2306]
**Describe the bug**
In our monorepo I would like to re-export all of `ramda-adjunct` from one file. Unfortunately the types don't seem to align with the way the JavaScript files actually export the individual functions.

**To Reproduce**
1. In a TypeScript file
	```ts
	  export * from 'ramda-adjunct'
	  ```
1. See this error
	  ```
	  error TS2498: Module '".../node_modules/ramda-adjunct/types/index"' uses 'export =' and cannot be used with 'export *'
	  ```

**Expected behavior**
The types align with the fact that all functions are exported as named exports and not as a single object and allow me to re-export all named exports using `export * from`

**Additional context**
- TypeScript: v4.7.3

**Comment by novascreen** [comment]
Hi @char0n 
I don't have too experience writing external type definitions, but I'm willing to give it a try and report back.

**Comment by char0n** [comment]
@novascreen your changes are now released in https://github.com/char0n/ramda-adjunct/releases/tag/v3.3.0. Thanks again for contributing.
