### ISSUE TITLE
Negated Logic

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#234]
Would you be open to a PR for the following negations of Ramda's logical functions:

```
export const nand = complement(and);
export const nor = complement(or);
export const notBoth = compose(complement, both);
export const neither = compose(complement, either);
export const notAllPass = compose(complement, allPass);
export const nonePass = compose(complement, anyPass);
```

I've found them to make my code a little more readable.

Let's deal with complements one at a time. 

- [ ] [nand](https://github.com/char0n/ramda-adjunct/issues/237)

**Comment by char0n** [comment]
Let me think about them and will let you know today evening/tommorow. But most of them looks legitimate.

**Comment by Undistraction** [comment]
Great. I find that with logic, this kind of extra clarity really helps me avoid brain melt. It's never good having to flip booleans in your mind to understand something. As far as naming goes, `nand` and `nor` are standard for [logic gates](https://en.wikipedia.org/wiki/Logic_gate), and the others feel like the most obvious names possible. Possibly `neither` could be `notEither` but I don't see much advantage to that.

**Comment by Undistraction** [comment]
Thinking about this a little further, Ramda also currently offers `all`, `any`, `none`, but doesn't offer  `notAll`, so that would probably be worth adding as well:

```
const notAll = complement(all);
```

**Comment by char0n** [comment]
Let's deal with complements one at a time. 

- [ ] [nand](https://github.com/char0n/ramda-adjunct/issues/237)

**Comment by char0n** [comment]
Meanwhile lets break down the naming

LGTM:
```javascript
export const nand = complement(and);
export const nor = complement(or);
```

These needs some additional thinking. I am not sure about these. IMHO they can make code harder to read and reason about. 

```javascript
export const notBoth = compose(complement, both);
export const notAllPass = compose(complement, allPass);
export const neither = compose(complement, either);
export const nonePass = compose(complement, anyPass);
```

For me personally it is easier to read something like this
```javascript
both(isNotUndefined, isNotNull)
```
instead of
```javascript
notBoth(isUndefined, isNull)
```

We should strive for simplicity, but these functions can really IMHO make code harder to read. Our aim should to create complements for `Type` functions which are inputs for these HOC `Logic` functions and not to complement the `Logic` functions them selves.

**Comment by Undistraction** [comment]
> For me personally it is easier to read something like this
> both(isNotUndefined, isNotNull)

This is exactly why I think this is confusing - you have actually created a `neither`, not a `notBoth`. Your function will only return true if both predicates return true , i.e. if the value is both not undefined and not null. However, `notBoth` should return true if either predicate returns false. 

```
const t = () => true;
const f = () => false;

both(t, t)() // true
both(t, f)() // false
both(f, t)() // false
both(f, f)() // false

const notBoth = compose(complement, both);

notBoth(t, t)() // false
notBoth(t, f)() // true
notBoth(f, t)() // true
notBoth(f, f)() // true
```

[REPL](http://ramdajs.com/repl/#?const%20t%20%3D%20%28%29%20%3D%3E%20true%3B%0Aconst%20f%20%3D%20%28%29%20%3D%3E%20false%3B%0A%0Aboth%28t%2C%20t%29%28%29%20%2F%2F%20true%0Aboth%28t%2C%20f%29%28%29%20%2F%2F%20false%0Aboth%28f%2C%20t%29%28%29%20%2F%2F%20false%0Aboth%28f%2C%20f%29%28%29%20%2F%2F%20false%0A%0Aconst%20notBoth%20%3D%20compose%28complement%2C%20both%29%3B%0A%0AnotBoth%28t%2C%20t%29%28%29%20%2F%2F%20false%0AnotBoth%28t%2C%20f%29%28%29%20%2F%2F%20true%0AnotBoth%28f%2C%20t%29%28%29%20%2F%2F%20true%0AnotBoth%28f%2C%20f%29%28%29%20%2F%2F%20true)

This is exactly why I would favour explicit functions for these things - because they are naturally confusing. I agree that using complements does help make things easier to read, but this is something tangential to that.

**Comment by char0n** [comment]
Your reasoning seems to be correct. We need something explicit, but also something understandable only by looking at it.

I would  rename `notAllPass` to `anyNotPass`. IMHO it is simpler to reason about anything that is not passing rather than negation of all passing.

```javascript
export const anyNotPass = compose(complement, allPass);
export const neither = compose(complement, either);
export const nonePass = compose(complement, anyPass);
```

I am still struggling with `both` vs `notBoth`. Can't we come up with something more descriptive ?

**Comment by Undistraction** [comment]
To be honest, I definitely favour keeping the naming as close to the complemented value as possible for consistency. `neither` makes sense as it is a common contraction of `not either`, but I think `notAllPass`, although not the most beautiful of names, at least fulfils:

1. Is clearly the opposite of  `allPass`.
2. It's function is obvious.

In trying to think of a better name, I keep coming back to `notAllPass`. In a different context:

> The exam was very hard. Not all passed. 
> There was a terrible car crash. Not all survived. 

The same is true of `notBoth`.

> Can we get the dog and the cat? Not both of them.

**Comment by char0n** [comment]
Ok makes sense. `notAllPass` is definitely better then `anyNotPass`.

Fine I was too not able to come up with anything better. Let go for `notAllPass`, `neither`, `nonePass` and `notBoth`. Create separate PR for each of them. Pls don't do them on in one big PR.

**Comment by Undistraction** [comment]
I'll jump on these next.

**Comment by char0n** [comment]
Ok. I'll release 2.2.0 and let's put those to 2.3.0.

**Comment by Undistraction** [comment]
Sounds good.

**Comment by char0n** [comment]
@Undistraction will you be able to squeeze something in for [v2.3.0](https://github.com/char0n/ramda-adjunct/milestone/6) release ?

**Comment by Undistraction** [comment]
Sure. I can definitely get `neither` done in time. Might be able to do `notAllPass` and `nonePass` as well, but got a lot on for the next 10 days.

**Comment by char0n** [comment]
@Undistraction assigning this to new milestone [v2.4.0](https://github.com/char0n/ramda-adjunct/milestone/7).

**Comment by Undistraction** [comment]
OK. I'll get `notAllPass` and `nonePass` done for then.

I'm also definitely liking the idea of adding the missing Boolean operators. Ramda currently supplies:

- `and`
- `or`
- `not`

I think it's worth adding:

- `nand`,
- `nor`
- `xor`
- `xnor`

These are basic units of logic and I think they have a place here.

**Comment by char0n** [comment]
Yeah why not go for it.

**Comment by Undistraction** [comment]
Closing as we already have separate issues in place for remaining functions.
