### ISSUE TITLE
Valid Number

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#235]
Would you accept a PR for a [Sanctary-style](https://github.com/sanctuary-js/sanctuary-def#ValidNumber) `isValidNumber()`?

Effectively:

```
const isValidNumber = both(isNumber, complement(isNaN));
```

**Comment by char0n** [comment]
We would, but need to understand first the usecases.

I can imagive having `isValidNumber` in the following form

```javascript
const isValidNumber = R.either(RA.isFloat, RA.isInteger);
```
In ramda-adjunct we already have `isFloat` and `isInteger`. I would expect `ValidNumber` to be something that is not NaN and also not an Infinite number (+/-Infinity)

**Comment by Undistraction** [comment]
>  I would expect ValidNumber to be something that is not NaN and also not an Infinite number (+/-Infinity)

That's a fair point.  I agree.

**Comment by char0n** [comment]
@Undistraction go for a PR then.

@BjornMelgaard opinion ?

**Comment by BjornMelgaard** [comment]
no

**Comment by Undistraction** [comment]
> no

So is that a no to a PR?

**Comment by BjornMelgaard** [comment]
@Undistraction sorry, I meant I have no comments)
Please do it)

**Comment by Undistraction** [comment]
@BjornMelgaard OK. Thanks. I'll go ahead.

**Comment by char0n** [comment]
@Undistraction, @BjornMelgaard going for 2.2.0 release after the CI finishes the build for the last commit of this repo. I would specially like to thank @Undistraction for his contributions for this release.

**Comment by Undistraction** [comment]
@charOn Thanks. Was a pleasure. You run a pleasingly tight ship!

**Comment by char0n** [comment]
@Undistraction thanks good to hear that ;] After you finish #234 and you'll still interesting in contributing further you can become commiter/contributor of this project.

**Comment by Undistraction** [comment]
Thanks. That would be grand.

**Comment by char0n** [comment]
v2.2.0 out: https://www.npmjs.com/package/ramda-adjunct
