### ISSUE TITLE
nand

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#237]
```javascript
export const nand = complement(and);

**Comment by char0n** [comment]
@Undistraction

`and` in ramda is defined with Hindley-Milner signature `a → b → a | b`
This means that `and` can process any types, not just Booleans and can return any types.

Example of what I mean
```javascript
R.and(1, 2); // => 2
R.and("test", "test1"); // => "test1"
```
Keeping this in mind, if we implement `nand` as complement of `and` it will always return Boolean.
The signature be then  `a → b → Boolean`

Are we okay with that ? Does any usecase for this exist ?

@BjornMelgaard any opinion on this ?

**Comment by BjornMelgaard** [comment]
@char0n 
What we should return otherwise? first parameter? there is `or` for this
I think its fine to return boolean and be closer to ramda as possible

**Comment by char0n** [comment]
@BjornMelgaard the question was rather, do we need something like this in the lib ? ... rather then what it should return. It can return Boolean, and Boolean only,

**Comment by BjornMelgaard** [comment]
@char0n is someone wants to, I've never used complement for and, I would rather add complement of path and prop

**Comment by rockymadden** [comment]
Tagging on to this discussion: I am curious if there might be interest in adding more logical operations/logic gates/truth functions (e.g. AND, OR, XOR, NOT, NAND, NOR and XNOR) that might also align/dispatch with scalar/not-scalar types alike. I know ramada already has many of them (i.e. the relation functions). More of a placeholder comment for me for now.

**Comment by Undistraction** [comment]
Complement of Ramda's `and`.

- T T = F
- T F = T
- F T = T
- F F = T

See: #234

**Comment by dawehner** [comment]
This is implemented in https://github.com/char0n/ramda-adjunct/pull/952
