### ISSUE TITLE
propNotEq

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#238]
@BjornMelgaard feel free to do this and https://github.com/char0n/ramda-adjunct/issues/217 if you wish to.

**Comment by char0n** [comment]
Will you be able to do this one of should I move it to the next release ?

**Comment by BjornMelgaard** [comment]
next release

**Comment by char0n** [comment]
@BjornMelgaard  will you be able to squeeze this in for [v2.3.0](https://github.com/char0n/ramda-adjunct/milestone/6) release ?

**Comment by BjornMelgaard** [comment]
till Friday - no, but can try on this weekends

**Comment by char0n** [comment]
Ok moved the milestone to 14.1. Good luck ! ;]

**Comment by char0n** [comment]
I've finalize the feature here: https://github.com/char0n/ramda-adjunct/commit/fab2066ee74286d5bf2d6e4faf5ddd413ca5ff5c
