### ISSUE TITLE
Package.json browser field causing errors in Webpack 1

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#242]
I've just added `ramda-adjunct` to a project compiled with Webpack 1, which resulted in errors in the compiled js. It seems that instead of `lib/index.js`, Webpack is using `es/index.js`, which is untranspiled, meaning es6 exports end up being compiled into the `commons.js` file created by Webpack.

The only working solution I've found is to remove the `browser` field from your `package.json` which means Webpack uses the transpiled js referenced by the `main` field.

I appreciate Webpack v1 is old, but it is used by [Gatsby.js](https://github.com/gatsbyjs/gatsby) which is a very popular lib, and is where I encountered this issue. I don't believe Webpack v1 supports es6 in packages.

**Comment by char0n** [comment]
Unfortunately it's there by design. As newer versions of webpack can read ES6 imports and do the tree-shaking on top of it. I guess the problem is solvable by using [resolve.alias](https://webpack.js.org/configuration/resolve/#resolve-alias) which is available even in webpack 1 (if my memory server me well).

Let me know if it helped somehow.

**Comment by Undistraction** [comment]
Thanks. Yes I figured it was deliberate. Unfortunately I don't have access to Gatsby's Webpack config (well not without a lot of hassle). Thought it was worth posting here in case someone else has trouble - it's not an obvious thing to track down if you aren't expecting it.

**Comment by char0n** [comment]
We can still make some research and find out what would removing the browser field mean. I am open to removing it if  it doesn't break a lot of things.

**Comment by Undistraction** [comment]
[The spec](https://github.com/defunctzombie/package-browser-field-spec) states: 

> The browser field is where the module author can hint to the bundler which elements (other modules or source files) need to be replaced when packaging.

If the code referenced by `browser` is identical to the code referenced by `lib` then I don't really see the point of using the field at all, but the immediate problem is that it is pointing to ES6 code. If it was pointing to transpiled code there wouldn't be a problem but it is making the assumption that anything that uses the `browser` field will be capable of using/transpiling ES6. There is nothing in the spec regarding whether the code referenced should use `require` or not.

**Comment by char0n** [comment]
@Undistraction actually code in `es/` is stranspiled by babel to ES5. The only thing that is not transpiled is ES6 imports because of the support of tree shaking. If we verify that rollout, webpack 2 and webpack 3 can also read `jsnext:main` or `module` I am up for removing the `browser` field to open support for webpack 1. Do you have time to verify those bundlers ? If yes, issue a PR for removing the browser field.

**Comment by Undistraction** [comment]
Webpack 2 will fall back to `module` (From the [docs](https://webpack.js.org/configuration/resolve/#resolve-mainfields)): 

When the target property is set to webworker, web, or left unspecified:
```
mainFields: ["browser", "module", "main"]
```
For any other target (including node):
```
mainFields: ["module", "main"]
```

Rollup is opt-in for the `browser` field using [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve).

> // some package.json files have a `browser` field which
> // specifies alternative files to load for people bundling
> // for the browser. If that's you, use this option, otherwise
>  // pkg.browser will be ignored
> browser: true,  // Default: false

**Comment by char0n** [comment]
So if i understand it correctly we should not break almost anything by
removing browser field and it will open possibility for webpack 1. Is that
correct ?

**Comment by Undistraction** [comment]
As far as I understand it, yes. Both Webpack 2 and Rollup both use the `module` field.

I think the browser field is still little-used and in no way official, and is superfluous unless it is used to supply code that is different from the code supplied via `module`. In this case you are not supplying anything different - both `module` and `browser` both point to `es/index.js`, so it isn't needed.

**Comment by char0n** [comment]
OK fair enough. Issue a PR. We'll get rid of it.

**Comment by Undistraction** [comment]
Nice. Thanks very much. I'll get that done tomorrow.

**Comment by Undistraction** [comment]
Closed with #cb9b58

Do you have a rough ETA on your next release by any chance?

**Comment by char0n** [comment]
@Undistraction it partly depends on you also: https://github.com/char0n/ramda-adjunct/milestone/5 ;]
