### ISSUE TITLE
Manual Installation Of Babel Plugins For Dev

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#244]
It seems that at present all the plugins in `.babelrc` need to be manually installed - they aren't included in `package.json` so aren't installed with `npm install`,  and running `npm test` triggers 'Unknown plugin' warnings. There are some babel presets in `package.json` but these don't appear to be applied anywhere.

Steps followed:

* fork ramda-adjunct
* clone to machine
* `npm i`
* `npm run test`

**Comment by char0n** [comment]
I've just tried on node node@9.2.0 and npm@5.5.1. Could not reproduce your issue. The way it works now is that devDependencies contains multiple presets that under the hood contains all the plugins mentioned in .babelrc. We have CI running on node 6,7,8,9 and everything is passing. Isn't there something else that works differently on your system ?

**Comment by Undistraction** [comment]
For some reason none of the plugins in the presets' `node_modules` dirs are not being resolved by Babel. They are visible using `npm ls`, but they aren't resolved by babel:

> ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/pedr/respos/ramda-adjunct/.babelrc" at 0, attempted to resolve relative to "/Users/pedr/respos/ramda-adjunct/".

I have the same node and npm versions as you. I'll keep digging.

**Comment by char0n** [comment]
We're not using shrinkwrap, that's the only thing that comes to my mind that could cause some issues.

**Comment by char0n** [comment]
I've added package-lock.json to the repo references in this issue. Try pulling and rerunning npm i and let's see if that worked.

**Comment by Undistraction** [comment]
Lockfile was identical. The only way I can make Babel happy is using the plugins directly:

```
{
  "presets": ["stage-3", "es2015", "es2016"],
  "env": {
    "commonjs": {
      "plugins": [["transform-es2015-modules-commonjs", { "loose": true }]]
    },
    "es": {},
    "coverage": {
      "plugins": [
        ["transform-es2015-modules-commonjs", { "loose": true }],
        "istanbul"
      ]
    }
  }
}
```

Note: I had to install `babel-plugin-transform-es2015-modules-commonjs` as well.

**Comment by char0n** [comment]
I'll try to reproduce on new ubuntu installation with node 9

**Comment by Undistraction** [comment]
Deleted NVM, NPM and removed all my Node installations and started again from scratch and it's building fine. Sorry for the noise. PR on the way.
