### ISSUE TITLE
Combinators

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#250]
Check if we have all the standard combinators in ramda. Find out which one are missing and implement them in ramda-adjunct. Write an article about combinators on linkedin pulse.

@rockymadden you may be interested in this one too...

**Comment by rockymadden** [comment]
@char0n Yep, would love to take part.

**Comment by guillaumearm** [comment]
Here a non-exhaustive list :

### [BCKW combinators](https://en.wikipedia.org/wiki/B,_C,_K,_W_system)
Ramda have the B, C and K from the [BCKW system](https://en.wikipedia.org/wiki/B,_C,_K,_W_system)

- B (composition) : [R.compose](http://ramdajs.com/docs/#compose) ✅ 
- C (flip) : [R.flip](http://ramdajs.com/docs/#flip) ✅ 
- K (known as [Prelude#const](http://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#v:const)) : [R.always](http://ramdajs.com/docs/#always) ✅ 
- W : :x:

```js
// ???
const W = curry((f, x) => f(x, x));
```

### [SKI combinators](https://en.wikipedia.org/wiki/SKI_combinator_calculus)
Ramda have K and I from the [SKI system](https://en.wikipedia.org/wiki/SKI_combinator_calculus)
 
- S (substitution) : :x:
- K (known as [Prelude#const](http://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#v:const)) : [R.always](http://ramdajs.com/docs/#always) ✅ 
- I (identity) :  [R.identity](http://ramdajs.com/docs/#identity) ✅ 

```js
// substitution
const S = curry((f, g, x) => f(x, g(x)));
```

### Other known combinators

- A (application) : [R.call](http://ramdajs.com/docs/#call) (IMHO [R.apply](http://ramdajs.com/docs/#apply) is valid too) ✅ 
- T (thrush) : [R.applyTo](http://ramdajs.com/docs/#identity) ✅ 
- Y : [RA.Y](https://char0n.github.io/ramda-adjunct/RA.html#.Y) (fascinating one) ✅ 
- Psi (known as [Data.Function#on](http://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Function.html#v:on)) : :x:

```js
// on
const Psi = curry((f, g, x, y) => f(g(x), g(y)));
``` 

We can imagine a variadic arguments version of this one.

**Comment by guillaumearm** [comment]
I updated and add a [Ref](https://gist.github.com/Avaq/1f0636ec5c8d6aed2e45).

In fact, it's missing only `Psi combinator`.

I propose to add `RA.on`.

@char0n, @Undistraction : what do you think ? maybe a flipped version ?

**Comment by char0n** [comment]
Give me some additional time for research. Currently I am missing `R.tap` which is considered K-combinator.

**Comment by guillaumearm** [comment]
`R.tap`, a K combinator ? I can not understand how.

K combinator is `R.always`.

**Comment by char0n** [comment]
I think it makes kinda sense. Observe this
```js
const K = tap(console.dir, 1);

K(); // => 1
```
It's a function that executes a side effect and creates a K-combinator as a byproduct. Basically `tap` is a K-combinator creator.

**Comment by char0n** [comment]
We're only missing Psi combinator. Great job on documenting all the combinators! THank you

**Comment by char0n** [comment]
Created a wiki page from this: https://github.com/char0n/ramda-adjunct/wiki/Combinators

Would be shame to go to limbo.

**Comment by drupol** [comment]
Hi all,
I'm coming across this issue while searching for a combinator stuff on Google.
I don't know if you are still looking for documentation about this, but I made [a package](https://github.com/loophp/combinator) with [a README file](https://raw.githubusercontent.com/loophp/combinator/master/README.md) that contains stuff about combinators.
Let me know if it helped!

**Comment by char0n** [comment]
@drupol good stuff, let me study it for a while and then I'll get back to you. Great job on implementing combinators in PHP!

**Comment by drupol** [comment]
Thanks ! Feel free to ping me if you discover something wrong :)
