### ISSUE TITLE
RA.isTrue, RA.isFalse

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#255]
Don't forget to refactor code that now uses constructs like
```javascript
equals(true)
equals(false)
```

**Comment by rockymadden** [comment]
I can grab this one, have it in a handful of private repos that I can then leverage against.

**Comment by char0n** [comment]
Go for it... don't forget to process 1st comment of this issue though

**Comment by rockymadden** [comment]
Yep, got it.

**Comment by char0n** [comment]
@rockymadden  will you be able to squeeze something at least of them in for [v2.3.0](https://github.com/char0n/ramda-adjunct/milestone/6) release ?

**Comment by rockymadden** [comment]
Yep, I can get that done by the 14th.

**Comment by rockymadden** [comment]
@char0n Family and work has come up, despite my best efforts. I will not be able to finish by tomorrow.

**Comment by char0n** [comment]
Np, don,t worry

**Comment by Undistraction** [comment]
If we had this in we could also add `propIsTrue` and `propIsFalse`. Basically:

```
propSatisfies(isTrue)
propSatisfies(isFalse)
```

**Comment by char0n** [comment]
@Undistraction I would go this way if we find enough usecases in our codebases. If there are no usecases for us at this moment (I don't have one now) I'd rather wait for somebody to request it or for us having a usecases for it.

**Comment by char0n** [comment]
@rockymadden assigned this to [v2.4.0](https://github.com/char0n/ramda-adjunct/milestone/7) milestone. Let's see if we manage to implement at least one of them ;]

**Comment by Undistraction** [comment]
@rockymadden You OK if I pick this up?
