### ISSUE TITLE
unflatten

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#263]
https://www.npmjs.com/package/o-unflatten

Inspiration

**Comment by guillaumearm** [comment]
IMO, it'a a too high level function for RA.
Input object need to have 'id' and 'parentId' keys, is it not too specific ?

**Comment by char0n** [comment]
Yet it is I agree, I'd rather go with the signature that consumes other functions to do the work and configure the behavior: https://www.npmjs.com/package/un-flatten-tree

**Comment by char0n** [comment]
Agree, very high level for this library.
