### ISSUE TITLE
trampoline

### ISSUE THREAD

**Issue by rockymadden** [char0n/ramda-adjunct#265]
Thoughts on adding `trampoline`? It used to be in Ramda itself<sup>1</sup> but was removed for a number of reasons. With TCO still not implemented<sup>2</sup>, except for Safari, and Chrome not working on it at all<sup>3</sup>, we might not see it for quite some time. I'd like to use `Y`, `trampoline`, and `thunk`s to do stack safe recursion <sup>4</sup>. Bilby.js<sup>5</sup> has an interesting implementation in that it also offers `cont` and `done` functions to work with `trampoline` to allow you to return functions and still have the trampolining work.

1. https://github.com/ramda/ramda/issues/1484
2. https://kangax.github.io/compat-table/es6/
3. https://www.chromestatus.com/feature/5516876633341952
4. https://gist.github.com/mrkaspa/d814619283d6a8ac5916
5. https://github.com/puffnfresh/bilby.js

**Comment by char0n** [comment]
Already part of https://github.com/char0n/ramda-adjunct/issues/66

**Comment by rockymadden** [comment]
Nice, thanks.
