### ISSUE TITLE
Absorb ramda cookbook

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#27]
https://github.com/ramda/ramda/wiki/Cookbook

**Comment by char0n** [comment]
@tycho01 can you pls check if I got the typescript for [pickIndexes](https://github.com/char0n/ramda-adjunct/commit/17cc3878cf2649c5d98bd04453d3a5f443eb8bec#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R200) right ?

Thanks a lot

**Comment by tycho01** [comment]
Note that `R.props` can do exactly that, though unfortunately their documentation is lacking an example for the array case, instead demonstrating its use with an object for input.

Your typing here is consistent with the current one we had for [`props`](https://github.com/types/npm-ramda/blob/master/index.d.ts#L2581-L2587), though that one is generalized for both arrays and objects as input. A step enabling better type inference for tuples would involve overloading so as to separately pick out each separate item. That was still marked todo for `props` as well.

**Comment by char0n** [comment]
@tycho01 thanks for review. Do you think it makes sense to keep it in codebase if props can handle this usecase ?

**Comment by tycho01** [comment]
Well, I'm seeing a more general trend between Ramda and Adjunct in generic vs. specific. In that sense, I think it's consistent with the functions already part of Adjunct.

**Comment by char0n** [comment]
I tend to agree. Let's keep it in. Thanks for your opinion

**Comment by tycho01** [comment]
Sure thing, you're welcome. :)

**Comment by char0n** [comment]
I'm doing a full review now and will create separate issues for every function we may implement.
