### ISSUE TITLE
log

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#276]
What about adding a simple `log` function that uses `tap`. Something simple that allows you to add a prefix and log the arg:

```
const log = prefix => tap(
  compose(
    console.log, 
    join(`: `),
    flip(append)([prefix]),
    JSON.stringify,
  )
)

const add3 = flip(add)(3);
const multi2 = multiply(2);
const sub1 = flip(subtract)(1);

const calc = compose(sub1, log(`Log`), multi2, add3); // Log: 16
```

There is a little discussion of something similar in Ramda's issues [here](https://github.com/ramda/ramda/issues/1132). I think it would be perfect for this library. We could of course allow the logging function to be configurable too.

```
const log = curry(
  (loggingFunction, prefix) => tap(
    compose(
      loggingFunction, 
      join(`: `),
      flip(append)([prefix]),
      JSON.stringify,
    )
  )
)

const logToConsole = log(console.log);
```

Could also allow the stringify function to be supplied.

**Comment by char0n** [comment]
Yes this has already been proposed by @BjornMelgaard and the result was https://github.com/BjornMelgaard/ramda-universal-trace. I tend to agree with ramda authors on this issue and I think that neither library (ramda, ramda-adjunct) should contain functions with direct side effects. And yes you can have configurable log function but does that even make sense ? Log functions are usually specific to the application. If we create something like your second version of the `log` IMHO it seems like it is easier to write your own function rather than use this complex configurable yet inflexible composition.

**Comment by Undistraction** [comment]
> I tend to agree with ramda authors on this issue and I think that neither library (ramda, ramda-adjunct) should contain functions with direct side effects.
I guess to me logging is the exception to the rule. I'm always going to need it and I'm always going to use it so it would be useful to have available from this lib.

> And yes you can have configurable log function but does that even make sense
I think it does in some cases - It would offer a quick way to add logging to something server-side.

> IMHO it seems like it is easier to write your own function rather than use this complex configurable yet inflexible composition.
I agree with this - you lose the benefit of having the function ready to use.

**Comment by char0n** [comment]
@Undistraction what is the conclusion here ? My opinion is that people should write their own function or use https://github.com/BjornMelgaard/ramda-universal-trace for debugging.

**Comment by Undistraction** [comment]
I can see how it isn't a perfect fit for this library. Trying to cater to browser and server is potentially complex, and making it configurable removes its immediate utility.

**Comment by Undistraction** [comment]
FWIW Here is module for some impure logging action: https://github.com/Undistraction/ramda-log

**Comment by char0n** [comment]
Feel free to add it to readme.

**Comment by Undistraction** [comment]
@char0n Thanks. I'll do it. Will do another package for `throwErrror()` once I get the chance.
