### ISSUE TITLE
New commiters

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#278]
I am about to release version 2.3.0. I'd like to thank you all for great job that you've done. Namely
 - @Undistraction (contributor)
 - @rockymadden (contributor)
 - @BjornMelgaard (committer)

Also I would like to move @Undistraction and @rockymadden into committer level. You guys contributed enough to become integral part of this project. The more we are, the more work we can done and more things we can learn from each other.

If you interested to join @BjornMelgaard  and me as a committers please explicitly state so in the comment of this issue. Also I would like you to be familiar with the following documents before you do so.

 - [CODE_OF_CONDUCT](https://github.com/char0n/ramda-adjunct/blob/6a7953d712934ea5146a50ee019786a798c7f43c/CODE_OF_CONDUCT.md)
 - [CONTRIBUTING](https://github.com/char0n/ramda-adjunct/blob/0015cc62ee5870b6d4ea9d1246a513cda3e5473a/CONTRIBUTING.md)
 - [GOVERNANCE](https://github.com/char0n/ramda-adjunct/blob/cdd46faf228cc19bbc902921f34425c0183cee7e/GOVERNANCE.md)

Thank you

**Comment by Undistraction** [comment]
Thank you. That would be grand. I can't promise I will always have spare time but I will try and carve out some regular hours.

**Comment by rockymadden** [comment]
Appreciated, @char0n! I would really enjoy being a contributor. I should caution, which you might have noticed, that my personal and professional commitments limit my bandwidth at the moment. I have three very young children (including ~1 year old twins), I am on two on-call rotations, work at a startup, have a side-business, and I am trying to do a rough equivilent of a masters on my own time around functional programming, logic programming, and deeper mathematics. That being said, I have short and long term life goals where functional and logic program are a major component, JS being a big piece of that. I currently use Ramda, Ramda Adjunct, Santuary, Fantasy Land, etc every day and I aim to contribute at a higher frequency.

All to say, what you propose is a perfect fit and my availability should, hopefully, improve over time.

**Comment by rockymadden** [comment]
Oh, and not only have I read those documents but I have also adapted them to internal projects. I am using Conventional Commits and other ideas each and every day 👍.

**Comment by Undistraction** [comment]
@rockymadden My god you make me feel like a slacker ;) I too have started using this style of commit messages and find them nicely compact.

**Comment by char0n** [comment]
@Undistraction, @rockymadden ok cool. Don't feel any time pressure. Feel free to invest time only when you have it or when you feel like it investing it. I will announce that you joined the project on linkedin and twitter this evening and will add you to the README and package.json files accordingly.
