### ISSUE TITLE
What about a RA.isNotEmptyArray ?

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#279]
Hello everyone,

Frequently, I implement myself a `isNotEmptyArray` function : 

```js
const isNotEmptyArray = R.both(RA.isArray, RA.isNotEmpty);
```

I think I'm not alone to doing that, maybe I could make a PR for adding this function ?

We should add `isEmptyArray`, `isEmptyObject` and `isNotEmptyObject` too.

**Comment by char0n** [comment]
Yes, I have the same usecase in the current codebase I'm working on. But I'd go for a following naming:
`isEmptyArray`, `isNonEmptyArray`.

Why ? You can read more about why here: https://github.com/char0n/ramda-adjunct/issues/40

#40 is also dealing with `isEmptyString` and `isNonEmptyString`.

You can own both this and #40 issue and make them realize ;]

**Comment by guillaumearm** [comment]
Yup, i prefer the 'isNonEmpty'  terminology.

PR coming tommorow ;-)

and I would like to say `ramda-adjunct` is an awesome library, the missing piece of `ramda`.

Thank you for your work.

**Comment by char0n** [comment]
Thanks, and you'll be the next one to make it even better ;]

Please make two separate PRs for `isEmptyArray` and `isNonEmptyArray`. Check out this [PR](https://github.com/char0n/ramda-adjunct/pull/258/files) as an example of how a PR should look like.

**Comment by guillaumearm** [comment]
And what do you think about `isEmptyObject` and `isNonEmptyObject` ?

**Comment by char0n** [comment]
@guillaumearm let's continue object discussion here https://github.com/char0n/ramda-adjunct/issues/283

**Comment by char0n** [comment]
From some reason I don't see `isNotEmptyArray` in generated docs for v2.4.0 https://char0n.github.io/ramda-adjunct/2.4.0/index.html

**Comment by guillaumearm** [comment]
'cause it's `isNonEmptyArray`

**Comment by char0n** [comment]
Of course ;]
