### ISSUE TITLE
reduceIndexed

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#281]
```js
// indexedReduce :: ((a, b, c, [b]) -> a) -> a -> [b] -> a
export const indexedReduce = addIndex(reduce);

**Comment by guillaumearm** [comment]
as said in #282, `iReduce` name can be a possibility of name

**Comment by char0n** [comment]
I'd stick with `indexedReduce` because it really says what it does. I can imagine having `ireduce` alias.

**Comment by char0n** [comment]
And to be consistent with ramda I'd rename to `reduceIndexed`

**Comment by char0n** [comment]
@guillaumearm is taking care of this for 2.5.0
