### ISSUE TITLE
isEmptyObject and isNonEmptyObject

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#283]
@guillaumearm said:
And what do you think about isEmptyObject and isNonEmptyObject ?

**Comment by char0n** [comment]
Well it is not that simple. We currently have following predicates for objects: `isObj`, `isPlainObj` and `isObjLike`. I can imagine having new predicate `isEmptyPlainObj` but that's about it. Usecases for other predicate combinations are very limited IMHO.

**Comment by guillaumearm** [comment]
@char0n : You right, as we say in #255, we have to look for use cases before implementing whatever.

I feel there are lot of use cases for `isEmptyPlainObj` and `isNonEmptyPlainObj`, but my feeling is not suffisant, we should think about the right granularity to have with this kind of functions.

for instance, we don't have implemented the `isEmptyArrayLike` and `isNonEmptyArrayLike`.

In addition, I think `isEmptyArray`, `isNonEmptyArray`, `isEmptyPlainObj` and `isNonEmptyPlainObj` are a great combo.

Personally, I like to make functional code in JS only with arrow function, plain object and consistent array as list, and un-consistent array as tuple.
(+ scalar like boolean, number, string, etc, obviously).

**Comment by char0n** [comment]
Ok lets wait a while with this. I've been thinking about this and if I would have a usecase for checking for empty object, I'd do...
```js
isEmpty(testingVar);
```
I would not think about adding new function like `isEmptyPlainObj`. On the other hand, I don't know why, but when I had usecases for testing empty strings or array I immediately created the declarative functions for them (`isEmptyArray`, `isEmptyString`).

**Comment by guillaumearm** [comment]
You right.

let's wait for having really need it.
You can close this issue for now ;-)
