### ISSUE TITLE
xor

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#286]
Exclusive Or. Is true only if exactly one of the values is true.

- T T = F
- T F = T
- F T = T
- F F = F

See: #234

**Comment by dawehner** [comment]
I'll have a look into that one :)

**Comment by dawehner** [comment]
Note: xor is implemented in ramda 0.27, see https://github.com/ramda/ramda/blob/master/source/xor.js

**Comment by char0n** [comment]
Cool, so we'll just wait for 0.27.0, add support for it to ramda-adjunct a then this issue is close. In fact I'd close it now as long as xor is already in ramda master. @dawehner feel free to take any other of our issues ;]

**Comment by dawehner** [comment]
Hi! I'm actually looking into nand now
