### ISSUE TITLE
Add RA in awesome-fp-js

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#294]
Make a PR on the `stoeffet/awesome-fp-js` github repo in able to add `ramda-adjunct`

https://github.com/stoeffel/awesome-fp-js

**Comment by guillaumearm** [comment]
PR here : stoeffel/awesome-fp-js#59
@char0n : is it correct for you ?

**Comment by guillaumearm** [comment]
It's merged : https://github.com/stoeffel/awesome-fp-js

**Comment by char0n** [comment]
Damn did write a comment for this but did not send it. Sorry. Please change it to the following
```md
* [Ramda Adjunct](https://github.com/char0n/ramda-adjunct) is a community-maintained extension of Ramda
```

We want to use this sentence only for outside propagation (as it was created for fantasy-land usecase).

Can you resubmit the PR with the correction ? Thanks

**Comment by guillaumearm** [comment]
@char0n It's merged

**Comment by char0n** [comment]
Very cool. Closing this one then. Nice job.
