### ISSUE TITLE
Ramda Adjunct Theme

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#302]
This is a really small one, but I think it would be helpful if the ramda adjunct site used a different theme colour to ramda. It's great that the two sites are (almost) identical in layout, but I think a complementary colour would work really well and help differentiate between the two when moving between tabs or deep in the docs. I think everything else should remain the same - just with an orange for example instead of the purple.

**Comment by char0n** [comment]
We're using highly modified docdash theme: https://github.com/char0n/docdash

Feel free to create visual prototype (png, jpeg)  im ramda-adjunct theme, so that we can collaborate on which one is the best and after them move to implementing it into our fork of docdash.

**Comment by char0n** [comment]
No update for two years now. We'll have to stick with current theme for now.
