### ISSUE TITLE
Current eslint config lints vast number of files

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#305]
Running `npm run lint` on my machine causes eslint to run on a vast number of files (149315 errors, 2316 warnings) without reporting file names. 

- If I run `node_modules/eslint/bin/eslint.js ./src ./test` I get the correct behaviour.
- If I swap out the `lint` script for `"lint": "eslint ./src ./test",` I get the correct behaviour.
- If I swap out the `betterScripts` `lint` script for `"lint": "eslint ./src ./test",` I get the correct behaviour.

RA cd94a5
OSX 10.11.6

**Comment by guillaumearm** [comment]
It's because `tmp-test-bundle.js` is missing in `.eslintignore`
Try to `npm run clean`

I just make a PR for fixing this => #309
