### ISSUE TITLE
Introduce commitizen

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#313]
According to what was said in #301, it can be a good idea to use [commitlint](https://github.com/marionebl/commitlint) and [husky](https://github.com/typicode/husky)

**Comment by guillaumearm** [comment]
Same thing as #314, @char0n, you can close this issue if you are ok ;-)

Personally, I use [commitizen](https://github.com/commitizen/cz-cli) to write my commit messages.

**Comment by char0n** [comment]
IMHO I think we should has commitizen as devDependancy and provide a package.json script to run it.

**Comment by guillaumearm** [comment]
Agree.

We can use it with [cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog)

and adding this to package.json
```json
{
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "scripts": {
    "commit": "git-cz"
  }
}
```

Usage: 
```bash
$ git add .
$ npm run commit
```

**Comment by char0n** [comment]
We use commit lint and husky, git staged and have a CONTRIBUTING.md document that documents creating commit messages. I think that is enought.
