### ISSUE TITLE
Use lint-staged

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#314]
a bit like #313, maybe we can add a precommit hook to lint staged file.

I use lint-staged on others projects, and it is relatively fast.

**Comment by guillaumearm** [comment]
I remove it from a project, I doesn't like it.
CI are here for doing that kind of things.

So, @char0n, I think you can close this issue.

**Comment by char0n** [comment]
Agree closing.

**Comment by char0n** [comment]
We can use lint-staged to replace pre-commit.sh script.
