### ISSUE TITLE
Use either instead of anyPass

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#320]
use R.either instead of R.anyPass for usecases where there are only two predicates

**Comment by Undistraction** [comment]
I've [suggested]([url](https://github.com/ramda/eslint-plugin-ramda/issues/15)) this as a rule for eslint-plugin-ramda.

**Comment by guillaumearm** [comment]
PR here for eslint-plugin-ramda : https://github.com/ramda/eslint-plugin-ramda/pull/16

**Comment by Undistraction** [comment]
On a related note [Reviewable](https://reviewable.io/) looks pretty nice.
