### ISSUE TITLE
RA.isNonNegative, RA.isNonPositive

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#324]
There are currently `isPositive` and `isNegative`, but we don't offer a way of checking for positive numbers including zero or negative numbers including zero. There is currently no way to check explicity for zero, therefore it isn't possible to do `either(isZero, isPositive)`. 

I suggest adding an `isZero` which would then allow us to add `isPositiveIncludingZero` and `isNegativeIncludingZero`.

**Comment by char0n** [comment]
I think this is a little bit too far. But I understand the reasoning. I suggest to implement `inRange` util with the following signature: `inRange(start: Number, end: Number, number: Number)`

`start - is inclusive`
`end - is exclusive`

What do you think ?

**Comment by Undistraction** [comment]
I definitely like the sound of the `inRange` util, though perhaps `between` might be a better name. Would you see it as implemented using `both(gt(start), lt(end)`?

I know what you mean about `isPositiveIncludingZero` being a little too far, but at the same time, I think in practical terms it is every bit as useful as `isPositive`. I guess the issue is proliferation - what about `isPositiveIntegerIncludingZero`, isPositiveFloatIncludingZero`?

I think a definite yes for the range util, but I do think there is a good argument for `isPositiveIncludingZero` because it satisfies a common need. Looks like there is no generic name for all positive numbers including zero or all negative numbers including zero other than (from Wikipedia): 

> Non-negative numbers: Real numbers that are greater than or equal to zero. Thus a non-negative number is either zero or positive.
> 
> Non-positive numbers: Real numbers that are less than or equal to zero. Thus a non-positive number is either zero or negative.

So how about we ditch the `isZero` and add `isNonNegativeNumber` and `isNonPositiveNumber`. These work nicely as complements of `isPositiveNumber` and `isNegativeNumber`.

**Comment by char0n** [comment]
> I definitely like the sound of the inRange util, though perhaps between might be a better name. Would you see it as implemented using both(gt(start), lt(end)?

Yes I was thinking about that also but lodash is using `inRange` name and it seems more idiomatic than `between`. Also people are also more used to it. I'd vote for some name that is already well known for this.

> So how about we ditch the isZero and add isNonNegativeNumber and isNonPositiveNumber. These work nicely as complements of isPositiveNumber and isNegativeNumber.

This makes sense to me.

@rockymadden, @BjornMelgaard, @guillaumearm what to you think ?

**Comment by Undistraction** [comment]
> This makes sense to me. Maybe we can drop the Number suffix and only use isNonNegative, isNonPositive to be consistent with their complementing counterparts.

Yes. This makes sense.

**Comment by Undistraction** [comment]
@char0n You happy for me to jump on this next?

**Comment by char0n** [comment]
Yup. Go ahead !
