### ISSUE TITLE
isRegExp / isNotRegExp

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#325]
Seems like an obvious addition to me. 

```
const t1 = new RegExp(/x/);
const t2 = /x/;
const t3 = 'x';

const isRegExp = is(RegExp);

console.log(`t1: `, isRegExp(t1)) // true
console.log(`t2: `, isRegExp(t2)) // true
console.log(`t3: `, isRegExp(t3)) // false
```

[REPL](http://ramdajs.com/repl/#?const%20t1%20%3D%20new%20RegExp%28%2Fx%2F%29%3B%0Aconst%20t2%20%3D%20%2Fx%2F%3B%0Aconst%20t3%20%3D%20%27x%27%3B%0A%0Aconst%20isRegExp%20%3D%20is%28RegExp%29%3B%0A%0Aconsole.log%28%60t1%3A%20%60%2C%20isRegExp%28t1%29%29%20%2F%2F%20true%0Aconsole.log%28%60t2%3A%20%60%2C%20isRegExp%28t2%29%29%20%2F%2F%20true%0Aconsole.log%28%60t3%3A%20%60%2C%20isRegExp%28t3%29%29%20%2F%2F%20false)

**Comment by char0n** [comment]
LGTM
