### ISSUE TITLE
reduceIf / reduceUnless

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#329]
Ramda currently supplies `reduceWhile` which is a short-circuiting version of reduce - if the predicate returns false, iteration stops. 

How about a `reduceIf` which has an identical signature, but doesn't short-circuit. It uses the predicate to decide if the `acc` should be returned untouched or the iterator function should be run for every iteration until conclusion.

```
const isEven = x => x % 2 === 0

const predicateIterator = (predicate, iterator) => (acc, value) => predicate(value) ? iterator(acc, value) : acc;

const reduceIf = curry((predicate, iterator, seed, value) => 
  reduce(predicateIterator(predicate, iterator), seed, value));

const a = [
  1,
  2,
  3,
  4,
  5,
  6,
  7
]

const reduceIfEven = reduceIf(isEven, add, 0);

reduceIfEven(a) // 12
```
[REPL](http://ramdajs.com/repl/?v=0.25.0#?const%20isEven%20%3D%20x%20%3D%3E%20x%20%25%202%20%3D%3D%3D%200%0A%0Aconst%20predicateIterator%20%3D%20%28predicate%2C%20iterator%29%20%3D%3E%20%28acc%2C%20value%29%20%3D%3E%20predicate%28value%29%20%3F%20iterator%28acc%2C%20value%29%20%3A%20acc%3B%0A%0Aconst%20reduceIf%20%3D%20curry%28%28predicate%2C%20iterator%2C%20seed%2C%20value%29%20%3D%3E%20%0A%20%20reduce%28predicateIterator%28predicate%2C%20iterator%29%2C%20seed%2C%20value%29%29%3B%0A%0Aconst%20a%20%3D%20%5B%0A%20%201%2C%0A%20%202%2C%0A%20%203%2C%0A%20%204%2C%0A%20%205%2C%0A%20%206%2C%0A%20%207%0A%5D%0A%0Aconst%20reduceIfEven%20%3D%20reduceIf%28isEven%2C%20add%2C%200%29%3B%0A%0AreduceIfEven%28a%29%20%2F%2F%2012)

We could also have a complement `reduceUnless` which returns acc if the predicate succeeds.

Actually not sure if these are the correct names as it sounds like no reduction will take place if the predicate is satisified / unsatisfied. It's more like a filteredReduce.

**Comment by char0n** [comment]
@Undistraction isn't this something that http://ramdajs.com/docs/#reduced solves ?

**Comment by Undistraction** [comment]
`reduced` is a way of early-exiting from a reduction:

> Returns a value wrapped to indicate that it is the final value of the reduce and transduce functions

So it is more related to `reduceWhile` than what I'm suggesting. I'm suggesting a way of applying the predicate to every value supplied to a reducer and only updating the result/acc if the predicate holds true. I'm not suggesting any early exit - the reducer would be called until there are no other values even if one, some or all were not added because the predicate returned true.

**Comment by char0n** [comment]
Ok get it. Looking at http://ramdajs.com/docs/#transduce and http://ramdajs.com/docs/#into if they can be used to get the desired behavior what you're describing.

**Comment by Undistraction** [comment]
With `transduce`:

```javascript
const reduceIfEven = transduce(filter(isEven), add, 0);
reduceIfEven(numbers) // 12
```

But this is pretty non-obvious imho.

**Comment by char0n** [comment]
IMHO I think that your use-case is exactly what transducers are for. If you're familiar with the concept it's more apparent. The only problem that I have with `transduce` is that it's not using SPA (single pass approach). But that's only an optimization problem (https://github.com/char0n/ramda-adjunct/issues/94).

**Comment by Undistraction** [comment]
> The only problem that I have with transduce is that it's not using SPA (single pass approach)
You mean it's iterating separately for every transform? Isn't the whole point that it only iterates once without creating collections in between?

**Comment by char0n** [comment]
Not necessarily.

Check out this link http://raganwald.com/2017/04/30/transducers.html which is in first comment of #94

**Comment by Undistraction** [comment]
Thanks for the link. Will take a look.

**Comment by Undistraction** [comment]
Closing because it's reasonably easy to do with transduce.
