### ISSUE TITLE
appendFlipped

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#333]
One thing I do a lot is `flip(append)`.  I know there is a `concatRight` so how about an `appendRight`? 

```
const appendRight = flip(append);
```

Useful with transformers too which expect (acc, value).

**Comment by char0n** [comment]
LGTM but thinking about nomenclature. Also does it still satisfy the data last principle of ramda ? What is the data and what is the configuration in this case ?

**Comment by Undistraction** [comment]
Well it's an inversion of `append` so I don't see how both it and `append` can both satisfy the data last principle. 

As far as naming goes, I guess the other approach is to name it based on the effect:

- _append_ value to list.
- _extend_ list with value.

However I think we'll struggle to find something that also means specifically adding after. There are other words like 'elongate', 'expand' etc but they don't have the specific meaning that the item will be added to the end.

**Comment by char0n** [comment]
Though about it during this weekend, I still think that using `Right` suffix is incorrect in this case. We are trying to express something different with `Right` in the cases we currently have (in comparison with e.g. `concatRight`). The same applies for ramda.

I'd rather see something like `appendFlipped` which says what it really does. It only flips two first arguments, but doesn't touch the rest of them. We use `Flipped` as suffix instead of prefix to be consistent with `maxIndexed` and alike...

What do you think ?

**Comment by Undistraction** [comment]
I think this is potentially an interesting direction - there are a number of Ramda's functions that I'm always flipping (`gt` for example), so this could be a way of adding those, but at the same time it feels a little weak because we are describing what has been done to the function, not what the function does which I really don't like.  I guess you could say the same about `appendRight` though, but it sounds less like it's exposing the internals that `appendFlipped`. 

How about `appendElement`?

**Comment by char0n** [comment]
Well we can say same thing about ramda's [mapObjIndexed](http://ramdajs.com/docs/#mapObjIndexed) or our `mapIndexed`. It tells us what has been done to the function and IMHO that is something I can relate to. Creating a name for it from the perspective of `what id does` will be very hard.

Try to think of it maybe differently. `append` tells us what the function does and `Flipped` suffix tells us what has been done the function to modify it's behavior. 

`appendElement` seems even more cryptic that `appendRight`. Rather would choose the latter.

**Comment by Undistraction** [comment]
My thinking was that `appendElement` suggests that the data is the element rather than the list, but you are correct - it is just confusing. 

I guess appending `flipped` is the best of a poor bunch.

**Comment by char0n** [comment]
I think we need more opinions before we decide ;]

@BjornMelgaard, @guillaumearm, @rockymadden any opinion on this one ?

**Comment by guillaumearm** [comment]
as char0n said, `Right` suffix is incorrect.

btw, for this use case, I like the `appendTo` name.
e.g. : 
```js
R.pipe(
  R.inc,
  R.inc,
  R.inc,
  R.inc,
  R.appendTo([1, 2, 3])
)(0) // => [1, 2, 3, 4]
```

**Comment by char0n** [comment]
Cool. So we have two candidates. 

appendFlipped and appendTo.

Let's vote for one of them

**Comment by BjornMelgaard** [comment]
@char0n appendFlipped

**Comment by Undistraction** [comment]
I don't think `appendTo` is saying anything different to `append`. If anything it is even more suggestive of the data being the list than `append`, so I vote `appendFlipped`.

**Comment by guillaumearm** [comment]
@Undistraction 
IMHO, `appendTo` suggest first argument is an array rather than `append` suggest  first argument is a value.

append: append what ?
appendTo : appendTo what ?

**Comment by char0n** [comment]
I tend to agree with @guillaumearm on this. See e.g. http://ramdajs.com/docs/#applyTo vs http://ramdajs.com/docs/#apply.

So what about putting in `appendFlipped` with alias of `appendTo` ?

**Comment by Undistraction** [comment]
I don't agree with your logic.

- `applyTo` Makes sense because it is saying 'Apply the first argument (the value) to the second (the function).
- `appendTo` doesn't make sense because it is saying append the _second_ argument (the element) to the the _first_ argument (the list).

This is back to front. In reality it would probably have made more sense if `append` had been called `appendTo`, then we could use `append` for `flip(append)`, but that horse has bolted, so  I think adding `appendTo` in any form is confusing.

**Comment by char0n** [comment]
I get you, just looking at the @guillaumearm composition it looked really understandable:
```js
R.pipe(
  R.inc,
  R.inc,
  R.inc,
  R.inc,
  R.appendTo([1, 2, 3])
)(0) // => [1, 2, 3, 4]
```
So it's decided, most votes got `appendFlipped`. `appendTo` alias is for further debate, but not that important at this point.
