### ISSUE TITLE
remove opencollective from package.json

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#339]
It only adds the only and and unnecessary dependency

**Comment by char0n** [comment]
@Undistraction, @guillaumearm, @BjornMelgaard what is your opinion on this one ? Currently we have opencollective as the only dependency and it gets installed them RA gets installed. But along with that it requires a lot of it's dependencies. I'd rather not have it as a dep. It's only purpose is to emit messages about RA's opencollective after installation.

**Comment by BjornMelgaard** [comment]
:smile: if you don't want to solicit

**Comment by char0n** [comment]
I'd rather take the stand of not soliciting than complicate the usage of library. Having opencollective as dep, for example in Oracle means to submit the library it self for approval and then the opencollective and all it's dependencies. I'd rather not deal with that personally and also I don't want to complicate approvals in other corporate environments.

**Comment by Undistraction** [comment]
I say lose it.
