### ISSUE TITLE
toArray

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#342]
This functions should convert value to an Array. Following rules are required to be satisfied by the implementation and by the tests:

**Should return shallow copy of an array**
```js
RA.toArray([1, 2]); // [1, 2]
```

**Should return values of object**
```js
RA.toArray({'foo': 1, 'bar': 2}); //=> [1, 2]
```

**Should convert string to array**
```js
RA.toArray('foo'); //=> ['f', 'o', 'o']
```

**Should convert any Iterable to array**
```js
const map = new Map();
map.set('0', 'foo');
map.set(1, 'bar');

RA.toArray(map); //=> [['0', 'foo'], [1, 'bar']]
```

```js
const set = new Set([1, 2, 3]);

RA.toArray(set); //=> [1, 2, 3]
```

```js
const object = { '0': 'a', 'length': 1 };
object[Symbol.iterator] = Array.prototype[Symbol.iterator];

RA.toArray(object); //=> ['a']
```

Technically this function is very similar to function [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from), except that `Array.from` returns empty array if plain javascript objects is provided. For the implementation it is possible to use `Array.from` internally (if available) and handle the the differences manually. 

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `toArray` function.

**Comment by guillaumearm** [comment]
Can you be more precise about what is `RA.toArray` is supposed to do ?

**Comment by char0n** [comment]
@guillaumearm should do exactly what https://lodash.com/docs/4.17.5#toArray does

**Comment by char0n** [comment]
@rafaelpadovezi go ahead! It's all yours ! ;]
