### ISSUE TITLE
RA.overProp, RA.overPath and RA.overIndex

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#348]
Because I always import [R.over](http://ramdajs.com/docs/#over) with [R.lensProp](http://ramdajs.com/docs/#lensProp) or [R.lensPath](http://ramdajs.com/docs/#lensPath).

Why not add a `RA.overProp`, `RA.overPath` and `RA.overIndex` helpers in RA ?

```js
const { curry, over, lensProp, lensPath, lensIndex } = require('ramda')

const overProp = curry((key, f, obj) => (
  over(lensProp(key), f, obj)
))

const overPath = curry((path, f, obj) => (
  over(lensPath(path), f, obj)
))

const overIndex = curry((index, f, obj) => (
  over(lensIndex(index), f, obj)
))
```

**Comment by Undistraction** [comment]
This makes sense to me.

**Comment by guillaumearm** [comment]
@char0n , If this feature and #349 looks good to you, I can make PRs today, maybe you would add this to the 2.5.0 release.

**Comment by Undistraction** [comment]
I think @char0n will want to take a look.

**Comment by char0n** [comment]
Seems legitimate but thinking about nomenclature. IMHO I think `over*` should always consume lenses. We have to create more sensible nomenclature for these fusion shortcuts so that e.g. `overWhen` still make sense.

**Comment by guillaumearm** [comment]
Totally agree with that : 

> over* should always consume lenses

Personally, I love `_.update`.
In first place I have thought about `RA.update*` but `R.update` is already here (by the way , I don't like this name for setting an array element).

Find an alternative to `_.update` is a huge deal for me, I need some time to think about that.

**Comment by GingerPlusPlus** [comment]
(not talking about naming)

`RA.overIndex` is just `R.adjust`.

`RA.overProp` and `RA.overPath` could be also expressed with `R.evolve`. I'm fine with having them.

**Comment by char0n** [comment]
I'm closing this one. Haven't seem upvotes for this outside our group.
