### ISSUE TITLE
RA.overWhen / RA.overUnless

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#349]
Sometimes, I add a helper like this to my codebase :

```js
const R = require('ramda');
const overNonNil = curry((lens, f, state) => {
  if (RA.isNotNil(R.view(lens, state))) {
    return R.over(lens, f, state);
  }
  return state;
})
```

need opinions about this function.

According to #348, should we add `RA.overNonNilProp`, `RA.overNonNilPath`and `RA.overNonNilIndex` ?

## Edit
(according to @Undistraction  advices)

Implement a more generic `RA.overWhen` instead of `RA.overNonNil`

#### RA.overWhen

```js
const overWhen = R.curry((predicate, lens, f, state) => {
  if (predicate(R.view(lens, state))) {
    return R.over(lens, f, state);
  }
  return state;
})
```

and add `RA.overPropWhen`, `RA.overPathWhen`and `RA.overIndexWhen`. (according to implementation below)

**Comment by Undistraction** [comment]
Would it make more sense to make this a little more generic. Rather than checking specifically for `isNotNil` expose the predicate:

`overPropWhen`, `overPathWhen`, `overIndexWhen`

**Comment by guillaumearm** [comment]
You right, I'm totally ok with your advice.

Checking if a property field is not null before update is very frequent, but the opposite is still true. (`overNilProp`, ...).

Sometimes I like to compose lenses, so it would be great to add a generic `RA.overWhen` function.

What about adding `RA.overWhen` in addition to `RA.overPropWhen`, `RA.overPathWhen` and `RA.overIndexWhen` ?


### RA.overWhen
```js
const overWhen = R.curry((predicate, lens, f, state) => {
  if (predicate(R.view(lens, state))) {
    return R.over(lens, f, state);
  }
  return state;
})
```

### RA.overPropWhen
```js
const overPropWhen = R.curry((predicate, key, f, state) => (
  overWhen(predicate, R.lensProp(key), f, state)
))
```

### RA.overPathWhen
```js
const overPathWhen = R.curry((predicate, path, f, state) => (
  overWhen(predicate, R.lensPath(path), f, state)
))
```

### RA.overIndexWhen
```js
const overIndexWhen = R.curry((predicate, index, f, state) => (
  overWhen(predicate, R.lensIndex(index), f, state)
))
```

**Comment by char0n** [comment]
`overWhen` is legitimate. Regarding the other derived functions...let's hold until we clear it out in #348

**Comment by GingerPlusPlus** [comment]
Why not just use `R.over(someLens, R.when(pred, fn))`?

**Comment by char0n** [comment]
Yeah that's a legitimate question.

**Comment by guillaumearm** [comment]
@GingerPlusPlus : 

because `over(lensProp('a'), identity, {})` returns `{ a: undefined }`

**Comment by Undistraction** [comment]
@guillaumearm Just got snagged by this exact issue using an `unless`.  I think `overWhen` and `overUnless` would be nice additions.

**Comment by char0n** [comment]
Before we move forward with implementation let's consider the naming first: https://github.com/ramda/ramda/issues/65

`when` vs `by`

**Comment by char0n** [comment]
Right, sorry. What about the `when` vs `if`. Do we have some semantics for these two words ?

**Comment by Undistraction** [comment]
Ramda only uses `when` because `if` is native and carries this over for composite functions – `R.splitWhen` would appear to be the precedent – so I think:
- overWhen
- overUnless 

Do we see a usecase for `overIfElse`?

**Comment by GingerPlusPlus** [comment]
`overIfElse`? Just `R.over(someLens, R.ifElse(t, f))`

**Comment by char0n** [comment]
Ok agreed then. It's `overWhen` and `overUnless`. Will make a nice addition to our lens utilities.

I'd go for a following signature instead of one proposed [here](https://github.com/char0n/ramda-adjunct/issues/349#issue-296024862). I'd like to keep the functional interface as close as possible with `over`.
```ks
overWhen(lens, predicate, transformer, data)
```

**Comment by guillaumearm** [comment]
I disagree because I think all `*When` function should take predicate first.
So we can say `R.over` is equivalent to `RA.overWhen(R.T)`

`RA.overWhen` can be considered like a `over` factory

**Comment by char0n** [comment]
Right, good point @guillaumearm I agree with your disagreement ;]

**Comment by crvouga** [comment]
over(
    lens,
    when(predicate, transformation),
   x
)

**Comment by char0n** [comment]
@crvouga just for a reason having specialized well tested named compositions. Do you think `overWhen` would be overkill ?

**Comment by char0n** [comment]
I'm closing this one. Haven't seem upvotes for this outside our group.
