### ISSUE TITLE
Add promise <-> monad bridge functions

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#35]
~~resolveP~~, ~~allP~~, tapP, ~~thenP~~, catchP, thenCatchP, ~~rejectP~~, raceP, ~~reduceP~~, ~~isThenable~~, ~~isPromise~~, tryP

**Comment by rockymadden** [comment]
Something like https://github.com/kirillrogovoy/promised-pipe might also be useful.

**Comment by char0n** [comment]
@rockymadden isn't [pipeP](http://ramdajs.com/docs/#pipeP) what you're looking for ?

**Comment by rockymadden** [comment]
If all functions are return promises, yes. The promised-pipe brings the ability to intermix, at any point, sync and async functions.

**Comment by char0n** [comment]
pipeP does the same. The only requirement is that first function in the pipe must be promise generator (returns promise). 

```javascript
const { add, subtract }  = require('ramda');

const resolveP = Promise.resolve.bind(Promise);
const asyncAdd = val => resolveP(val).then(add(1));

pipeP(
  resolveP,
  add(1),
  subtract(1),
  asyncAdd,
  add(2),
  subtract(1)
)(1);
```

**Comment by rockymadden** [comment]
Nice, hmm yeah ignore me then. Thanks!

**Comment by char0n** [comment]
NP

**Comment by rockymadden** [comment]
Thoughts on your `resolveP` function or (`R.bind(Promise.resolve, Promise)`) being made into a standard function in adjunct (e.g. `resolveP` or `ofP`)? Seems to be generally usable to kick things off as a Promise.

**Comment by char0n** [comment]
Yep, the plan is to implement it. Checkout out the first comment of this issue. It is the first function to be implemented for this issue ;]

**Comment by char0n** [comment]
You can provide a pull request for it if you wish and become a contributor. ramda-adjunct ecosystem is ready to receive PR's and I always welcome any help. What do you think ?

**Comment by rockymadden** [comment]
Yep, love it. I've had a subset of this library internally for a while. Was reading through the Ramda wiki and saw `ramda-adjunct`, which was exactly what I myself was doing.

**Comment by char0n** [comment]
Yep, I guess everybody is doing it. This library has a potential saving a lot of development time to a lot of people. Check this [article](https://www.linkedin.com/pulse/ramda-adjunct-vladim%C3%ADr-gorej) to find out more.

Great, check out the [CONTRIBUTING.md](https://github.com/char0n/ramda-adjunct/blob/master/CONTRIBUTING.md) and you can start right away.

**Comment by char0n** [comment]
Further inspirations: https://github.com/krainboltgreene/unction.js?files=1

**Comment by char0n** [comment]
https://stackoverflow.com/questions/27746304/how-do-i-tell-if-an-object-is-a-promise

**Comment by Undistraction** [comment]
@char0n You OK if I bump this to 2.7.0?

**Comment by char0n** [comment]
Bump it up or remove the milestone entirely. Have no usecases for the rest of them right now.

**Comment by Undistraction** [comment]
@char0n When you get a chance maybe move remaining to separate issues.

**Comment by char0n** [comment]
Yeah me or anybody else can do that. 

Note for me and others: when doing it reference this issue in the child issues just for reference and then close this one.

**Comment by guillaumearm** [comment]
since #676, additional candidates are :

- **mapP**
- **filterP**
- **rejectP**

IMO, we need to talk about parallel and series behavior, isn't ?

**Comment by char0n** [comment]
Created separate issue for [raceP](https://github.com/char0n/ramda-adjunct/issues/1231)

**Comment by char0n** [comment]
created separate issue for [catchP](https://github.com/char0n/ramda-adjunct/issues/1232)

**Comment by char0n** [comment]
created separate issue for [thenCatchP](https://github.com/char0n/ramda-adjunct/issues/1233)

**Comment by char0n** [comment]
Not going to implement tapP for now.
