### ISSUE TITLE
isIterable/isNotIterable

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#351]
Can we add a predicate to check if a value is or isn't iterable?

A basic check:
```
either(isArray, isPlainObj)
```
Note: the `isPlainObj` as opposed to `isObj` is needed to avoid false positives for things like RegExp objects. 

But I'm not sure exactly what else Ramda classifies as an Iterable, so this will probably need to be fleshed out.

Note discussion and usecase in #350

**Comment by char0n** [comment]
I don't think it that simple. IMHO iterable is everything that implements [Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator).

**Comment by Undistraction** [comment]
I guess I was thinking about this from a Ramda perspective - as a way to detect which objects would be iterable by Ramda's functions that support iteration. 

I think it is too ill-defined so I will close.

**Comment by dimitropoulos** [comment]
well hold on a sec.  I just ran into a use case for this.  How about something simple like

```javascript
const isIterable = obj => {
  if (obj === null || obj === undefined) {
    return false;
  }
  return typeof obj[Symbol.iterator] === 'function';
};
```

I recognize that this doesn't rely on ramda, but also the point of all this is a utility library and I feel like this particular function has utility.  @char0n let me know if you are interested in me putting up a PR.

:)

**Comment by char0n** [comment]
I think this has use-cases, but it must be implement as you suggest, checking for `Symbol.iterator` according to [iterator protocol spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols). We also have to be careful to make this function `safe` in a sense, that when `Symbols` are not supported in javascript env where RA is used, it must not fail; the `isIterable` will always return false if `Symbol` don't exist.

Go for a PR, this is a valid predicate.
