### ISSUE TITLE
@guillaumearm as core commiter

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#355]
To: @Undistraction, @rockymadden, @BjornMelgaard

I would like to propose the case for @guillaumearm becoming a core commiter into RA. From the moment he discovered the project until now he has shown consistent interest in the project and provided the project with a lot of improvements and PRs. IMHO I think he is a valuable asset and can help us keep the project going.

Opions ? Votes ?

**Comment by Undistraction** [comment]
For sure. He has been working hard and absolutely deserves it.

**Comment by BjornMelgaard** [comment]
Yes

**Comment by char0n** [comment]
@guillaumearm congratulations, you've become a core commiter ;]

I'll add you to the repo contributors during today. Meantime checkout the following documents:

[CODE_OF_CONDUCT](https://github.com/char0n/ramda-adjunct/blob/master/CODE_OF_CONDUCT.md)
[CONTRIBUTING](https://github.com/char0n/ramda-adjunct/blob/master/CONTRIBUTING.md)
[GOVERNANCE](https://github.com/char0n/ramda-adjunct/blob/master/GOVERNANCE.md)

**Comment by Undistraction** [comment]
@guillaumearm Congratulations!

**Comment by guillaumearm** [comment]
Thank you all, for everything, 
I'm very enjoying to join the ramda-adjunct journey with all of you.

It' a lot of emotions for me :-).
