### ISSUE TITLE
Inverse ramda compat order in test:ramda script

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#358]
Because I'm unable to find what Ramda version is causing problem in #281, I have thought about inversing test order : 

```
- bnr test:ramda0.25.0
- bnr test:ramda0.24.1
...
- bnr test:ramda0.19.0
```

instead of : 

```
- bnr test:ramda0.19.0
...
- bnr test:ramda0.24.1
- bnr test:ramda0.25.0
```

**Comment by char0n** [comment]
Why not, the order should not make a difference to the overall test results. So if makes founding incopatible ramda version easier...I am for that.
