### ISSUE TITLE
whenAlways

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#363]
There is a pattern which I keep using which feels like an antipattern, but is seems to be common:

When using `when`, you often need the predicate to refer to some value other than the one you want to transform:

```
when(always(predicate(value1)), transform)(value2)
```

The inverse if also possible, but is less readable:

```
when(predicate, always(transform(value2)))(value1)
```

I'm wondering if we can do something like:

```
whenAlways(predicate(value1), transform)
```

[Edit] The rest of this is just braindump. The issue is meant to address the above.

Or is there a better way to do this? Could we offer a version of when with two args, so the first arg is mapped to the predicate and the second to the transform.

```
whenAlways(predicate, transform)(value1, value2)
```

 Obviously that would be a lot less portable as it isn't unary, so I suppose this is possible:

```
whenAlways(predicate, transform)([value1, value2])
```

**Comment by guillaumearm** [comment]
I'm not sure about the last 2. It's weird IMO. (for comprehension and for composition)

But I'm totally OK with the first one : 
```js
whenAlways(true, f) //=> f
whenAlways(false, f) // => R.identity
```

The other case is more specific, you want to set a value if predicate returns true : 
```js
setWhen(R.equals(''), 'Hello World')('') //=> 'Hello World'
setWhen(R.equals(''), 'Hello World')('hello') //=> 'hello'
``` 

I'm not sure if setWhen is a good name, but this is the idea.

For the last case, maybe we can found a valid name for doing this.

**Comment by Undistraction** [comment]
Yep. They are weird for sure. I think I confused matters with them.

The problem I'm really trying to solve is the frequent use of `when(always(p(x)), f)(v)`.

Your second examples are basically `defaultWhen` which we already have.

**Comment by guillaumearm** [comment]
Yup, `defaultWhen` is a better name for sure.

Anyway, the second problem you're trying to solve is : 
```js
when(always(predicate(value1)), always(transform(value2)))("it's value2 here, it's a fallback if cannot satisfy predicate")
```

It's a bit like a normal `ifElse` but with values instead of functions.

```js
ifElseValue(true, 'then', 'else'); //=>  'then'
ifElseValue(false, 'then', 'else'); //=>  'else'
```

I think we should create a second issue to discuss about this case, and find a name ;-)

**Comment by char0n** [comment]
Closing for now. No upvotes for sar.
