### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#367]
Whilst there is loads of good info in the README, there is no list of the functions Ramda Adjunct provides. I think we should add this right at the top, with links to the docs. That way somebody doesn't need to click to see what the project offers. 

It might also be useful to break the functions down by type - predicate etc to make parsing easier.

So we need:

- [x] Update intro text for README
- [x] Update description (on repo and npm)
- [x] Move link to docs to top of README
- [ ] Only link to _latest_ and _previousVersions_ in README
- [ ] Create Previous Versions or All Versions page (not sure if this already exists)
- [x] Consider including list of functions in README

**Comment by char0n** [comment]
I think it's kind of duplicate effort. What about moving our documentation section right on top of README.md file and make is somehow better ? Create link to functions list and add maybe some examples and so on.... It will be the first thing people see when they come to the repo. Nor ramda, nor for example redux have full list of functions directly in README.md file.

**Comment by Undistraction** [comment]
> What about moving our documentation section right on top of README.md file

This would be a good start. I have to say I think that having links to every version of docs is distracting, so how about one prominent link to latests docs at the top of the README, then a link to previous versions. 

> Nor ramda, nor for example redux have full list of functions directly in README.md file

I'm just looking at this from the perspective of a new user. If I'm looking at a utility library the most important thing I want to know is what utilities are provided. Ramda and Redux are really well known - people are most probably there to learn *how* to use them, not to find out *what* they offer. 

That said, I can see that a list of all functions is ungainly (and will be a perfect place for docs to go out of sync), so a prominent link at the top gets us part of the way there. Maybe coupled with a paragraph explaining the kinds of functions offered and possibly mentioning the number of functions offered this would be enough. I think that the current text:

> This library is a community maintained extension of Ramda.

Is really confusing. I think something like:

> Ramda Adjunct is a comprehensive and well tested library of pure functions for use with Ramda, including a large selection of predicates, tools for working with lenses and for composing and manipulating functions, objects and lists.

**Comment by guillaumearm** [comment]
- If we change the description, I can re-make a PR on https://github.com/stoeffel/awesome-fp-js
- List all RA functions in README.md is a very good idea, but IMHO we cannot trust our human rigor to maintain that, I propose to automate this step using tools like [node-plop](https://www.npmjs.com/package/node-plop)

**Comment by Undistraction** [comment]
We should also change the strapline for the repo which is currently:

> Adjunct is a thing added to something else as a supplementary rather than an essential part. And that something is being ramda. https://char0n.github.io/ramda-adjunct/

**Comment by char0n** [comment]
After reviewing it, @Undistraction I agree with your points. We need to evolve the` readme` to move the project forward. The generation of function list needs to be automated though. In the first comment of this issue please create checklist of actions points that you feel are necessary to execute.

**Comment by Undistraction** [comment]
@char0n Ha. I'd also come round to your thinking that a list of functions was too much for the README. Anyway, I've updated with checklist.

**Comment by char0n** [comment]
Everything processed here.
