### ISSUE TITLE
RA.argsPass

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#370]
Build a predicate that maps multiple args to multiple predicates:

[(* -> Boolean)] -> *... -> Boolean

```
const multiPredicate = predicates => useWith(and, predicates)
const configuredMultiPredicate = multiPredicate([is(Boolean), is(String)])
configuredMultiPredicate(false, 's')
```

[REPL](http://ramdajs.com/repl/?v=0.25.0#?const%20multiPredicate%20%3D%20predicates%20%3D%3E%20useWith%28and%2C%20predicates%29%0Aconst%20configuredMultiPredicate%20%3D%20multiPredicate%28%5Bis%28Boolean%29%2C%20is%28String%29%5D%29%0AconfiguredMultiPredicate%28false%2C%20%27s%27%29)

**Comment by guillaumearm** [comment]
Awesome !

The function name LGTM.

Need more functions like this + build multi arguments function this way is very cool IMO.

**Comment by Undistraction** [comment]
There are definitely a few things to think about - This code above uses `and` so its limited to two args, however it would be nice to allow more than two predicates / args. However, there is no multi-arg equivalent of `and`, so this will require some rethinking. 

Also, `useWith` will pass additional args untouched into the first function, so this might be problematic.

**Comment by guillaumearm** [comment]
What about this implementation ? 

```js
const repeatUndefined = R.repeat(undefined);
const zipApplyTo = R.zipWith(R.applyTo);
const allTrue = R.all(R.equals(true));

const multiPredicate = (predicates) => (...args) => {
 const missingArgs = repeatUndefined(Math.max(0, predicates.length - args.length));
 return allTrue(zipApplyTo([...args, ...missingArgs], predicates));
};

multiPredicate([R.is(String), R.is(Boolean)])('', true); // => true
```

[REPL](https://goo.gl/u8sAnW)

**Comment by char0n** [comment]
I'd go for `argsPass` or something similar.

> However, there is no multi-arg equivalent of and, so this will require some rethinking.

You can have what you need with this `R.unapply(R.all(RA.isTrue))`

Of course for this we need to have `RA.isTrue`.

> Also, useWith will pass additional args untouched into the first function, so this might be problematic.

Wouldn't worry about that, if we document this behavior as expected.


```js
const argsPass = R.useWith(R.unapply(R.all(RA.isTrue)));

argsPass([RA.isString, RA.isArray])('', []); //=> true
```
I still invite any suggestion for better names, but it's friday evening and this is the most I could come up with ;]

**Comment by guillaumearm** [comment]
@char0n : oh, it's even better conserving usage of `R.useWith` because we can benefit from auto-currying.

Just a little correction, did you mean `RA.isTruthy`  ?

In the ramda world, a predicate is not especially a function which return a boolean value. it returns falsy or truthy value.

**Comment by char0n** [comment]
> Just a little correction, did you mean RA.isTruthy ?

> In the ramda world, a predicate is not especially a function which return a boolean value. it returns falsy or truthy value.

Nope, I meant `RA.isTrue === R.eq(true)`. Provide an example of what you mean pls by your statement. All ramda predicates and all RA predicates return values in `Boolean` category which consists of two exclusive objects (true or false).

**Comment by guillaumearm** [comment]
Yup, you right.
Sorry, I badly formulated.

By ramda predicate, I mean all ramda functions which take predicates. (like `R.filter` and `R.reject`)
They do not assumes especially that predicate return a bool.

e.g.  

```js
R.filter(R.identity, [undefined, undefined, undefined]) // make a compact
```

**Comment by char0n** [comment]
Agree, `RA.isTruthy` is consistent with ramda's HOCs consuming predicates. Good catch!

**Comment by Undistraction** [comment]
Here is more flexible version:

```
const argsPass = curry((c, ps) => useWith(
  compose(c(isTruthy), list),
  ps,
 ))

const result = argsPass(all, [isString, isArray])('', []); //=> true
````

[Codepen](https://codepen.io/Pedr/pen/KQZWxQ?editors=0012)

**Comment by guillaumearm** [comment]
@Undistraction : This one is awfully efficient ;-).

In addition, the `argsPass` name is more justified here, it is very more semantic this way. 

e.g.
```js
argsPass(all) // does all args predicates satisfies ?
argsPass(any) // does any args predicates satisfies ?
argsPass(none) // does none args predicates satisfies ?
```

-----------

Just a point :

- `argsPass` first argument function must be curried to work.

this is not necessarily bad, we just have to document this behavior.
Why this is not a bad thing ? this allows to bypass the `RA.isTruthy` predicate using `R.always`.

e.g.

```js
argsPass(always(all(isFalsy)))
```

----------

by the way,
> a function is returned which is unexpected.

do you mean it is the expected behavior ?
IMHO, it's correct because final function is curried.

**Comment by Undistraction** [comment]
> this is not necessarily bad, we just have to document this behavior

Agreed

> do you mean it is the expected behavior ?
> IMHO, it's correct because final function is curried.

I guess it's fine if we document it, and actually that's really interesting, because you can build a chain of predicates, then supply the args one by one.

**Comment by char0n** [comment]
If the function will work in the following way (currying + logic)
```js
argsPass(all)([isString, isArray])('')([]); // => true
```
....I'd go for it.

**Comment by Undistraction** [comment]
That's how it works already in the Codepen I linked to above.

> [Codepen](https://codepen.io/Pedr/pen/KQZWxQ?editors=0012)
