### ISSUE TITLE
ensureArray

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#371]
I just chat with a friend about using the following function :

```js
// a | [a] -> [a]
const ensureArray = R.when(RA.isNotArray, R.of);
```

e.g. : 

```js
ensureArray(42); // => [42]
ensureArray([42]); // => [42]
```

IMO, It is a recurrent pattern in JS, what do you think of adding it in ramda-adjunct?

**Comment by char0n** [comment]
LGTM; Ref: https://github.com/jeffbski/ensure-array

**Comment by guillaumearm** [comment]
Question : does ensureArray is an arity 1 function ? or arity n ?
 
Concretely, does `RA.ensureArray(1, 2)` should return `[1, 2]` or `[1]` ?

**Comment by Undistraction** [comment]
I don't think it makes sense to have an artity greater than one - it doesn't make sense that you are _ensuring_ something is an array if there are more than one of it. Otherwise it feels more like a constructor. However maybe it would make more sense with a different name.
