### ISSUE TITLE
7 ramda recipes

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#38]
http://czyzykowski.com/posts/7-ramda-recipes.html

**Comment by char0n** [comment]
Hi @czyzykowski,

Sorry for bothering you, just to let you know, I came across you recipes, and thinking about assimilating some of then into ramda-adjunct. Are you cool with that ?

**Comment by czyzykowski** [comment]
Hi @char0n,

Sure, go ahead. 👍

**Comment by char0n** [comment]
@czyzykowski your site seems to be down.

Mirror: http://web.archive.org/web/20161123064854/http://czyzykowski.com/posts/7-ramda-recipes.html

**Comment by czyzykowski** [comment]
Thanks. I know about it. I'm working on bringing it back.

**Comment by guillaumearm** [comment]
### contained
Very good idea, I think `RA.oneOf` is a better name.

### filterT
I prefer the name `RA.compact`
Like the lodash `_.compact` function. I use a lot.

### allT
very useful, but I don't like the name, @charOn what do you think ?

### safeHead
very useful, what about a collection of RA.safe* functions ?

### toTitle
Here, IMO, it's a bit front-end oriented.

### imap
Why not, I use React a lot, so for me it's fine.

### peek
I don't agree with adding `RA.peek`.
ramda is 100% pure,
I think ramda-adjunct should be too.

There is a good library for debugging point-free code : https://github.com/sebinsua/ramda-debug/

**Comment by char0n** [comment]
**contained**
Candidates: `oneOf`, `within`

**filterT**
Candidates: `compact`

**allT**
I see to few usecase; `all(isTruthy, [1,2,3])` is sufficient

**safeHead**
wouldn't go there, it can hide nasty errors

**toTitle**
 capitalize (should be same as lodash.capitalize)

**imap**
We're dealing with this in another issue

**peek**
We don't want anything unpure inside the library

**Comment by guillaumearm** [comment]
Hum, and if `safeHead` function return a Maybe ? :-D
Can we add a `Monadic` category in README.md ?

**Comment by char0n** [comment]
Then I'd say that this is usecase then for entirely another kind of library. What we try to do here is produce total, referential transparent pure functions. That is why we are using Hindlery-Millner signatures to define a category for a function input. If the Category/Type of the input is not satisfied then the behavior of the function is undefined. It is the same as fantasy land spec defines it's types and operators.

**Comment by guillaumearm** [comment]
Yup I agree, in addition there is a library called [sanctuary](https://github.com/sanctuary-js/sanctuary) for doing that kind of things ;-)

**Comment by Undistraction** [comment]
Looks like the only one that is left as a possibility is `contained` (other than impure `peek`/`log`). Do we want to add it?

**Comment by guillaumearm** [comment]
Yup, agreed.
**toTitle** (capitalize) is missing to, I just a create an issue for it. (Ref #389)

**Comment by guillaumearm** [comment]
I just created an issue for `oneOf`. Ref #392.

everything has been addressed here, close the issue.
