### ISSUE TITLE
throwError

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#380]
I know this is a contentious one, but I think a `throwError` would be a good addition. I fully realise that we should be using the functional approach to avoid the need for throwing, but in many cases, throwing is a necessary part of the API we expose - I'm working on a thin API for use with Styled Components.  If the consumer supplies invalid input I need to throw and tell them what the problem is so they can amend the input. It makes no sense here to recover or continue. In this instance I would prefer to a use a well tested `throwError` function from this lib than have to bake my own. 

```
const throwError = error => {
  throw error;
};
```

**Comment by guillaumearm** [comment]
I never ask myself, is an error throw is pure ?

**Comment by char0n** [comment]
@guillaumearm no, it's a classical side effect. 

@Undistraction we can talk about it and brainstorm, but my feeling are clear on this one. This a side effect and should not be part of a pure functional library. I know it's practical, IMHO belongs somewhere else.

**Comment by Undistraction** [comment]
@char0n It's your call: I guess we'll kick it out on the streets to beg for change along with `log`. Or I can create a new lib called `ramda-adjunct-adjunct` …

**Comment by guillaumearm** [comment]
And what about a `ramda-adjunct-effects` library ?
This may be a `packages/ramda-adjunct-effects` in this repository (the monorepo way) and we could add `peek` from #38 and so on.

**Comment by Undistraction** [comment]
@guillaumearm I like that idea. I think this is a good compromise.
