### ISSUE TITLE
Git hooks (prepush/precommit)

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#381]
This issue is a continuation of #379 discussion about git hooks.

Related issues : #301, #313, #314

I think adding a prepush hook is very good idea, I personally run `prepublishOnly` before every of my push.

But for precommit I disagree, it's unpleasant to wait for it, and [lint-staged](https://github.com/okonet/lint-staged) cannot be used because okonet/lint-staged#62

**Comment by GingerPlusPlus** [comment]
I think `prettier --write`  should be run on `precommit`, and you don't have to use `lint-staged`, `prettier` suggest [a few solutions](https://prettier.io/docs/en/precommit.html). [`precise-commits`](https://github.com/nrwl/precise-commits) looks especially interesting:

> This is currently the only tool that will format only staged lines rather than the entire file.

**Comment by guillaumearm** [comment]
It seems to be a very nice solution, I will try `precise-commts` with a PR

**Comment by guillaumearm** [comment]
it seems to not work as well I expected :/

effectively, `precise-commits` verify only staged lines, but there is a bug.

- when I stage some bad code : `precise-commits --check-only` fails ✅ 
- when I stage some bad code and I edit my file to correct this manually and keep this modification unstaged : `precise-commits --check-only` successful ❌ 

It's a false positive, because staged lines is still good.

**Comment by GingerPlusPlus** [comment]
Well, no, that modification is unstaged

**Comment by guillaumearm** [comment]
The correction is unstaged, and bad code is still staged, so it should fails ? did I miss something ?

**Comment by GingerPlusPlus** [comment]
Yes, it checks or formats __staged__ changed. When you stage some bad code, and correction is unstaged, it checks the bad, staged code.

And, in git, you need to stage stuff to commit it, so I think this is correct.

**Comment by GingerPlusPlus** [comment]
`precise-commits --check-only` should be used in CI, but in `pre-commit auto fixing wouldn't be bad.

**Comment by guillaumearm** [comment]
> it checks the bad, staged code.

No it don't. I just test

I think there is a bug, I go for creating an issue into [nrlw/precise-commits](https://github.com/nrwl/precise-commits).

**Comment by guillaumearm** [comment]
woops, i just understood the misunderstanding

above, I said : 
> It's a false positive, because staged lines is still good.

but I meant : 

> It's a false positive, because staged lines is still failing and `precise-commits` say it's ok

**Comment by GingerPlusPlus** [comment]
Maybe a good idea would be to edit that message and clean up the discussion after it

**Comment by guillaumearm** [comment]
It's edited.
I think it's fine, the evil is already done.

**Comment by Undistraction** [comment]
@guillaumearm  Stupid question: What is the benefit of just checking staged changes - isn't it adding an element of complexity? Prettier is lightning fast so running it against everything shouldn't be a problem.

**Comment by GingerPlusPlus** [comment]
> What is the benefit of just checking staged changes

Smaller diffs. And being seamless, only the code that is already edited gets formatted.

> It looks like precise-commits makes more sense for a codebase moving slowly over to prettier, but we are there already - all we need to do is make sure new code is formatted.

Valid point. We could go with any [other solution](https://prettier.io/docs/en/precommit.html),

**Comment by Undistraction** [comment]
> Smaller diffs. And being seamless, only the code that is already edited gets formatted.

Both of these are no benefit here because all the code is already formatted. Short of prettier going loco and reformatting random pieces of code at random times, only code that is touched will ever be formatted, so diffs will only cover changed code.

**Comment by guillaumearm** [comment]
@Undistraction : It just faster + I don't like when a script automatically add a new file to my commit (except for release commits, and so on)

There is a good compromise : [pretty-quick](https://github.com/azz/pretty-quick)

> **Use Case**: Great for when you want an entire file formatting on your changed/staged files.

`lint-staged` is great for doing this too.

I totally understand the philosophy but I tried it, it disappointed me and I removed it from my project.
**It's just a feedback**: I think DX is bad with this solution, but it's still good, prettier should be a precommit operation.

**Comment by Undistraction** [comment]
@guillaumearm 

> I don't like when a script automatically add a new file to my commit 

I think this is the best argument for it. We could run prettier without write and exit if any files are touched. That would then prompt the developer to run it themselves and commit as needed. In this respect it would act as a linter without autofix.

**Comment by GingerPlusPlus** [comment]
It looks like it is in general not trivial to fix files in `pre-commit` and do the right thing with partly staged files, `pretty-quick` apparently can't do that too: https://github.com/azz/pretty-quick/issues/6.

Maybe the easiest thing to do would be to just validate all the files, don't try to autofix in `pre-commit`.

Also, if there are files which `prettier would reformat, `prettier -l` prints file names and exits with status code 1.

**Comment by Undistraction** [comment]
@GingerPlusPlus Yes exactly. Just lint without the fix and prevent the commit if needs amending.

**Comment by guillaumearm** [comment]
@GingerPlusPlus : I prefer this solution.

IMHO : 
- precommit : lint staged files only (using lint-staged)
- prepush : `npm run lint && npm run test && npm run build && npm run docs`

**Comment by GingerPlusPlus** [comment]
I don't think `npm run lint` is helpful on `prepush`, if we decide to lint staged on `precommit`.

**Comment by guillaumearm** [comment]
Yes it is.
For example : if you delete a .js file, this may fails the import resolver on another unstaged file, etc...

**Comment by Undistraction** [comment]
Related #97

**Comment by GingerPlusPlus** [comment]
Update:

`lint-staged` works by passing filenames to eslint (at least their Readme says so), which means it checks version of the file in working directory instead of index. Can be solved by using a simple [bash script](https://gist.github.com/GingerPlusPlus/1d4cb7f142aa3f093f4a4c0d19c2acfb) instead.

But...

> Anyway, `npm run + husky + lint-staged + commitlint1 is not about waiting 1 second but 3-4 seconds, I do not like to wait so much. 1 second would be fine. (https://github.com/char0n/ramda-adjunct/issues/386#issuecomment-366728977)

@guillaumearm I have to agree with you here. To a point that I'm myself wondering if any hooks near commiting are worth it.

Especially `pre-commit`, when now that prettier is run from within eslint, which makes my VSCode fix everything on save (it's awesome), and entire project will be linted anyway on `pre-push`...

I'll probably open a PR adding `pre-push` and `commit-msg` hooks. I think I'll add each hook in separate commit, so that it'd be easier to merge it only partially. Might as well throw in `pre-commit`.

**Comment by GingerPlusPlus** [comment]
> prepush : `npm run lint && npm run test && npm run build && npm run docs`

Issues:

1. I think it might be building the project twice, as already mentioned in #402,
2. It probably runs everything on version from working dir instead of from last commit -- someone could fix the issues and forget to commit them, and push wouldn't stop him. Fix suggestion: add `git stash -k && trap 'git stash pop' EXIT` to the beggining of that `&&`-chain.

Also, another idea, we could handle somehow `fixup!` and `squash!` commits. Either by running `git rebase -i --autosquash` without spawning an editor before each push, or by examining commits to be pushed and failing the push if `fixup!` or `squash!` commit was found.
