### ISSUE TITLE
push package-lock.json file

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#382]
Every time I run `npm install`, I need to `rm package-lock.json`

What about adding `/package-lock.json` in the `.gitignore` file ?

By the way, why do not freeze dependencies with a `package-lock.json` ?

**Comment by Undistraction** [comment]
That should be checked in: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by guillaumearm** [comment]
Ok, so new question : why do we not push the `package-lock.json` file ?

**Comment by Undistraction** [comment]
I think that the answer to that is that it _should_ be checked in. Good overview [here](https://medium.com/@Quigley_Ja/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8)

**Comment by char0n** [comment]
Because of greenkeeper. I was trying to setit up but was unsucessful. You're welcome to try. Search for commits regarding this in history

**Comment by Undistraction** [comment]
@char0n What exactly was the problem with greenkeeper? It only updates `package.json` and not `package-lock.json`?

**Comment by char0n** [comment]
Ref https://github.com/char0n/ramda-adjunct/issues/252

It was updating package.json but not the package-lock.json even if the [greenkeeper-lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile) was setup

**Comment by Undistraction** [comment]
[Overview of greenkeeper-lockfile](https://blog.greenkeeper.io/greenkeeper-support-for-lockfiles-9d9c282efcbe)

**Comment by char0n** [comment]
Greenkeeper already updates package-lock.json. We have this file checked-in for some time.
