### ISSUE TITLE
Use commit-msg hook to validate commit message

### ISSUE THREAD

**Issue by GingerPlusPlus** [char0n/ramda-adjunct#386]
While we're thinking about automating some stuff using git hooks, an idea:

Use [`commit-msg` hook](https://git-scm.com/docs/githooks#_commit_msg) to validate commit message according to [Commit Message Guidelines](https://github.com/char0n/ramda-adjunct/blob/master/CONTRIBUTING.md#-commit-message-guidelines). and drop the link if validation fails, and perhaps explain the problem.

Even validating just the first line would be helpful, as "typing" and "scoping" commits is not the standard practice.

**Comment by guillaumearm** [comment]
There is [commitlint](https://github.com/marionebl/commitlint), I test it on a personal project coupled with [lint-staged](https://github.com/okonet/lint-staged) but I removed both because I hate waiting when I commit. CI are here for doing that kinds of stuffs.

**Comment by GingerPlusPlus** [comment]
IMO having to wait a second is better than hearing on your PR about commit convention, and you could omit the check if for example an environmental variable is set if you hate waiting that much.

**Comment by guillaumearm** [comment]
It make sense, but I prefer a prepush hook for doing this.

Anyway, `npm run + husky + lint-staged + commitlint` is not about waiting 1 second but 3-4 seconds, I do not like to wait so much. 1 second would be fine.

@char0n, @Undistraction, anyone else ?
any advices ?

**Comment by GingerPlusPlus** [comment]
`prepush` is kinda late, you'd have to `rebase -i` to fix, `commit-msg` lets you know as soon as you screw up.

Also, `commitlint` would run after the commit message is typed, which is later than `npm run + husky + lint-staged`, which'd run before editor opens (at least if you use git cli).

**Comment by Undistraction** [comment]
> prepush is kinda late, you'd have to rebase -i to fix, commit-msg lets you know as soon as you screw up.

This is exactly why I like running things before commit. Less hassles fixing bad commits (or adding new distracting one for fixes).

**Comment by guillaumearm** [comment]
It seems to make sense, if @char0n agreed, I think we can go for it.

Just for explain, I remove commitlint from my project because I use commitizen to make commits and I'm alone on this project for now.

**Comment by char0n** [comment]
Please describe the proposed solution, example usage, provide links and mention some cons ans props. Thank you
