### ISSUE TITLE
RA.capitalize

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#389]
Ref #38

**Comment by guillaumearm** [comment]
Implementation idea : 
```js
const capitalize = R.compose(R.join(''), R.over(R.lensIndex(0), R.toUpper))
```

**Comment by Undistraction** [comment]
Personally I think this is a slippery slope. We then need to add toUppercase, toTitlecase etc which don't really feel like they should be part of this lib.

However I do think it would be good to have a separate lib for string formatting functions.

**Comment by guillaumearm** [comment]
Hum, it's true, there are no `String` function in `ramda-adjunct` (expect for `isString` and so on, but it's `Type`).

@char0n : What about making a `ramda-adjunct-string` in this repo ?

**Comment by char0n** [comment]
Well, IMHO we should have them, it's one of the reason why this library exists to provide string manipulations utils. ramda already contains toLower and toUpper so I don't see why not continuing the this approach and having capitalize, kebabCase, camelCase, snakeCase, etc... I have to use lodash because we now don't have them in RA.

**Comment by Undistraction** [comment]
In that case shall we create a new issue to discuss string formatting functions. I can definitely see the advantage from a user's perspective - theses things are sometimes quite awkward to write and get heavy use.

**Comment by Undistraction** [comment]
In fact is it worth discussing some kind of separation of functions into groups - if only for discoverability.

**Comment by guillaumearm** [comment]
@char0n : it seems to makes sense too.
my goal is to remove lodash from my projects, so agreed.

@Undistraction : There are already groups in ramda-adjunct documentation : `Type` / `List` / `Logic` / `Function`, what do you mean ?

**Comment by Undistraction** [comment]
@guillaumearm Sorry, I was vague. I was considering some kind of way of partitioning the library in terms of how it is used, but I think what we have already is probably fine.

**Comment by GingerPlusPlus** [comment]
Alternative implementation (simpler IMO): `R.replace(/^./, R.toUpper)`

https://stackoverflow.com/questions/40011725/point-free-style-capitalize-function-with-ramda

**Comment by GingerPlusPlus** [comment]
If you want to go for lenses, implementation becomes much cleaner with `lensSlice` (#395):

```js
capitalize = R.over(lensSlice(0, 1), R.toUpper)
capitalize('asdF') //=> "AsdF"
```

**Comment by char0n** [comment]
Closing this one for now.
