### ISSUE TITLE
RA.inRange

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#393]
As discussed in #324

Signature
```
Number -> Number -> Number -> Boolean
```

Possible Implementation
```
const inRange = curry((low, high, v) =>
  compose(apply(useWith(both, [flip(gte), flip(lte)])), sort(gt), list)(
    low,
    high
  )(v)
);
```
[Codepen](https://codepen.io/Pedr/pen/PQRMWL)

Does it need to do anything else?

**Comment by char0n** [comment]
It needs to conform to some additional criteria:
 - start is **inclusive**
 - end is **exclusive**
 - if **start is greater than end** the params are **swapped** to support negative ranges

**Comment by Undistraction** [comment]
First two are already covered. I'll add the third.

**Comment by Undistraction** [comment]
@char0n Updated with version that covers point three:
> if start is greater than end the params are swapped to support negative ranges

**Comment by char0n** [comment]
LGTM

**Comment by GingerPlusPlus** [comment]
> if start is greater than end the params are swapped to support negative ranges

I don't think this is essential, after all, you can do `inRange(__, max)`.

Ramda actually [treats it as an error](https://github.com/ramda/ramda/blob/3dfce5ee44d287b8a6c0460cf57fb9d5a2f468dc/source/clamp.js#L24-L26).

**Comment by Undistraction** [comment]
I have to say, I kind of agree. I think it's a little unexpected. I know it's convenient, but if you aren't expecting it it could mask a problem.

**Comment by char0n** [comment]
Agree, I am just used to it from lodash. But let's comply with ramda on this.

**Comment by GingerPlusPlus** [comment]
Without all the swapping, the function becomes much simpler:

```js
const inRange = R.curry((min, max, val) => {
  if (R.ge(min, max)) {
    throw something
  }
  return R.lte(min, val) && R.gt(val, max)
})
```

**Comment by guillaumearm** [comment]
Woops, this is impure.

**Comment by GingerPlusPlus** [comment]
@guillaumearm how is it impure?

**Comment by guillaumearm** [comment]
@GingerPlusPlus : because it throws.

**Comment by guillaumearm** [comment]
@GingerPlusPlus : Well, it's predictable, so I think it's fine.
I hadn't read your previous posts yet about `R.clamp`, sorry for the inconvenience.

**Comment by Undistraction** [comment]
Are we OK with never being able to include `Number.POSITIVE_INFINITY` in a range? Because the upper value is exclusive.

**Comment by guillaumearm** [comment]
I don't know, IMHO, `Infinity` is not really an upper bound : 
```js
Infinity + 1 === Infinity
```

But conceptually you right, so should we support negative ranges ?

**Comment by Undistraction** [comment]
You could look at it like this:

If I'm trying to check if a value is in the range of `n` to `Number.POSITIVE_INFINITY` I'm effectively doing `R.flip(R.gt(n))` so I should use that instead. However I'm not sure if that is a good enough argument.
