### ISSUE TITLE
isEmptyString & isNonEmptyString

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#40]

**Comment by char0n** [comment]
@tycho01 need some collaboration over this. Does this even make sense. Thought I have one production use case in my current project.

```javascript
const description = 'user input';
if (isNotNull(description) && isNotEmptyString(description)) { return description }
```

**Comment by tycho01** [comment]
Sounds like just `if (description)` covers this use-case? That said, I think this whole function-based approach primarily shines if you're doing composition/`map`. That is, without need for a function one could technically be shorter off just writing `description != ''` for this.

But yeah, why not? :)

So I've personally tended toward higher abstraction, and wanted a slightly different truthy/falsy check for arrays/objects, here's what I've been using for that.
```
export let falsy: (v: any) => boolean = R.either(R.isEmpty, R.not);
export let truthy: (v: any) => boolean = R.complement(falsy); // differs from JS's 'truthy': []/{} -> false.
```
For other cases, in the case one would prefer higher abstraction, where you want a function version of the built-in truthy/falsy check, one could also use the built-in `Boolean` (/ `R.identity`) or `R.not` for positive/negative checks respectively.

**Comment by char0n** [comment]
> Sounds like just if (description) covers this use-case? That said, I think this whole function-based 
> approach primarily shines if you're doing composition/map. That is, without need for a function one 
> could technically be shorter off just writing description != '' for this.

`if (description)` would cover the usecase, but we have a airbnb codestyle where everything should be checked explicitly except for booleans. As for imperative over declarative system here, I like the first version better, I can read it faster and I know instantly what is going on there.

```javascript
if (isNotNull(description) && isNotEmptyString(description)) { return description }`
if (description !== null && description !== '') { return description }
```

Also I like you falsy, truhy approach ;]

**Comment by tycho01** [comment]
Yeah. I wish the built-in checks used this logic for truthy/falsy; it could make things a bit more terse when checking objects/arrays...

**Comment by char0n** [comment]
Back to the original problem...it seems that isNotEmptyString doesn't make sense alone. 

```javascript
if (isString(description) && isNotEmptyString(description)) { return description }`
```

What makes more sense is

```javascript
isNotEmptyString = allPass([isString, complement(isEmptyString)]);
```

**Comment by tycho01** [comment]
`allPass` could be `both` for just two, for `complement(isEmptyString)` just `Boolean` could do, but yeah, whatevers. With composition like that you'll manage to avoid boilerplate, yeah.
P.S. if it includes `isString` I'd name it `isNonEmptyString`. :)

**Comment by char0n** [comment]
```javascript
isNotEmptyString = both(isString, );

isNotEmptyString(null) -> false
isNotEmptyString('test') -> true
isNotEmptyString(udefined) -> false
isNotEmptyString('') -> false
```

Ok I guess it make sense now, thanks.

**Comment by char0n** [comment]
Conclusion: Implement two new type functions

```javascript
isEmptyString
isNonEmptyString
```

@tycho01 thanks for all your input.

**Comment by tycho01** [comment]
Sure. :)

**Comment by char0n** [comment]
@guillaumearm wanna take this one also ?

**Comment by guillaumearm** [comment]
Absolutely :-D
@char0n : I think you can assign this issue to v2.4.0, sorry for the late response, hard week for me ><

**Comment by guillaumearm** [comment]
I'm on it ;-)

**Comment by guillaumearm** [comment]
I have an issue with the proposed `isEmptyString` implementation above : 
```js
const isEmptyString = equals('');
```

@char0n  : Should  `isEmptyString(new String(''))` return true ?

**Comment by char0n** [comment]
IMHO it should return false for `isEmptyString(new String(''))`. It is the case that in JavaScript `'' !== new String('')` so I would not worry about handling this usecase. They're just not the same.

Regarding the composition, I understand the consistency argument, but again in JavaScript it is case that  `'' === ''` but `{} !== {}` and `[] !== []`. I don't think complex composition like `both(isString, isEmpty)` is needed for this usecase and simple equation should do. It is simple and quick, and I just like these two attributes. We should always strive to use the simplest workable solution. 

If you look at the source of `isEmpty`, it calls `empty` on argument (monoid) and then doing the comparisong using the equal...so basically it is doing the `equals('', arg)` which is what I am proposing.

**Comment by guillaumearm** [comment]
OK, it sounds good, but i have some trouble in `isNonEmptyString` tests because of `isEmpty` : 
```js
> R.isEmpty(new String('abc')) // => false
> R.isEmpty(new String()) // => false
```

so there is a problem here : 
```js
eq(RA.isNonEmptyString(new String('abc')), false); // test throw
```

**Comment by guillaumearm** [comment]
We can get around using a kind of `isPlainString` internal function in isNonEmptyString implementation.

```js
const isPlainString = x => typeof x === 'string'
```

**Comment by char0n** [comment]
What about something like this one ?
```js
const isNonEmptyString = R.allPass([RA.isString, RA.isNotObj, RA.isNotEmpty]);

**Comment by guillaumearm** [comment]
I don't know. 
Semantically speaking, I prefer your solution.

But according to you, which one is fastest ? 

```js
const isNonEmptyString = R.allPass([RA.isString, RA.isNotObj, RA.isNotEmpty]);
```
or
```js
const isPlainString = x => typeof x === 'string';
const isNonEmptyString = both(isPlainString, isNotEmpty);
```

Need a bench ?

**Comment by char0n** [comment]
I'd prefer also the first one even though it is going to be slower. In the context of Equational Reasoning I prefer to compose new parts from the parts that are already available rather than create new add hoc parts just to satisfy the speed property. My main argument in previous comment was not about speed it self but the simplicity. Speed is secondary in this case. `both(isString, isNotEmpty)` can be translated directly into `equals('')` so we are basically creating a fushion showcut here because we understand the behavior of both and we know that they equal.

**Comment by guillaumearm** [comment]
Ok, so I go for the first solution, did  you want I create 2 PRs ?

**Comment by char0n** [comment]
yup thanks
