### ISSUE TITLE
RA.padStart, RA.padEnd?

### ISSUE THREAD

**Issue by GingerPlusPlus** [char0n/ramda-adjunct#400]
#391 

JS already has `String.prototype.padStart` and `String.prototype.padEnd`, it's only a matter of exposing a functional interface to them.

1. If we used `R.invoker` for that, they'd have signature `targetLength -> padString -> stringToPad -> paddedString`. I feel like a better signature would be `padString -> targetLength -> stringToPad -> paddedString`.

2. How would we name them? 
    - `padStart` and `padEnd`?
    - `leftPad` and `rightPad`?
    - `padLeft` and `padRight`?

    My preferred choice would probably be `padStart` and `padEnd`, for consistency with JS.

**Comment by guillaumearm** [comment]
1. I'm ok with the flipped version [[REPL example]](http://ramdajs.com/repl/#?const%20padStart%20%3D%20R.flip%28R.invoker%282%2C%20%27padStart%27%29%29%3B%0A%0ApadStart%28%27%3D%27%29%2830%29%28%27%3D%3E%20Hello%20World%27%29)

2. I have a preference for `leftPad` in reference to [left-pad npm package](https://www.npmjs.com/package/left-pad), but I follow you on `padStart` and `padEnd`.

**Comment by Undistraction** [comment]
+1 for `padStart` and `padEnd` (which is also what lodash uses). 

We will also need a `pad`.

Do we also want functions that are like pad but *always add the specified padding* rather than only when there is a deficit between `targetLength` an `stringToPad` length? I think this would be useful. I suggested `wrap`, but `wrapStart` and `wrapEnd` don't make sense as names.

**Comment by char0n** [comment]
+1 for padStart and padEnd

> Do we also want functions that are like pad but always add the specified padding rather than only when there is a deficit between targetLength an stringToPad length? I think this would be useful. I suggested wrap, but wrapStart and wrapEnd don't make sense as names.

We add them later when there is need for them

**Comment by GingerPlusPlus** [comment]
> Do we also want functions that are like pad but __always add the specified padding__

> `wrapStart` and `wrapEnd`

@Undistraction: That sounds like `R.concat` to me.

**Comment by GingerPlusPlus** [comment]
Just saying, `String.prototype.padStart` and `String.prototype.padEnd` [are available since Node 8](http://node.green/#ES2017-features-String-padding)

**Comment by guillaumearm** [comment]
> @Undistraction : That sounds like `R.concat` to me.


@GingerPlusPlus : 
All the idea of `wrap` is to be used into pipelines.

e.g.

```js
compose(
  wrap('[', ']'),
  toUpper,
  prop('name'),
)({ name: 'guillaumearm' }) // => [GUILLAUMEARM]
```

**Comment by GingerPlusPlus** [comment]
I said, `wrapStart` and `wrapEnd` sound like `R.concat`, I said nothing about `wrap`.

**Comment by guillaumearm** [comment]
Woops, sorry, agreed.

**Comment by Undistraction** [comment]
@GingerPlusPlus I think it has merits when using configuration for example. The mechanics of converting these two vars into the correct string are hidden away. 

```
const {
  indentChar,
  indentCharCount,
} = formattingConfig

const indentLeft = wrapLeft(indentChar, indentCharCount) 
```

**Comment by GingerPlusPlus** [comment]
@Undistraction 
```js
const wrapLeft = R.concat
const wrapRight = RA.concatRight
```

it's just an alias, I don't think we need it.

**Comment by Undistraction** [comment]
@GingerPlusPlus I think you are getting a little confused. Why would you alias a function with the signature `string  -> number -> string -> string` to a function with the signature `string -> string -> string`?

**Comment by GingerPlusPlus** [comment]
oh wait

**Comment by GingerPlusPlus** [comment]
edited

**Comment by Undistraction** [comment]
So explain to me how you'd handle the example I outlined above using just concat.

**Comment by GingerPlusPlus** [comment]
```js
const indentLeft = R.concat(indentChar.repeat(indentCharCount))
```

**Comment by Undistraction** [comment]
So it isn't just concat then is it?

**Comment by GingerPlusPlus** [comment]
Right.

Still, `wrapLeft` and `wrapRight` are terrible names then, they look like they're related to `wrap`, which they aren't (except that both do `concat` internally at least once, I guess).

**Comment by GingerPlusPlus** [comment]
Also, I'd ask to add a feature label to this issue.

And, I'd suggest making sure what `wrapLeft` and `wrapRight` should do, try to think of a better name, and open a new issue @Undistraction.

**Comment by GingerPlusPlus** [comment]
> Just saying, String.prototype.padStart and String.prototype.padEnd are available since Node 8

What do we do? Implement those, mention that it relies on those methods in docs, and disable tests if they're not found?

**Comment by char0n** [comment]
Nope, we use methods from String.prototype if present. If not present we provide polyfill.

Ref https://github.com/char0n/ramda-adjunct/blob/8ae9b5fa961217101c70a4d25fcdf6367022d754/src/isFinite.js#L14

**Comment by GingerPlusPlus** [comment]
1. I started implementing `padStart` and `padEnd`, please assign me. And please label this issue.

2. Should a function with signature `repeat(s: string, n: number)` be considered polyfill of `String.prototype.repeat` and live in polyfills, despite having different signature, or should it be considered just an internal function?

**Comment by char0n** [comment]
> Should a function with signature repeat(s: string, n: number) be considered polyfill of String.prototype.repeat and live in polyfills, despite having different signature, or should it be considered just an internal function?

Implement a polyfill using this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat as `src/internal/polyfills/String.repeat.js`. Don't modify the String.prototype just export this function from the file. Then we have to create a public util called `repeatStr` with alias of `repeatString` and use mechanism like [this](https://github.com/char0n/ramda-adjunct/blob/8ae9b5fa961217101c70a4d25fcdf6367022d754/src/isFinite.js#L28) to make it all work together.

After we have `repeatStr` I'd go for `padStart` and `padEnd`.

**Comment by GingerPlusPlus** [comment]
> Implement a polyfill using this

I went a different approach, I created a `repeat(s: string, n: number)` function which calls `s.repeat(n)` if it's defined, and uses Ramda and RA if not. So, I guess it means it's an internal method. Similar story with `padStart` and `padEnd`, try to dispatch to the method, and uses internal function, `createPadding` if it's not defined.

Not `const padEnd = String.prototype.padEnd ? R.invoker(...) : padEnd` polyfill, because it would work on non-string values in environments having native `padEnd`, and perhaps it wouldn't on environments that don't.

> I'd go for `padStart` and `padEnd`.

I'm on it already. I have everything defined, documenting, typing and testing left.

**Comment by GingerPlusPlus** [comment]
> Resolving this issue means adding 3 new utils

2 internal functions. `repeat` and `createPadding`.

**Comment by char0n** [comment]
@GingerPlusPlus I will still require your PR to conform to the proposed solution in https://github.com/char0n/ramda-adjunct/issues/400#issuecomment-368325029

If we're gonna by be invoking String.prototype.repeat our polyfill must adhere to ECMASCRIPT spec and have exactly the same behavior.

**Comment by GingerPlusPlus** [comment]
> our polyfill must adhere to ECMASCRIPT spec and have exactly the same behavior.

I think it'd be easier to discuss if you could see the code. Let's return to the topic after I PR.

**Comment by Undistraction** [comment]
@char0n Lets park this for the moment until we have a better idea of which string functions we are going to include. We can get a better feel for shared utilities then.

**Comment by guillaumearm** [comment]
@Undistraction : Agreed, maybe the RA string update will be for `v2.7.0` ? 😆 

@GingerPlusPlus : In fact, your polyfill is a [ponyfill](https://github.com/sindresorhus/ponyfill)

@char0n : 

> our polyfill must adhere to ECMASCRIPT spec and have exactly the same behavior.

Exactly, any resources on this ? 

Let's move on #418 to discuss about implementation.

**Comment by GingerPlusPlus** [comment]
> There is too much code

What do you mean?

> without signatures

There are [typings](https://github.com/char0n/ramda-adjunct/pull/418/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8). `@sig` in JSDoc is also present.

> use native ones when present and ponyfills when not present

That's what it does.

Is your issue with the fact that they behave differently than native functions or official polyfills in some edge cases?

**Comment by GingerPlusPlus** [comment]
I analyzed the MDN's polyfills and improved my ponyfill to handle 2 edge cases which, unlike MDN's and native methods, were throwing an error.

Now the only differences I'm aware of occur when you pass wrong type.

Note, Github didn't add those 2 commits to the (closed) pull request.

**Comment by char0n** [comment]
Closing this in favor of #1102, #1103, #1104, #1105
