### ISSUE TITLE
Commented test in concatAll

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#409]
One test in `test/concatAll.js` is failing so it is currently commented. Needs more investigation.

**Comment by GingerPlusPlus** [comment]
https://github.com/char0n/ramda-adjunct/blob/341f3f1797e75c469fd7e02e4faa457defeb8d85/test/concatAll.js#L32-L39

This test is about concatanating string and array, recent version of Ramda throw when you try to do that, but it apparently wasn't always the case.

I'd remove the test and leave that up to Ramda to test.

Or we could consider dropping support for older Ramda, and ancient Node in next major release.

**Comment by char0n** [comment]
@GingerPlusPlus thanks for explanation. I've provided a PR that solves the issue.
