### ISSUE TITLE
Investigate use of sideEffects:false in package.json regarding Webpack

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#414]
From [Webpack 4 beta release docs](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2):

> We introduced support for `sideEffects: false` in package.json. When this field is added, it signals to webpack that there are no sideEffects in the library being consumed. This means that webpack can safely eliminate any used re-exports from your code.

If I'm reading this right, this is make's @char0n's decision to keep RA effect free all the more important and we should investigate and ensure RA works correctly with / takes full advantage of this new Webpack feature.

We currently [have](https://github.com/char0n/ramda-adjunct/blob/eb1fbcd85b4bf05eca9e64a66c16a743c5dfe0ee/package.json#L29) `sideEffects: false` enabled in our `package.json` so I think it's a matter of ensuring this (in combination with our export structure) achieves the expected when used with Webpack v4.

See discussion regarding lodash's use of `sideEffects: false` [here](https://github.com/webpack/webpack/issues/1750)

**Comment by guillaumearm** [comment]
If we choose rollup (#318) instead of webpack, please take a look to `treeshake.pureExternalModules` and `treeshake.propertyReadSideEffects` options.

Ref : [RollupJS guide, danger-zone part](https://rollupjs.org/guide/en#danger-zone)

**Comment by Undistraction** [comment]
@guillaumearm This isn't related to our bundler. It's related to a flag we can set in our `package.js` which will be used by other bundlers (Webpack) that are consuming our package. It tells them that our package is side-effects free, so the bundler can be more aggressive about tree-shaking. It would probably make more sense to add your note to #318

**Comment by Undistraction** [comment]
Ramda are [going to enable the flag](https://github.com/ramda/ramda/issues/2482).

**Comment by guillaumearm** [comment]
@Undistraction : Yes, this is a great point, if I understood correctly, the `sideEffects: false` will be useful for RA user that bundle his app, and not specially for us ?

**Comment by Undistraction** [comment]
@guillaumearm Yes. Exactly. It means that their final bundle is potentially much smaller when using RA.

**Comment by char0n** [comment]
> I'm not 100% that this covers what Webpack considers side-effects, but if so, I guess the only place where we might have issues is in the use of Polyfills, but I think that is just for testing @char0n?

Can you collaborate on this ? We have some internal polyfills which should be side effects free too. Then we are using promise polyfill for phantomjs but that's about it.

> Yes, this is a great point, if I understood correctly, the sideEffects: false will be useful for RA user that bundle his app, and not specially for us ?

Yes, basically we are supporting this already, because of the way RA is written.

There are some exceptions like [this](https://github.com/char0n/ramda-adjunct/blob/a3109fc1020c6f4a8686d032cb7d539a230af258/src/isGeneratorFunction.js#L4) but we are still not modifying nothing external, just reading from it (future detection).

Is there something actionable in this issue or do we already understand what it means to have `sideEffect: false` in package.json ?

**Comment by Undistraction** [comment]
> Is there something actionable in this issue or do we already understand what it means to have sideEffect: false in package.json ?

I think I understand this enough to know we should do it. My only concern was the polyfills, but I think we should be OK. Is the promise pollyfill only used in tests?

**Comment by char0n** [comment]
> I think I understand this enough to know we should do it. My only concern was the polyfills, but I think we should be OK. Is the promise pollyfill only used in tests?

Yes only in tests.

> In terms of action, I'll try and dig some more as I'd like to understand edge-cases a little better.
Pls document your research so that we can reference it in future.

**Comment by Undistraction** [comment]
@char0n [Here](https://stackoverflow.com/questions/49160752/what-does-webpack-4-expect-from-a-package-with-sideeffects-false) is a very comprehensive answer to a question I posted on SO by one of the Webpack team. I think we should be good to add the flag for the next release.  I suggest you and @guillaumearm have a read and see if you agree.

**Comment by Undistraction** [comment]
Well after all this, it looks like this was done way back in November in #223 so I'm going to close this out.
