### ISSUE TITLE
RA as a monorepo

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#419]
### The idea
The idea is to consider ramda-adjunct as a monorepo, and add additional packages around it : 
- eslint-plugin-ramda-adjunct
- ramda-adjunct-monads
- ramda-adjunct-effects
- and so on...

Purpose behind this is to make a large community around functional programming in javascript, enforce practices, write tools, share concepts.

I have create a proposal on ramda repository to start the idea : https://github.com/ramda/ramda/issues/2443

By the way, I think this is the `ramda` job.
`ramda` is the most famous fp library in js, this should be their responsabilities (IMHO).

### Discussions
We already discussed about this in #415 and #380, I think we should regroup here all related issues and PRs.

### Big deal

This discussion is a big one, in the first place, I would to say there are no breaking changes.
All of this is not about splitting the `ramda-adjunct` library, but adding more stuffs around ramda that cannot be in `ramda-adjunct`.

So no need to consider a v3 of ramda-adjunct.

**Comment by Undistraction** [comment]
I do like the idea, but as you have already mentioned, I think the key is that there is minimal/no disruption for the user. I think it would be great if Ramda took the lead and architected a more clearly defined set of libs around a monorepo, but I doubt that will happen any time soon. It would also involve a lot of work unifying libs etc. 

So the questions here are:

1. Do we see any benefit to multiple repos - I like the idea of an effects lib that lives under the ramda-adjunct banner (without being part of the main lib). I also think a monad lib makes sense. Are there any other repos that we might need or could/should spin out of the current one? To some degree we need to think a few steps ahead - if we keep adding functions to RA, will it at some point become too large - will it make sense to split it up in the near future anyway?

2. What are the pros / cons from a user's perspective? Are there potential performance gains or does tree-shaking mean this is already covered.

3. What is involved in the process of moving to a monorepo (I'm assuming Lerna)? How would this effect build / publish / deployment / docs etc.

As I said, I like the idea, but I'm wary of how much of a cost there will be in terms of additional work. I think there is potentially a way of doing this internally first, then publicly later which might reduce the amount of work needed in one hit - we could switch to using internal packages in a monorepo structure, then expose / promote these later.

**Comment by guillaumearm** [comment]
- 1. We should **define a precise scope for RA**, we can't end up with a ramda-adjunct-list, ramda-adjunt-predicates, ramda-adjunct-adjunct, this scope need to be mentionned somewhere (RA README.md). Anyway, I think discussing about RA which will become too large is a good point, Do we need a dedicated issue for this ?

- 2. I think there is **no performance gains** for user, **just more stuffs**.
  But, a monorepo allow us to have a **bigger space to do things**, we can imagine add a `ramda-adjunct-cookbook` in and write a large sets of examples with R and RA. Result  : users have **more contents**

- 3. I don't sure yet, I have no experience in monorepo, I would to use this architecture on another repo but I don't have any time for this (for now).


> I think there is potentially a way of doing this internally first, then publicly later which might reduce the amount of work needed in one hit.

Totally agree with that 👍, we should proceed step by step, so we can rollback if we want to.

**Comment by Undistraction** [comment]
In our Gitter discussion a while back @char0n said:

> I am using monorepos in work, so I am familiar with the topic. Regarding ramda + ramda-adjunct monorepo, it's more a political issue at this point than technical one. If ramda-adjunct is merged into ramda organization we may loose absolute control over this repo, but I am not against it the right time comes. Regarding the monorepo (which already assumes merge into ramda org), there are couple of things that needs to be solved and realized first
> 
> 1.) all the projects are using the same repo issues
> 
> Every project has different culture, work morale and standards. You will have issues mixed from multiple project in one repo. This may have some additional implications. I will make a core commiter in some feature of ramda-adjunct, but guys from ramda don't agree with this, because it means access to their code too. So I think it is not that simple as it may seem.
> 
> 2.) no support on CI
> 
> It's pretty hard to get CI working on monorepo setup. I've dealt with that and solutions are not pretty nice
> 
> I also see the benefits, but IMHO the disadvantages are greater than the advantages. Ramda is not a company like Facebook with coherent structure and culture.

**Comment by char0n** [comment]
I'm closing this for now. As we have no need, nor plans for other related RA stuff I'm putting this onhold. Thank you all for sharing your opinions here!
