### ISSUE TITLE
Commit-lint Unhelpful Error Messages

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#433]
I'm getting failing commits with the new commit-lint setup when I can't see anything wrong with the message:

# Message 
```
docs(isPositive/Negative): Clarify zero exclusion 

Clarify that zero isn’t included in isPositive and isNegative predicates.
```

# Error

```
husky > npm run -s precommit (node v9.3.0)

husky > npm run -s commitmsg (node v9.3.0)

⧗   input: docs(isPositive/Negative): Clarify zero exclusion
✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings

husky > commit-msg hook failed (add --no-verify to bypass)
```

**Comment by char0n** [comment]
```
docs(isPositive/Negative): Clarify zero exclusion 
```
I thinks that subject cannot contain special chars and first character after `:` should be lowercase.

**Comment by Undistraction** [comment]
Ah. Of course. Was working late.

**Comment by Undistraction** [comment]
This seems to be working fine now (or at least I seem to be formatting the messages properly). I'll close for now and reopen if I encounter it again.
