### ISSUE TITLE
compactList / compactArgs

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#442]
Convert function args into a compact list:

```
const compactList = compose(compact, list)
```

Useful in converging functions where you want a list at the other end, but some functions might return undefined.

Maybe a little too specific.

**Comment by char0n** [comment]
IMHO hard to find a usecase for it. It's basically a `compactArgs` as I understand it, but it will change the positions of the args by removing the falsy values which may render it impossible to deterministic-ally apply to another function.

**Comment by Undistraction** [comment]
Yep. Fair enough. I have a situation where I have a function that accepts only an arbitrary number of `...args` and this makes some kind of sense in that situation, but I struggle to see a use outside of this particular situation.

**Comment by char0n** [comment]
Yeah it's hard to use for general usecases, but nice idea anyway
