### ISSUE TITLE
import RA default export doest not works

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#456]
default export seems to not works like `ramda` does.

```js
import RA from 'ramda-adjunct' // RA is undefined
import R from 'ramda' // R is OK

import * as RA from 'ramda-adjunct' // RA is OK
import * as R from 'ramda' // R is OK
```

I don't understand why, maybe need to investigate https://github.com/ramda/ramda/blob/master/.babelrc

**Comment by guillaumearm** [comment]
I have made some investigations on ramda : 

```js
import R from 'ramda' // use "main" field (commonjs)
import * as R from 'ramda' // use "main" field (commonjs)
```

It seems like Ramda have a bug and never really expose es module.
In my case, "module" field is ignored, but "jsnext:main" works fine.

```js
import RA from 'ramda-adjunct' // use "jsnext:main" field (es)
import * as RA from 'ramda-adjunct' // use "jsnext:main" field (es)
```

I can't find a case where "module" is used, I test this with babel 6 and this configuration : 


```json
{
  "ignore": [
    "node_modules/**"
  ],
  "presets": [
    ["es2015"],
    ["stage-0"]
  ]
}

```

**Comment by Andarist** [comment]
How do u consume `ramda-adjunct`? node? webpack? rollup? other?

**Comment by guillaumearm** [comment]
In my case I've just node, so `import` are replaces by `require`, commonJs is used, everything seems normal.

> You are not supposed to be able to import `default` from RA, it's a namespace library and import * as RA is correct for this use case.

You right, but I have to know why `import R from 'ramda'` is working while `import RA from 'ramda-adjunct'` doesn't

**Comment by Andarist** [comment]
Might be because `ramda` uses custom transform from esm to cjs - https://github.com/ramda/ramda/blob/9e5107e6e021b35179401eb719283cd835687d51/scripts/transpile/esm-to-cjs.js . This is just a guess though - you should be able to debug this easily by inspecting transformed outputs of both.

**Comment by Andarist** [comment]
@quangv You are not supposed to be able to import default from RA, it's a namespace library and `import * as RA` is correct for this use case.

**Comment by char0n** [comment]
Yes the current behavior `* as RA` is due to the tree shaking. We can add additional mechanism that supports `import RA from 'ramda-adjunct'` but now we don't support. I'll fix the documentation to reflect that.

**Comment by Andarist** [comment]
@guillaumearm `ramda` does not export default, so you are already consistent 😉

**Comment by guillaumearm** [comment]
@Andarist : I mean it's work when you import ramda as default.

**Comment by Andarist** [comment]
It really shouldnt until ur setup is in some way not-standard.

**Comment by Undistraction** [comment]
@Andarist The problem is that someone used to using Ramda like this:

```
import R from 'ramda'

R.length('abc') //=> 3
```

Will expect Ramda Adjunct to function in the same way. However using ES6 imports the following will not work:

```
import RA from 'ramda-adjunct' 

RA.isBoolean('abc') // => RA is undefined
```

**Comment by Andarist** [comment]
Since `ramda@0.25` it's not possible to import ramda as default, see [upgrade guide](https://github.com/ramda/ramda/issues/2319)

**Comment by Undistraction** [comment]
@Andarist Thanks for the link. In that case, as long as we aren't doing it anywhere in the docs or examples, I think we can safely close this issue.

**Comment by guillaumearm** [comment]
Like @Andarist said : 
> You are not supposed to be able to import default from RA, it's a namespace library.

So now that consistency issues between `ramda` and `ramda-adjunct` are fixed, it's ok to me.
