### ISSUE TITLE
propsToList

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#467]
Create a list using selected props from an object. Quite possibly this exists somewhere already but I haven't found it. 

```
const propsToList = compose(converge(list), map(prop))

const o = { a 1, b: 2 }
propsToList(['a', 'b'])(o) // [1, 2]
```

Useful paired with `apply`.

**Comment by guillaumearm** [comment]
I'm not sure to understand your example, what is **[a, b]** ?

**Comment by guillaumearm** [comment]
Yeah, I suspected it, but I wasn't sure.

This is a nice idea, I like it.

Why not a `pathsToList` function ?

```js
const o = {
  a: { b: 1 },
  c: { d: 2 },
};
pathsToList([['a', 'b'], ['c', 'd']], o); // [1, 2]
```

**Comment by guillaumearm** [comment]
Wait a minute, this is definitively [R.props](http://ramdajs.com/docs/#props)

**Comment by Undistraction** [comment]
Yes it is. I knew it was there somewhere. Thanks and sorry for the distraction.
