### ISSUE TITLE
paths

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#468]
Like [R.props](http://ramdajs.com/docs/#props) but using [R.path](http://ramdajs.com/docs/#path)

```js
const paths = R.uncurryN(2)(
  R.compose(R.converge(RA.list), R.map(R.path))
);

const o = {
  a: { b: 1 },
  c: { d: 2 },
};
paths([['a', 'b'], ['c', 'd']], o); // [1, 2]
```

[REPL](http://ramdajs.com/repl/#?const%20list%20%3D%20unapply%28identity%29%0A%0Aconst%20paths%20%3D%20uncurryN%282%29%28compose%28converge%28list%29%2C%20map%28path%29%29%29%3B%0A%0Aconst%20o%20%3D%20%7B%0A%20%20a%3A%20%7B%20b%3A%201%20%7D%2C%0A%20%20c%3A%20%7B%20d%3A%202%20%7D%2C%0A%7D%3B%0A%0Apaths%28%5B%5B%27a%27%2C%20%27b%27%5D%2C%20%5B%27c%27%2C%20%27d%27%5D%5D%2C%20o%29%3B)

Related to #467.

**Comment by guillaumearm** [comment]
woops, we already have [RA.paths](https://char0n.github.io/ramda-adjunct/2.5.0/RA.html#.paths)

**Comment by char0n** [comment]
Yep already needed this one ;]
