### ISSUE TITLE
Have an eslint-plugin-ramda-adjunct repository

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#469]
IMHO, there are a lot of eslint rules we can imagine for `ramda-adjunct`.

@char0n  : Are you ok to create this repo ?

**edit**: I can take a little time to make this project up.

This issue can be related to #419.

**Comment by Undistraction** [comment]
What kind of rules are you imagining?

**Comment by guillaumearm** [comment]
`prefer-is-string`
```js
RA.isString
// insteadOf
R.is(String)
```

`prefer-compact`
```js
RA.compact
// instead of
R.filter(R.identity)
// or
R.reject(RA.isFalsy)
// or
R.filter(RA.isTruthy)
```

and so on...

**Comment by guillaumearm** [comment]
Just looking the ramda-adjunct documentation, you can deduce a lot of simple rules.

an another example:


`prefer-is-not-nil`
```js
RA.isNotNil
// instead of
R.complement(R.isNil)
// or
R.compose(..., R.not, R.isNil, ...)
// or
R.pipe(..., R.isNil, not, ...)
```

**Comment by Undistraction** [comment]
I definitely like this idea, but potentially a lot of work.

**Comment by char0n** [comment]
@guillaumearm I am for it if you want to work on it. 

> @char0n : Are you ok to create this repo ?

Do you want me to create this repo under `github.com/char0n`, or I just did not understand it properly ?

**Comment by guillaumearm** [comment]
>Do you want me to create this repo under github.com/char0n, or I just did not understand it properly ?

In fact, I can create the repo under `github.com/guillaumearm`.

I would explore to code my own eslint plugin and `eslint-plugin-ramda-adjunct` seems to be a nice playground for doing that.

Anyway, I'll try to take some time to make a **v0.1**
Stay tuned.

**Comment by char0n** [comment]
This haven't seen activity for more than year and a half, closing for now.
