### ISSUE TITLE
Restrict scope case

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#472]
There is a [PR](https://github.com/marionebl/commitlint/issues/307#issuecomment-376480920) adding support for restricting scope to a subset of scopes to commit-lint. We currently have no restriction on scope because we couldn't limit to just one case. Once this PR drops we should restrict to:

```
"rules": {
    "scope-case": [2, ['camel-case', 'kebab-case']],
  }
```

**Comment by char0n** [comment]
PR still pending...

**Comment by Undistraction** [comment]
Linking directly to PR so we can track: https://github.com/marionebl/commitlint/pull/312
