### ISSUE TITLE
RA.isNumberString / RA.isNotNumberString

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#477]
We currently don't offer a way to check if a string is a number.  `isNaN` uses `Number.isNaN` which doesn't attempt to coerce the value. 

```
const s = '12'
RA.isNaN(s) // => true
RA.isNumberString(s) // => true
```

**Comment by Undistraction** [comment]
I don't think the usecase is just limited to processing forms. For example I'm working on a lib which parses CSS. All values are strings, but I need to decide if a value is numeric so I can process it it differently.

**Comment by char0n** [comment]
I'm closing this one for now. As this library primarily focuses on predicates and coercions on actual types. For asserting if the string is a number we would have to coerce it to number anyway and use existing predicates.
