### ISSUE TITLE
RA.EnsureNumber, RA.EnsureString, RA.EnsureBoolean 

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#478]
How about some functions for coercing values if they aren't already that type.

```
const ensureString = unless(isString, toString)
const ensureNumber = unless(isNumber, Number)
```

**Comment by guillaumearm** [comment]
👍 

I would add one for deal with arrays :  
```js
const coerceToArray(unless(isArray, of))
```

**Comment by Undistraction** [comment]
We already have `ensureArray` for exactly that.

**Comment by guillaumearm** [comment]
oops, I had completely forgotten this one. It's stupid because I have made a PR for it 😆 

ok, so maybe we would want to keep the same naming conventions here : `ensureString` and `ensureNumber` ?

**Comment by Undistraction** [comment]
That would make sense.

**Comment by guillaumearm** [comment]
anyway, `ensureBoolean` is not valuable because we could use `Boolean` directly : 
```js
const ensureBoolean = Boolean;
```

**Comment by Undistraction** [comment]
@guillaumearm I'd argue that it would still make sense for consistency - we wrap `Number.isNan` for `isNaN` for example.

**Comment by char0n** [comment]
I am having mixed feeling about those. It seems like unnecessary aliasing. Using `String`, `Number` or `Boolean` should be sufficient. These functions are idempotent, while `R.of` function is not. And that is why `ensureArray` exists.

```js
String(String(1)) === String(1)
Number(Number(1)) === Number(1)
Boolean(Boolean(1)) === Boolean(1)

R.of(R.of(1)) != R.of(1)
```

**Comment by Undistraction** [comment]
I think part of this was based on my misuse of R.toString which can play havoc if you run a string through it - actually I should have been using `String` in which case it would indeed have been idempotent.
