### ISSUE TITLE
RA.isMatch / RA.isNotMatch

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#481]
Ramda offers 'match', but how about we offer an alias of `isMatch` and its complement `isNotMatch`? That would feel a little more consistent with our other predicates.

**Comment by GingerPlusPlus** [comment]
`isMatch` sounds like [`R.test`](http://ramdajs.com/docs/#test).

**Comment by char0n** [comment]
Match is not a predicate because it returns `String` or `Undefined`. So I don't consider it a predicate. Other thing is that we already stipulated in past that we don't want to be in business of aliasing.

**Comment by Undistraction** [comment]
Sorry. I meant using `R.test`, not `R.match`, but I can see that calling it 'RA.isMatch` in that case is confusing. 

I do feel like a negation of `test` would be useful (that is why I first opened the issue) - it feels wrong that we offer so many predicates, but not a flexible one for regexp, and my OCD kicks in when I use `test` alongside a set of `is...` predicates.

**Comment by char0n** [comment]
```js
import { test as hasMatch } from 'ramda';
```
I get you, but people are already used to `test` nomenclature when dealing with regex. `test` in my mind is too a non predicate. Observe..

```js
const regexMatches = test(/a/);
const regexNotMatching = complement(regexMatches);
```

So I consider `test` a factory for predicate creation not a predicate it self.

**Comment by Undistraction** [comment]
OK. I understand what you are saying. Yes it is a factory. 

Do you see any place for a negation of `test`? If not I'll close.

**Comment by char0n** [comment]
I can see a place for a negation of `R.test`. But to come up with the name would be pretty interesting ;]
