### ISSUE TITLE
divideNum

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#482]
Divides two numbers. Equivalent to `b / a`.

**Preferred implementation**
```js
const divideNum = flip(divide);
```
`flip` and `divide` functions are already part of [ramda](https://ramdajs.com/docs).

If the person that is implementing this function comes up with the better name for the function, all suggestions are welcome.

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `divideNum` function.

**Comment by guillaumearm** [comment]
+1 for divideBy

But multiply is commutative, why do you want to flip it ?

**Comment by Undistraction** [comment]
@guillaumearm Of course. I meant `subtract` not `multiply` which isn't commutative.

**Comment by guillaumearm** [comment]
You means #483

**Comment by char0n** [comment]
**Original issue description by @Undistraction** 
I'm forever doing `flip(divide)`, so how about:

```
const divideBy = flip(divide)

const percentToRatio = divideBy(100)
percentToRatio(75) // => 0.75
```
