### ISSUE TITLE
subtractNum

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#483]
Subtracts its first argument from its second argument.

**Preferred implementation**
```js
const subtractNum = flip(subtract);
```
`flip` and `subtract` functions are already part of [ramda](https://ramdajs.com/docs).

If the person that is implementing this function comes up with the better name for the function, all suggestions are welcome.

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `subtractNum` function.

**Comment by guillaumearm** [comment]
@char0n: are you ok to put a `feature` label on  this and #482 ?
This functions are very useful (even in real life use cases)

**Comment by char0n** [comment]
**Original issue description by @Undistraction :**
I'm forever doing  `flip(subtract)`, so how about:

```
const subtractValue = flip(subtract)

const subtract5 = subtractValue(5)
subtract5(6) // => 1
```
