### ISSUE TITLE
RA.move

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#485]
Get a new list with an item's index changed.

```
const moveItem = curry(
  (oldIdx, newIdx, list) => compose(
      insert(
        newIdx,
        nth(oldIdx, list)
      ),
      remove(
        oldIdx,
        1
      )
    )(list)
)

const a = [1, 2, 3, 4] 

moveItem(0, 3, a) // => [2, 3, 4, 1]
```

[REPL](http://ramdajs.com/repl/#?const%20moveItem%20%3D%20curry%28%0A%20%20%28oldIdx%2C%20newIdx%2C%20list%29%20%3D%3E%20compose%28%0A%20%20%20%20%20%20insert%28%0A%20%20%20%20%20%20%20%20newIdx%2C%0A%20%20%20%20%20%20%20%20nth%28oldIdx%2C%20list%29%0A%20%20%20%20%20%20%29%2C%0A%20%20%20%20%20%20remove%28%0A%20%20%20%20%20%20%20%20oldIdx%2C%0A%20%20%20%20%20%20%20%201%0A%20%20%20%20%20%20%29%0A%20%20%20%20%29%28list%29%0A%29%0A%0Aconst%20a%20%3D%20%5B1%2C%202%2C%203%2C%204%5D%20%0A%0AmoveItem%280%2C%203%2C%20a%29%20%2F%2F%20%3D%3E%20%5B2%2C%203%2C%204%2C%201%5D%0AmoveItem%283%2C%200%2C%20a%29%20%2F%2F%20%3D%3E%20%5B4%2C%201%2C%202%2C%203%5D%0AmoveItem%282%2C%203%2C%20a%29%20%2F%2F%20%3D%3E%20%5B1%2C%202%20%2C4%20%2C3%5D%0AmoveItem%281%2C%200%2C%20a%29%20%2F%2F%20%3D%3E%20%5B2%2C%201%20%2C3%20%2C4%5D%0AmoveItem%280%2C%201%2C%20a%29%20%2F%2F%20%3D%3E%20%5B2%2C%201%20%2C3%20%2C4%5D%0A)

Additional possibilities:

- `RA.moveBy(fromIndex, by)`

**Comment by char0n** [comment]
`R.move` make sense. There seems to be a usecases for it https://www.npmjs.com/package/array-move
