### ISSUE TITLE
RA.replaceToken, RA.replaceTokens

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#490]
Here are a set of functions I find very useful. I think they would make a great addition to the lib. I already have tests written. 

```
replaceToken(`alpha #{bravo}`, `bravo`, `charlie`) //=> `alpha charlie`
replaceTokens(`alpha #{bravo} #{delta}`, { bravo: `charlie`, delta: `echo` }) //=>`alpha charlie echo`
replaceTokens(`alpha #{1} #{2}`, [`bravo`, `charlie`]) //=> `alpha bravo charlie`
```

Note: `condDefault` is just `R.cond` with  a default of `[R.T, R.identity]` (See #487)

```
const toToken = v => new RegExp(`#{(${v})}`, `g`)

const replaceWithMap = curry((template, valueMap) =>
  reduceObjIndexed(
    (acc, [key, value]) => replaceToken(acc, key, value),
    template,
    valueMap
  )
)

const replaceWithArray = curry((template, values) =>
  pipe(
    reduceIndexed((acc, v, idx) => assoc(inc(idx), v, acc), stubObj()),
    replaceWithMap(template)
  )(values)
)

export const replaceToken = curry((template, tokenName, value) =>
  replace(toToken(tokenName), value, template)
)

export const replaceTokens = curry((template, value) =>
  condDefault([
    [isArray, replaceWithArray(template)],
    [isPlainObj, replaceWithMap(template)],
  ])(value)
)
```

Obviously there is the possibility of exposing the token generation as well.

**Comment by Undistraction** [comment]
@char0n @guillaumearm I'd love to get this added. I think these are very useful functions. How do you feel about this?

**Comment by char0n** [comment]
Feels like you attempting to create a simple templating language. I'm for having something like https://lodash.com/docs/4.17.10#template. But this have to be thought really carefully.

**Comment by Undistraction** [comment]
Well there are a lot of features in lodash's `template` that I think are way outside what we should offer - loading templates from URLs etc. The scope for this is simply replacing values in a template string. I'm definitely up for expanding it a little though. It currently allows:

- single values to be replaced,
- arrays of values to be used to replace numeric tokens 
- objects of values to be used to replace keyed tokens

What other features do you feel it would need to support to be included?

**Comment by char0n** [comment]
Closing this for now. This should be possible to implement with `lazy string template literals concept` by creating ad-hoc curried functions when creating function composition.

https://stackoverflow.com/questions/30003353/can-es6-template-literals-be-substituted-at-runtime-or-reused
