### ISSUE TITLE
RA.hasIndex

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#495]
Does a list have a given index?

```
export const hasIndex = R.curry((n, l) =>
  RA.lensSatisfies(RA.isNotUndefined, R.lensIndex(n))(l)
)
```

**Comment by guillaumearm** [comment]
`R.has` do the work, but have a different behavior : 
```js
R.has(0, [undefined]) //=> true
hasIndex(0, [undefined]) // => false
```

**note**:
`R.has(0, [undefined])` in consistent with `R.has('a', { a: undefined })`

We should think about adding a `RA.hasValue` (any idea for the name ?).
It's like `R.has` but check if value is nil (using `R.isNil`).

**Comment by Undistraction** [comment]
@guillaumearm OK. I'm going to close this as it is effectively covered by `R.has`. 

> We should think about adding a RA.hasValue (any idea for the name ?).

Maybe `RA.hasDefined`? I think you should open a new issue for it so we can discuss.
