### ISSUE TITLE
documentation: display the implementation when it only has one line

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#508]
Like in [RA.mapIndexed](https://char0n.github.io/ramda-adjunct/2.6.0/RA.html#.mapIndexed) and [RA.reduceIndexed](https://char0n.github.io/ramda-adjunct/2.6.0/RA.html#.reduceIndexed), I think it's can be useful to display the implementation of all one line functions.

Just by adding in documentation : 
```
Implementation: `const mapIndexed = R.addIndex(R.map)` 
```

**Comment by Undistraction** [comment]
This is a nice idea.

**Comment by guillaumearm** [comment]
If @char0n is ok with that, I will go for it soon.

**Comment by char0n** [comment]
@guillaumearm good idea. But it create the problem of disconnecting when we document and what is the implementation. Can we somehow automate it via jsdoc and our docdash theme ?

**Comment by char0n** [comment]
Never had a similiar usecase. The person handling this issue will have to do his homework ;]

**Comment by char0n** [comment]
Closing this for now. The source code of the function is directly accessible from documentation anyway.
