### ISSUE TITLE
Is there a function to do strict equality check ?

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#518]
I asked myself when I wrote https://github.com/char0n/ramda-adjunct/pull/513#issuecomment-384323292 :

Because `R.equals` performs deep equality checks, is there a function to do strict equality in `RA` (or directly `Ramda`) ?

**Comment by guillaumearm** [comment]
And what about adding a `strictEquals` function in `RA`  ?

**Comment by char0n** [comment]
I would introduce isEqualWith which consumes the customizer and after then I'd derive something like `strictEquals` from it.

**Comment by guillaumearm** [comment]
there is already [R.eqBy](http://ramdajs.com/docs/#eqBy) for this.

**Comment by char0n** [comment]
It's different in implementation that lodash. Check the source: https://github.com/ramda/ramda/blob/master/source/eqBy.js

I think we can introduce `eqStrict` which will be eqvivalent to `===`, but we cannot use  `eqBy` for it.

**Comment by Undistraction** [comment]
I would vote we call it `equalsStrict` as this is much easier to remember. I think when we are talking about function libs with so many different functions I'd always favour verbosity. It always bugs the hell out of me when I use `R.T`.

**Comment by char0n** [comment]
Missed it. We have http://ramdajs.com/docs/#identical so we have everything we need for further compositions
