### ISSUE TITLE
isNonEmpty

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#524]
Because we have [RA.isNonEmptyString](https://char0n.github.io/ramda-adjunct/2.7.0/RA.html#.isNonEmptyString) and [RA.isNonEmptyArray](https://char0n.github.io/ramda-adjunct/2.7.0/RA.html#.isNonEmptyArray).

What about a `RA.isNonEmpty` function ?

It is just the complement of [R.isEmpty](http://ramdajs.com/docs/#isEmpty).
It works with strings, arrays and objects according to [R.isEmpty documentation](http://ramdajs.com/docs/#isEmpty).

**Comment by Undistraction** [comment]
Makes sense for completeness.

**Comment by char0n** [comment]
We already have https://char0n.github.io/ramda-adjunct/2.7.0/isNotEmpty.js.html#line3

**Comment by guillaumearm** [comment]
Woops, that's true, sorry.
