### ISSUE TITLE
using ZenHub

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#526]
I think it's can be good to use [ZenHub](https://www.zenhub.com/) in order to manage better triage for issues.

![image](https://user-images.githubusercontent.com/16897658/39395027-4f75c594-4ad9-11e8-8f70-13038ff4aa53.png)

There is nice features like dependencies : 
![image](https://user-images.githubusercontent.com/16897658/39395031-69c46112-4ad9-11e8-8b0d-e920962ecef2.png)

You can choose, if an issue/PR is `blocked` or `blocking` : 
![image](https://user-images.githubusercontent.com/16897658/39395037-7ac41da4-4ad9-11e8-83ae-6dadb1c4ccb1.png)

Ref : https://www.zenhub.com/

@char0n, @Undistraction : what do you think ?

**Comment by Undistraction** [comment]
Looks great. Would definitely help.

**Comment by char0n** [comment]
Doesn't github projects solve the same thing ?

**Comment by guillaumearm** [comment]
Yes it is, but ZenHub have much more poweful features.

**Comment by char0n** [comment]
How do we turn it on ?

**Comment by guillaumearm** [comment]
Just install the chrome ZenHub extension.

Then, this will add a "ZenHub" tab in GitHub.

**Comment by char0n** [comment]
We'll not be using this for now as there is currently no need for it.
