### ISSUE TITLE
cata

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#58]
Catamorphism monad bridge

**Comment by char0n** [comment]
@tycho01 could you please review the typings if you'll have couple of minutes to spare. I've added some more complex declarations.

https://github.com/char0n/ramda-adjunct/blob/1c6fdc63abc28813cd0be37839ce38793b2554dd/src/index.d.ts#L260

Thank you

**Comment by tycho01** [comment]
Without having tested them, I think that looks okay. I'm still less confident about the ADTs as defined in Ramda as well, also see [here](https://github.com/fantasyland/fantasy-land/issues/140#issuecomment-289188011).

**Comment by char0n** [comment]
Thanks for your time mate. Will look at the link.
