### ISSUE TITLE
Improve Github Description

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#591]
Currently: 

> Adjunct is a thing added to something else as a supplementary rather than an essential part. And that something is being ramda.

Recommended:

> Ramda Adjunct is the most popular and most comprehensive set of utilities for use with Ramda, providing a variety of useful, well tested functions with excellent documentation.

@char0n (I don't have permission to update the description)

**Comment by char0n** [comment]
I will do it and move the original sentence to readme.
