### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#592]
IMHO the Ramda Logo is terrible and we shouldn't feel the need to use it. I've been playing around with a few ideas and I really like this one. It about as simple as possible which is to my taste but might not be to yours @char0n. Obviously we can try some colours if you like it. No problem if not. 

![ra_logo-01](https://user-images.githubusercontent.com/161489/40993205-da49e012-68f0-11e8-9458-269193341a0a.jpg)

**Comment by guillaumearm** [comment]
Nice work.
I like very much the logo and his simplicity, but it does not remind me ramda.
Is it ok if the logo doesn't make think of ramda ?

@char0n: What did you expect from the new ramda-adjunct logo ? What is your feeling ? :)

**Comment by Undistraction** [comment]
@guillaumearm Perhaps we could use Ramda's purple as a nod to Ramda.

**Comment by guillaumearm** [comment]
Completely agreed, very good idea. Why not the 'R' symbol in purple and the '+' in heavy black ?

**Comment by char0n** [comment]
Nice work. I was thinking about fact that we are using RA abbreviation. So what about using the egyptian symbol for the eye of ra ? https://i.pinimg.com/736x/cf/ea/96/cfea96070bcec47b0de57690223dd18b--egyptian-eye-egyptian-symbols.jpg

**Comment by Undistraction** [comment]
@char0n Again this is very much a matter of taste, but tbh I don't think that really fits with the feel of the library - the logo should represent utility and simplicity. I also think my idea incorporate the idea of functions locking together and RA and R locking together.

**Comment by char0n** [comment]
Yeah, you're right. I just tried to propose my RA stuff anyway ;]

Let's go for your proposal. It's original work so we won't have problems with license ;]

So the actions points:
 - let's move this image into readme.md
 - let's create a favicon.ico

**Comment by Undistraction** [comment]
Sorry. I've been very short of time recently. This is on my radar and I'll get this done soon.

**Comment by char0n** [comment]
No problem. I think I can use jpeg attached here to do magic.

**Comment by char0n** [comment]
@Undistraction can you provide a source code of the image in this issue ?
