### ISSUE TITLE
uniqueId

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#609]
The same behavior as lodash

**Comment by char0n** [comment]
@Undistraction, @guillaumearm is this something that should be part of library ? I have a ton of usecases for it, but this function will not be referentially transparent, which means it's not going to be pure (although it will not have side effects). What do you think ? The implementation (without supporting prefixes) is quite primitive.

```js
const uniqueId = (() => {
  let id = 0;

  return () => {
    id += 1;

    return String(id);
  };
})();

**Comment by Undistraction** [comment]
I'm 100% for utility over purity for things like this. I'd prefer a well tested function that is part of a trusted lib, however there are a few others we have come across that are useful but not pure - `throwError` and `log` - that we haven't included, so how about including them under an `impure` namespace?

**Comment by char0n** [comment]
@Undistraction I still think we can do this in pure and referentially transparent way. For example `uniqueId` usecase can be rewritten into pure way using [Reader monad](https://monet.github.io/monet.js/#reader). The same can be applied for `log` function.

```js
const uniqueId = () => Reader({ seed }) => String(seed);
uniqueId.seed = () => ({ seed: 0 });
```
Now we have `RA.weaveLazy` to weave the config into the pure  `uniqueId` function.
```js
import { uniqueId as uniqueIdPure } from './src';
// src/impure/uniqueId.js
export const uniqueId = weaveLazy(uniqueIdPure, (config) => () => {
  config.seed += 1;
  return config;
}(uniqueIdPure.seed()));
```
Now we have 2 versions of `uniqueId`, one pure and one impure. One can be tested with ease, the other one is almost unpredictable to test but still it's possible. Is this something that could solve our problem and can act as a compromise for purity and utility ?

**Comment by char0n** [comment]
It's an effect. It doesn't have place in FP library.
