### ISSUE TITLE
Make all tests consistent + support for Ramda placeholder

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#624]
Currently our support for ramda placeholder is limited. Almost all binary functions are lacking the support for it. We need to continually provide full support for it. Every binary function needs to have the following test in it's test suite
```js
  it('should support placeholder to specify "gaps"', function() {
    const trimStart = RA.trimStart(R.__);

    assert.strictEqual(trimStart('  abc'), 'abc');
  });
```
All other functions needs to have following curring test which tests the combination of params invocation:
```js
  it('should curry', function() {
    assert.isTrue(RA.allEqualTo(1, [1, 1]));
    assert.isTrue(RA.allEqualTo(1)([1, 1]));
  });
```

As part of this, we should also refactor all tests to be consistent with gherkin style of testing. Here is an [example PR](https://github.com/char0n/ramda-adjunct/commit/8b8f8dff4d76d8512959b1142e3416c1bd4f5c4b) which demonstrates what we want. I already invested tens of hours into this effort, but need help to rectify these things in the rest of our tests.

**Comment by char0n** [comment]
@js636f would would you say to help me with this effort ? Is it something you would be interested in ?

**Comment by char0n** [comment]
@js636f thank you for doing great job! Last 3 days I've spent 40 hours so far to increase quality of our issues as part of https://github.com/char0n/ramda-adjunct/issues/1069. I've already transformed half of our issues. Feel free to take any one of them If you feel to and there is no need for you to always just work on this one. So...feel free to grab any issue with `Feature` and `Help wanted` label.

**Comment by js636f** [comment]
@char0n, thank you! I think I'll close this issue first.

**Comment by char0n** [comment]
@js636f how are we looking here? Are we done here?

**Comment by char0n** [comment]
Closing this as we have last PR approved. @js636f great job here!
