### ISSUE TITLE
Functional Javascript by Michael Fogus

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#66]
~~isSet~~, ~~isMap~~, isIndexed, ~~isTruthy~~, ~~isFalsy~~, ~~isEven~~, ~~isOdd~~, repeatedly, ~~fnull~~, ~~dispatch~~, hasKeys, trampoline, skipatke, pipeline, condition <-> validator pattern

**Comment by char0n** [comment]
https://developer.mozilla.org/pl/docs/Glossary/Falsy

**Comment by char0n** [comment]
@fogus just wanted to let you know, I read your book and it was really great. I compiled the list of some of the functions you described I would like to implement them into ramda-adjunct. There are couple of more that I would to add to the list, but have them stored in my notes on the iPad. Would you mind if I do so ?

Thank you very much for the book

**Comment by fogus** [comment]
I do not mind at all.  Update me with a link when you get started.

**Comment by char0n** [comment]
@fogus will sure do. Will be progressively implementing utils from the list spanning multiple releases. I can update you with every new release that will contain at least one of the utils of your design.

**Comment by char0n** [comment]
@fogus `isOdd`, `isEvent` already in [v2.1.0](https://char0n.github.io/ramda-adjunct/2.1.0/). For next release v2.2.0, `isTruthy` and `isFalsy` is planned.

**Comment by rockymadden** [comment]
Thrush combinator is known as `applyTo` in Ramda: https://github.com/ramda/ramda/pull/1847

**Comment by char0n** [comment]
@rockymadden thrush combinator removed from list. Thanks

**Comment by Undistraction** [comment]
@char0n Shall we get the remaining functions into their own issues?

**Comment by char0n** [comment]
@Undistraction yep, but I need to do that (or anybody that read the @fogus book). We'll have to provide original implementation as a description for these separate issues and explanation from the book for possible usecases.

**Comment by char0n** [comment]
I've created separate issue for [fnull](https://github.com/char0n/ramda-adjunct/issues/1235)

**Comment by char0n** [comment]
I've created separate issue for [isIndexed](https://github.com/char0n/ramda-adjunct/issues/1236)

**Comment by char0n** [comment]
repeatedly is basically an alias of [R.times](https://ramdajs.com/docs/#times)

**Comment by char0n** [comment]
`hasKeys` will not be implemented as it seems very very specialized. But can be easily implemented using `R.allPass([R.has('key1'), R.has('key2')])`

**Comment by char0n** [comment]
I've created separate issue for [skipTake](https://github.com/char0n/ramda-adjunct/issues/1237)

**Comment by char0n** [comment]
I've create separate issue for [trampoline](https://github.com/char0n/ramda-adjunct/issues/1238)

**Comment by char0n** [comment]
@fogus closing this as most have been implemented and what remains has been fragmented into separate independent issues from this issue comments. Again, thank you for the book!
