### ISSUE TITLE
padEnd, repeatStr

### ISSUE THREAD

**Issue by trustedtomato** [char0n/ramda-adjunct#667]
Hey! Firstly, thanks for all the effort you put into the library!
I've got some functions which might be suitable for the library too. I would be happy to do a PR!

---

`padEnd` & friends:
```javascript
const padEnd = curry((n, str) => str.padEnd(n));
const padEndWith = curry((n, str, padString) => str.padEnd(n, padString));
const padStart = curry((n, str) => str.padStart(n));
const padStartWith = curry((n, str, padString) => str.padStart(n, padString));
```

---

`repeatStr`:
```javascript
const repeatStr = curry((n, str) => str.repeat(n));
```

**Comment by char0n** [comment]
Hi @trustedtomato, no problem we hope it helps people build better software.

Regarding your feature set, there is already an issue for it #400  and a PR #418. We've discontinued the efforts there. You can start fresh here from the start. I'd suggest starting with this: https://github.com/char0n/ramda-adjunct/pull/418

https://github.com/char0n/ramda-adjunct/issues/400#issuecomment-368325029

Why using ponyfill ? We want RA to work even on environments where String.prototype.repeat and other functions are not present

**Comment by char0n** [comment]
These seems to be requested features so I'll start implementing this.

**Comment by char0n** [comment]
repeatStr is on the way
