### ISSUE TITLE
Promises stuff

### ISSUE THREAD

**Issue by guillaumearm** [char0n/ramda-adjunct#676]
Hi, lambda bros 🙂 

I'm highly motivated to make a collection of promises curried functions like `pmap`, `pfilter`, and so on...
**I'm tired to make for loops in async functions, this is why I'm so motivated.**

I've never been able to find a library proposing curried functions to do that.
The idea is to list all functions we want here.

Interesting link: https://www.fpromises.io/

**Comment by char0n** [comment]
Hi @guillaumearm, good idea. I've started the work already some time ago here: https://github.com/char0n/ramda-adjunct/issues/35

In addition to that we already have [reduceP](https://char0n.github.io/ramda-adjunct/2.9.0/RA.html#.reduceP) and [reduceRightP](https://char0n.github.io/ramda-adjunct/2.9.0/RA.html#.reduceRightP)

**Comment by guillaumearm** [comment]
Oh nice 🙂 , so we can considerate this issue as a duplicate ? and add `mapP` and `filterP` to the list ?

**Comment by Undistraction** [comment]
Guys I'm really sorry to have been so absent. I switched from 13 years of freelancing to a full-time job and it's been hard finding time for other things. I should be up-to-speed in the next few weeks and I promise I'll try and carve out some time for this lib.

**Comment by char0n** [comment]
@guillaumearm I'd create separate issues for every one of your new additions and connect them together.

@Undistraction no worries haven't had much time last 3 months too. Holidays, trying to push new product out, family etc..

**Comment by char0n** [comment]
@guillaumearm If you're still motivated then go ahead. But to make naming consistent I'd for for `mapP`, `filterP` and so on...

**Comment by char0n** [comment]
I guess I'd leave the parallel behaviors to RxJS which I'm already heavily using and RA works with it very well. IMHO RA is not a place for these things.

**Comment by char0n** [comment]
Sorry if I wasn't clear. I don't mean removing anything. I am saying - let's be careful what we put in. IMHO it make sense to put in  `delayP`, `catchP`, `catchIfP`, `promisify` and `promisifyAll`. They all deal with serial behaviors only. Let's leave parallel flows to libraries like https://www.fpromises.io/ or https://github.com/Reactive-Extensions/RxJS/.

Other thing that I was mentioning are functions like `filterP` or `mapP`. I'm taking back what I wrote before. I think they can prove practical

```js
const promise = resolveP([1, 2, 3]);

filterP(isEven, promise); //=> Promise([2])

**Comment by char0n** [comment]
THere's been no followup here. CLosing.
