### ISSUE TITLE
R.headAndTail, R.initAndLast

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#719]
```javascript
const a = [1,2,3,4]

const convergeToList = R.converge(RA.list)

const headAndTail = convergeToList([R.head, R.tail])
const initAndLast = convergeToList([R.init, R.last])

const [first, lastRest] = headAndTail(a) //=> [1, [2, 3, 4]]

const [firstRest, last] = initAndLast(a) //=> [[1, 2, 3], 4]
```

Codepen [here](https://codepen.io/Pedr/pen/MPGQKB?editors=0011).

**Comment by char0n** [comment]
Yep, I get what you're trying to do. In current javascript we can do following (in imperative way)
```js
const a = [1,2,3,4]

const [first, tail] = [head(a), tail(a)];
```
Anyway It seems like this is specialized version of https://ramdajs.com/docs/#partition. IMHO these functions can be additions but I'm struggling with the names. Having the `and` inside the function name seems strange.

**Comment by char0n** [comment]
Closing for now. Haven't seen any upvotes here in a year.
