### ISSUE TITLE
RA doesn't include latest version of R in peerDependencies range

### ISSUE THREAD

**Issue by Undistraction** [char0n/ramda-adjunct#745]
The README says: 
> ramda >= 0.19.0

But in the package.json
```
"peerDependencies": {
    "ramda": ">= 0.19.0 <= 0.25.0"
  },
```

The current version of Ramda is `0.26.0`, so updating to the latest version of Ramda in a project using Ramda Adjunct results in:
> npm WARN ramda-adjunct@2.11.0 requires a peer of ramda@>= 0.19.0 <= 0.25.0 but none is installed. You must install peer dependencies yourself.

**Comment by char0n** [comment]
Yes and that is correct. We haven't tested newest version of ramda@0.26.0 yet and there is pending PR for it here https://github.com/char0n/ramda-adjunct/pull/738. All our tests are failing, so I suppose something must have changed and we should compensate.

**Comment by char0n** [comment]
If you have time feel free to take over this one.

**Comment by Undistraction** [comment]
OK. But the README Is incorrect then. It should have an upper limit on the supported range:

> ramda >= 0.19.0

**Comment by char0n** [comment]
Agree it's incorrect. I forgot to translate the peerDeps rules there.
