### ISSUE TITLE
isNegativeZero

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#784]
Object.is can be used to provide the check under hood

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `isNegativeZero` function.

**Comment by miguelcarvalho13** [comment]
Can I work on this issue?

**Comment by char0n** [comment]
@miguelcarvalho13 sure. It's yours now. Good luck!

**Comment by miguelcarvalho13** [comment]
Hi! Thank you for let me work in this issue.

Just submitted a PR for this issue.
Please let me know if I need to change something.
