### ISSUE TITLE
isSparseArray

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#785]
An array with at least one “empty slot” in it is often called a “sparse array.”

**Comment by char0n** [comment]
https://stackoverflow.com/questions/36622064/check-the-array-has-empty-element-or-not

**Comment by dawehner** [comment]
I've implemented this function in https://github.com/char0n/ramda-adjunct/pull/1022

**Comment by char0n** [comment]
Thank you for noticing this feature issue. You provided a PR in #1022, but I think we have get our theory right first. Your implementation is assumes that spare array is every array that includes `undefined` value. That is unfortunately not true.

To share more light on the problem, please read the Array section on this document [You Don't Know Javascript](https://github.com/getify/You-Dont-Know-JS/blob/f0d591b6502c080b92e18fc470432af8144db610/types%20%26%20grammar/ch3.md#array) which explains the problem in intimate detail.

The implementation should reflect that theory. Here one of the way how sparse arrays can be detected in javascript. You can take it, and use it in your PR.

```js
const list = [1, , 2];
R.values(list).length === list.length; // if this eqation returns false then the list is sparse array

**Comment by char0n** [comment]
As agreed, closing in favor of https://github.com/char0n/ramda-adjunct/pull/1048

**Comment by dawehner** [comment]
Thank you! Sorry again for stopping the work

**Comment by char0n** [comment]
@dawehner no problem at all ;]
