### ISSUE TITLE
isSentinelValue

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#793]
**Is your feature request related to a problem? Please describe.**

-1 is commonly called a "sentinel value," which basically means a value that's given an arbitrary semantic meaning within the greater set of values of its same type (numbers). The C-language uses -1 sentinel values for many functions that return >= 0 values for "success" and -1 for "failure."

**Describe the solution you'd like**
Possible implementation
```js
const isSentinelValue = curry(val => ~val === 0);
```

Assertions
```js
isSentinelValue(-1); //=> true
isSentinelValue('-1'); // => true
isSentinelValue(new Number('-1')); // => false
isSentinelValue(2); //=> false
isSentinelValue('a'); //=> false
```

**Describe alternatives you've considered**

**Additional context**

[The curious case of ~](https://github.com/getify/You-Dont-Know-JS/blob/9959fc904d584bbf0b02cf41c192f74ff4238581/types-grammar/ch4.md#the-curious-case-of-the-)

**Comment by skShekhar** [comment]
@char0n Can I take this up

**Comment by char0n** [comment]
@skShekhar sure go ahead.

**Comment by skShekhar** [comment]
@char0n Is `[-1]` a sentinel value?

**Comment by char0n** [comment]
@skShekhar that's a good question.

Sentinel value can only be [signed 32 integer](https://char0n.github.io/ramda-adjunct/2.32.0/RA.html#.isInteger32). We cannot count in implicit JavaScript coersions.

So the correct implementation would be:

```js
const isSentinelValue = curry(val => isInteger32(val) && ~val === 0);
```

**Comment by skShekhar** [comment]
@char0n Using `isInteger32` will fail for `new Number(-1)` which is one of the assertions in the description.

**Comment by char0n** [comment]
@skShekhar right, I've updated to assertion to expect `false`. `Number(-1)` is technically an object and not signed 32 bit integer value.

**Comment by skShekhar** [comment]
@char0n Okay. If we are not going to do any type coercions, that means `'-1'` is also out. The only thing left is `-1`. Do we even need a function just to check if the value is `-1`?

**Comment by char0n** [comment]
> @char0n Okay. If we are not going to do any type coercions, that means '-1' is also out. 
Yes, it means exactly that.

> The only thing left is -1. Do we even need a function just to check if the value is -1?

Yes, we have a lot functions asserting on single value. The function becomes handy in more complex functional compositions like validation and others.
