### ISSUE TITLE
unzipObjWith

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#801]
To form a partial isomorphism with `R.zipObj` the transformation needs to look like this:

```js
const patient = {
  'abbrev@1':{
    version:'1.0.9',
    resolved:'https://registry.yarnpkg.com/abbrev/-/abbrev-1.0.9.tgz#91b4792588a7738c25f35dd6f63752a2f8776135'
  },
  'shell-quote@git+https://github.com/srghma/node-shell-quote.git#without_unlicenced_jsonify':{
    version:'1.6.0',
    resolved:'git+https://github.com/srghma/node-shell-quote.git#0aa381896e0cd7409ead15fd444f225807a61e0a'
  },
  '@graphile/plugin-supporter@git+https://1234user:1234pass@git.graphile.com/git/users/1234user/postgraphile-supporter.git':{
    version:'1.6.0',
    resolved:'git+https://1234user:1234pass@git.graphile.com/git/users/1234user/postgraphile-supporter.git#1234commit'
  },
}

const result = unzipObjWith((value, key) => [key, { ...value, name: key }]), patient)

const expected = [
  [
    'abbrev@1', 
    'shell-quote@git+https://github.com/srghma/node-shell-quote.git#without_unlicenced_jsonify',
    '@graphile/plugin-supporter@git+https://1234user:1234pass@git.graphile.com/git/users/1234user/postgraphile-supporter.git',
 ],
 [
  {
    name: 'abbrev@1',
    version:'1.0.9',
    resolved:'https://registry.yarnpkg.com/abbrev/-/abbrev-1.0.9.tgz#91b4792588a7738c25f35dd6f63752a2f8776135'
  },
  {
    name: 'shell-quote@git+https://github.com/srghma/node-shell-quote.git#without_unlicenced_jsonify',
    version:'1.6.0',
    resolved:'git+https://github.com/srghma/node-shell-quote.git#0aa381896e0cd7409ead15fd444f225807a61e0a'
  },
  {
    name:   '@graphile/plugin-supporter@git+https://1234user:1234pass@git.graphile.com/git/users/1234user/postgraphile-supporter.git',
    version:'1.6.0',
    resolved:'git+https://1234user:1234pass@git.graphile.com/git/users/1234user/postgraphile-supporter.git#1234commit'
  },
 ]
]

expect(result).toEqual(result)
```

So you'll need to do `expected[1]` to get what you need. I like that this is generic concept which plays with the rest of the `zipping` algos.

**Comment by thomasmichaelwallace** [comment]
I can take a look at this :)

**Comment by char0n** [comment]
@thomasmichaelwallace go ahead. Does the function make sense to you ? 

I've also create issue for [zipObjWith](https://github.com/char0n/ramda-adjunct/issues/1129). Take a look at it - I'd appreciate your opinion. Thanks

**Comment by thomasmichaelwallace** [comment]
I think so, I understood it like this:

* Split a `{ key: value }` object into an array of `[key, value]` tuples
* Apply a function of the signature `(value, key) => [key', value']` to each of the tuples
* Return an tuple of arrays of the transformed keys/values respectively: `[[keys'], [values']]`.

Noting that with an identity function this would be a way to get a tuple where the left hand side is all the object keys and the right hand side is all the object values.

#1129 zipObjWith is the reverse of this - which I think is probably the more useful of the two from my experience.

n.b. I'll implement it as you've shown, but the function's signiture `(value, key)` seems counter-intuitive to me given that the array and map are ordered `(key, value)`?

**Comment by thomasmichaelwallace** [comment]
Interesting- it does make sense to match that consistency. Thanks for pointing it out.
