### ISSUE TITLE
anyP

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#807]
Make sense to wait untill stage-2 is reached. https://github.com/tc39/proposal-promise-any

**Update:**
Already present in other Promise libraries. No need to wait for stage-2.

**Comment by char0n** [comment]
This pattern is like all([ .. ]), but it ignores any rejections, so only one needs to fulfill instead of all of them.

**Comment by char0n** [comment]
Proposal is in stage 1.

**Comment by tynopet** [comment]
I'm going to implement this feature

**Comment by char0n** [comment]
@tynopet thanks, I've assign the issue to you, applied `Hacktoberfest` label and I'm looking into the PR now.

**Comment by char0n** [comment]
This tc39 proposal just reached stage 3. No major changes are expected from this point on.
