### ISSUE TITLE
firstP/headP

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#815]
This pattern is like a race with [anyP([ .. ])](https://github.com/char0n/ramda-adjunct/issues/807), which means that it ignores any rejections and fulfills as soon as the first Promise fulfills.

Promise patterns explained in [YDKN series](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/ch3.md#variations-on-all---and-race--)

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `firstP/headP` function.

**Comment by char0n** [comment]
This implementation of first(..) does not reject if all its promises reject; it simply hangs, much like a Promise.race([]) does. If desired, you could add additional logic to track each promise rejection and if all reject, call reject() on the main promise.

**Comment by tynopet** [comment]
I'm going to implement this feature

**Comment by char0n** [comment]
@tynopet you're assigned. Good luck!

**Comment by char0n** [comment]
This has effectively become just an alias of `anyP`. Unfortunately we've realized that after the implementation.
