### ISSUE TITLE
lastP

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#816]
This pattern is like [firstP([ .. ])](https://github.com/char0n/ramda-adjunct/issues/815), but only the latest fulfillment wins.

Promise patterns explained in [YDKN series](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/async%20%26%20performance/ch3.md#variations-on-all---and-race--)

[This PR](https://github.com/char0n/ramda-adjunct/pull/1067) should serve as a model template of PR for `lastP` function.

**Comment by thomasmichaelwallace** [comment]
I'll take a look at this :)

**Comment by char0n** [comment]
@thomasmichaelwallace thanks, you're assigned.
