### ISSUE TITLE
docs: wrong example in lengthGte

### ISSUE THREAD

**Issue by evdama** [char0n/ramda-adjunct#825]
Seems the third out of three examples at https://char0n.github.io/ramda-adjunct/2.14.0/RA.html#.lengthGte is wrong as it shows `false` when it's actually `true` (same as the second example).

**Comment by char0n** [comment]
Thanks for noticing. I will issue an PR with fix ASAP. Or if you wish feel free to issue PR with fix.

**Comment by evdama** [comment]
cheers, no worries, go ahead and do a PR... thanks

**Comment by char0n** [comment]
PR provided.
