### ISSUE TITLE
Cannot find module 'jsverify'

### ISSUE THREAD

**Issue by ipanasenko** [char0n/ramda-adjunct#838]
Hey, guys. Seems like in latest minor version there's a bug in types. I get following error:

`node_modules/ramda-adjunct/src/index.d.ts(1,29): error TS2307: Cannot find module 'jsverify'.`

Can it be so that you forgot to add `jsverify` to dependencies?

**Comment by char0n** [comment]
Problem is here: https://github.com/char0n/ramda-adjunct/blob/master/src/index.d.ts#L1

Some symbol got imported automatically from jsverify and it slipped inside during core review. I'll create a patch release this evening to fix it. Thanks for reporting this.

**Comment by char0n** [comment]
Released [v2.16.1](https://www.npmjs.com/package/ramda-adjunct/v/2.16.1) which fixes this problem. Thanks again for reporting this.
