### ISSUE TITLE
flattenDepth

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#844]
https://tc39.github.io/proposal-flatMap/

```js
// flattenDepth :: Number -> [a] -> [b]
```

**Comment by JaceHensley** [comment]
Hello, I was wondering if you had an implementation idea for this? Even something a little messy. Trying to implement it but not having much luck. Thanks!

**Comment by char0n** [comment]
Yeah I think so. Ramda has [_makeFlat](https://github.com/ramda/ramda/blob/master/source/internal/_makeFlat.js) which can be used in non recursive mode.

```js
const baseFlatten = _makeFlat(false);

// pseudo code
const flattenDepth = curry((depth, list) => {
  // call baseFlatten on list until depth === 0
});

**Comment by char0n** [comment]
You could provide a PR for this if you wish to

**Comment by JaceHensley** [comment]
Awesome thank you! I'll fiddle with that and if I can get it working I'll submit a PR
