### ISSUE TITLE
whereAny

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#889]
**Is your feature request related to a problem? Please describe.**

Takes a spec object and a test object; returns true if the test satisfies the spec. Each of the spec's own properties must be a predicate function. Each predicate is applied to the value of the corresponding property of the test object. where returns true if one of the predicates return true, false otherwise. This function is just like [R.where](https://ramdajs.com/docs/#where) but uses `boolean OR` instead or `boolean AND`

**Describe the solution you'd like**

Possible implementation
```js
const whereAny = R.curry((spec, testObj) => {
  for (let [key, fn] of Object.entries(spec)) {
    if (fn(testObj[key])) {return true}
  }
  return false
})

const pred = searchValue => whereAny({
  a: R.includes(searchValue),
  b: R.equals(searchValue),
  x: R.gt(R.__, 3),
  y: R.lt(R.__, 3)
});
```

**Describe alternatives you've considered**

--

**Additional context**

Originally conceived on SO: https://stackoverflow.com/questions/55688667/ramda-whereany
`R.where` - https://ramdajs.com/docs/#where

**Comment by nshaikhinurov** [comment]
Useful function. I've currently copied it from SO, thanks

**Comment by char0n** [comment]
You can issue a PR if you want to see this function in RA permanently ;]

**Comment by kcouliba** [comment]
Hey, I'd like to give a try on that one if you don't mind. I think the proposed implementation could do.

**Comment by char0n** [comment]
@kcouliba you didn't give me chance to respond to your comment here. It seems that somebody already implemented this function in [ramda](https://github.com/ramda/ramda/blob/master/source/whereAny.js). 

Having said that, we'll not be incorporated this function into Ramda Adjunct as well. I'm sorry you'd have to go through the trouble of implementing it.

**Comment by kcouliba** [comment]
@char0n no problem, I had fun implementing it. I'll be looking forward to other functions to implement
