### ISSUE TITLE
Use chai directly instead of internal `eq` function in test asserts

### ISSUE THREAD

**Issue by char0n** [char0n/ramda-adjunct#895]
Appropriate assert functions from [chai](https://www.chaijs.com/api/assert) should be used to be more explicit.

Code like this:
```js
describe('ensureArray', function() {
  context('given argument is not an array', function() {
    specify('should wrap value into singleton array', function() {
      const arrayPrototype = Array.prototype;

      eq(RA.ensureArray(void 0), [void 0]);
      eq(RA.ensureArray({}), [{}]);
      eq(RA.ensureArray(null), [null]);
      eq(RA.ensureArray(undefined), [undefined]);
      eq(RA.ensureArray(42), [42]);
      eq(RA.ensureArray('Array'), ['Array']);
      eq(RA.ensureArray(true), [true]);
      eq(RA.ensureArray(false), [false]);
      eq(RA.ensureArray({ __proto__: arrayPrototype }), [
        { __proto__: arrayPrototype },
      ]);
    });
  });
});
```
has to become like this:
```js
import { assert } from 'chai';

describe('ensureArray', function() {
  context('given argument is not an array', function() {
    specify('should wrap value into singleton array', function() {
      const arrayPrototype = Array.prototype;

      assert.sameOrderedMembers(RA.ensureArray(void 0), [void 0]);
      assert.sameDeepOrderedMembers(RA.ensureArray({}), [{}]);
      assert.sameOrderedMembers(RA.ensureArray(null), [null]);
      assert.sameOrderedMembers(RA.ensureArray(undefined), [undefined]);
      assert.sameOrderedMembers(RA.ensureArray(42), [42]);
      assert.sameOrderedMembers(RA.ensureArray('Array'), ['Array']);
      assert.sameOrderedMembers(RA.ensureArray(true), [true]);
      assert.sameOrderedMembers(RA.ensureArray(false), [false]);
      assert.sameDeepOrderedMembers(
        RA.ensureArray({ __proto__: arrayPrototype }),
        [{ __proto__: arrayPrototype }]
      );
    });
  });
```

**Comment by char0n** [comment]
@js636f i've updated the ticket description to bring more clarity.

**Comment by js636f** [comment]
@char0n, OK, thanks.

**Comment by js636f** [comment]
@char0n, I found a test which still uses eq and made a [PR](https://github.com/char0n/ramda-adjunct/pull/1142).

**Comment by char0n** [comment]
@js636f there is tons of them actually ;] Thank you for the PR.

**Comment by js636f** [comment]
@char0n, you are welcome! I'll find another tests to edit (I think I'll edit them in small batches - around 3-5 files to keep things maintainable) and make another PRs.

**Comment by js636f** [comment]
@char0n, here is Batch 2 [PR](https://github.com/char0n/ramda-adjunct/pull/1149)

**Comment by js636f** [comment]
@char0n, here is Batch 3 [PR](https://github.com/char0n/ramda-adjunct/pull/1155)

**Comment by js636f** [comment]
@char0n, here is Batch 4 [PR](https://github.com/char0n/ramda-adjunct/pull/1156)

**Comment by js636f** [comment]
@char0n, here is Batch 5 [PR](https://github.com/char0n/ramda-adjunct/pull/1157)

**Comment by char0n** [comment]
Keep it comming ;]

**Comment by char0n** [comment]
The goal here is to get rid of `eq` function.

**Comment by js636f** [comment]
@char0n, here is Batch 6 [PR](https://github.com/char0n/ramda-adjunct/pull/1160)

**Comment by js636f** [comment]
@char0n, here is Batch 7 [PR](https://github.com/char0n/ramda-adjunct/pull/1163)

**Comment by js636f** [comment]
@char0n, here is Batch 8 [PR](https://github.com/char0n/ramda-adjunct/pull/1165)

**Comment by char0n** [comment]
Very cool, keep it comming. You're increasing quality of this codebase considerably.

**Comment by js636f** [comment]
@char0n, I'm happy to help, here is Batch 9 [PR](https://github.com/char0n/ramda-adjunct/pull/1169)

**Comment by js636f** [comment]
@char0n, here is Batch 10 [PR](https://github.com/char0n/ramda-adjunct/pull/1171)

**Comment by js636f** [comment]
@char0n, here is Batch 11 [PR](https://github.com/char0n/ramda-adjunct/pull/1174)

**Comment by js636f** [comment]
@char0n, here is Batch 12 [PR](https://github.com/char0n/ramda-adjunct/pull/1176)

**Comment by js636f** [comment]
@char0n. here is Batch 13 [PR](https://github.com/char0n/ramda-adjunct/pull/1177)

**Comment by js636f** [comment]
@char0n, here is Batcn 14 [PR](https://github.com/char0n/ramda-adjunct/pull/1181)

**Comment by js636f** [comment]
@char0n. here is Batch 15 [PR](https://github.com/char0n/ramda-adjunct/pull/1182)

**Comment by js636f** [comment]
@char0n, here is Batch 16 [PR](https://github.com/char0n/ramda-adjunct/pull/1184)

**Comment by js636f** [comment]
@char0n, here is Batch 17 [PR](https://github.com/char0n/ramda-adjunct/pull/1185)

**Comment by js636f** [comment]
@char0n, here is Batch 18 [PR](https://github.com/char0n/ramda-adjunct/pull/1187)

**Comment by js636f** [comment]
@char0n, here is Batch 19 [PR](https://github.com/char0n/ramda-adjunct/pull/1192)

**Comment by js636f** [comment]
@char0n, here is Batch 20 [PR](https://github.com/char0n/ramda-adjunct/pull/1193)

**Comment by js636f** [comment]
@char0n, here is Batch 21 [PR](https://github.com/char0n/ramda-adjunct/pull/1195). 

All tests in the main folder are ready. Do I need to refactor tests in test/fantasy-land/ and test/internal/?

**Comment by js636f** [comment]
@char0n, here is Batch 22 [PR](https://github.com/char0n/ramda-adjunct/pull/1196)

**Comment by char0n** [comment]
@js636f great job here. Thank you!

**Comment by js636f** [comment]
@char0n, I'm happy we finished this. Thank you for your help with all this assertions details.

**Comment by char0n** [comment]
No, problem, any time...
