### ISSUE TITLE
isPair

### ISSUE THREAD

**Issue by rockymadden** [char0n/ramda-adjunct#90]
@char0n open to a PR for `isPair` and `isNotPair`? Something along the lines of:
```javascript
const isPair = both(isArray, pipe(length, equals(2)));
const isNotPair = complement(isPair);
```

**Comment by char0n** [comment]
LGTM. go for it. There is [pair](http://ramdajs.com/docs/#pair) util in ramda so why not having a predicate for it.

**Comment by char0n** [comment]
@rockymadden wanna go for this one in the next release ? ;]
