### ISSUE TITLE
mergePath typing is wrong

### ISSUE THREAD

**Issue by borys-kupar** [char0n/ramda-adjunct#925]
TypeScript method definition for mergePath function seems to be wrong.

Current code:
```
mergePath(path: Array<Array<string | number>>, source: object, obj: object): object;
```

According to documentation, the first argument is array of strings or numbers, but not an array of arrays.

This example currently throws TS error:
```
RA.mergePath(
   ['outer', 'inner'],
   { foo: 3, bar: 4 },
   { outer: { inner: { foo: 2 } } }
); => { outer: { inner: { foo: 3, bar: 4 } }
```
-> `Type string is not assignable to to type (string | number)[]`

**Comment by char0n** [comment]
Hi @borys-kupar,

Thank you for reporting this. Would you be able to provide a PR for this ?

**Comment by borys-kupar** [comment]
@char0n, sure
