### ISSUE TITLE
sortByProp and sortByPath and orderByProp and orderByPath

### ISSUE THREAD

**Issue by dimitropoulos** [char0n/ramda-adjunct#945]
I'm inclined to wonder, would you be interested in a set of functions (similar to lodash's [sortBy](https://lodash.com/docs/4.17.11#sortBy) and [orderBy](https://lodash.com/docs/4.17.11#orderBy)) which could sort an array of objects with respect to one of the properties.

for the given data:
```js
const data = [
  {
    a: 1,
    b: {
      c: 2
    },
  },
  {
    a: 1,
    b: {
      c: 3
    },
  },
  {
    a: 2,
    b: {
      c: 2
    },
  },
  {
    a: 2,
    b: {
      c: 1
    },
  },
];
```

sortByProp would work like `sortByProp(['a'])(data)` or possibly `sortByProp('a')(data)` if you want to have one that just supports one prop ascending.

sortByPath would work like `sortByPath([['a'], ['c', 'd']])(data)`

orderByProp and orderByPath would be the same thing, just that you would be able to specify a comparator e.g. `orderByProp([['a', descend]])(data)` or `orderByPath([[['a'], descend], [['b', 'c'], descend]])(data)`;

I'll admit, having typed that out it looks a little scarier than I'd like, but the I also gotta mention that this function is something I need very often and end up implementing like this with vanilla ramda:
```js
data = sortWith([
  ascend(path(['location', 'start', 'line'])),
  ascend(path(['location', 'start', 'character'])),
], data)
```

**Comment by dimitropoulos** [comment]
I would like to also add, as an aside, that I have tried the version of this offered up in the ramda cookbook:
https://github.com/ramda/ramda/wiki/Cookbook#sort-a-list-by-array-of-props-if-first-prop-equivalent-sort-by-second-etc
and I had quite some trouble getting the types (with typescript) to work, whereas the above solution with sortWith works well "out of the box"

**Comment by char0n** [comment]
`sortByPath` seems valid. `sortByProp` can be then just specialization of `sortByPath`. Regarding `orderByProp|Path` I'm not sure about those two. If you want to go further with this, provide a PR with `sortByPath` and we'll go from there ;]

**Comment by char0n** [comment]
sortByProps mentioned in [ramda cookbook](https://github.com/ramda/ramda/wiki/Cookbook#sort-a-list-by-array-of-props-if-first-prop-equivalent-sort-by-second-etc)

**Comment by char0n** [comment]
I've extracted 3 issues from your descriptions that are references under this issue. If you with to also extract `orderBy` functions, which I'm not sure about their behavior, pls use new feature template when creating a new issue and describe in details the behaviour and possible implementation. Thank you!
